### ISSUE TITLE
[Bug]: Invisible app menu items when using split menu bar shape

### ISSUE THREAD

**Issue by davidsule** [jordanbaird/Ice#103]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

The bug happens when the active app (see note) has so many menu items that some show on the right side of the notch normally, and you turn on the split menu bar style. Then, the buttons to the right of the notch become invisible but still clickable. The pill (or rectangle) shape under the menu bar items doesn't reach the invisible items but reaches partway under the notch.

Note: Microsoft Edge is the only app I have with that many menu items so I couldn't test is with others.

[2021 M1 Pro Macbook Pro 14]

### Steps to Reproduce

1. Set the menu bar shape to split in Ice
2. Open app with enough menu items that some are on the right side of the notch.

### Ice Version

0.9.0

### macOS Version

14.5

### Screenshots

https://github.com/jordanbaird/Ice/assets/78355622/4561efec-c20d-49f5-bdcb-83a2af65d187

**Comment by davidsule** [comment]
Oops, I think 3 of us opened a bug report about this issue within a few minutes of each other.

**Comment by jordanbaird** [comment]
Thanks for the report! My MacBook doesn't have a notch, so this bug is probably going to have to wait until I can get one. But thankfully, seeing the insane amount of support I've been getting over the past couple of days, that might not be too far off. I'll get to this one as soon as I'm able :)

**Comment by davidsule** [comment]
Thank you for your work! :) Tbh this isn't a huge issue for me and given the influx of people I'm sure you're swamped and there are many higher priority stuff.

**Comment by jordanbaird** [comment]
You're welcome! I'll get to it when I can :)

**Comment by jordanbaird** [comment]
@davidsule Thinking back, I want to say this was resolved either in the most recent update or the one before that. Can you confirm?

**Comment by davidsule** [comment]
@jordanbaird Indeed it is! Time to switch to the split shape! ^^
