### ISSUE TITLE
[Bug]: Menu Bar Items that overflow past notch not visible in split mode.

### ISSUE THREAD

**Issue by dfrl-dev** [jordanbaird/Ice#104]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

**Device Model:** 14-inch 2021

When viewing an application whose menu bar items overflow beyond the webcam notch, the items are not visible - though they can still be opened.  The split menu bar also doesn't extend beyond the notch.

### Steps to Reproduce

1. Open an application whose menu overflows beyond the webcam notch (Xcode does on my 14" MacBook Pro - the window and and help tab appear to the right of the notch.
2. Set to Full mode - all menu items are visible
3. Set to split mode - Window and Help are missing, and the menu bar doesn't exist where they should be.
4. Click where the Window and Help menu items should be - the context menus still open, despite not being visible.

### Ice Version

0.9.0

### macOS Version

14.5

### Screenshots

<img width="1512" alt="Screenshot 2024-06-06 at 11 22 35 AM" src="https://github.com/jordanbaird/Ice/assets/6496412/93672ff8-bc82-48d6-9534-593cd0dd6f5b">

<img width="1512" alt="Screenshot 2024-06-06 at 11 21 47 AM" src="https://github.com/jordanbaird/Ice/assets/6496412/07fb4fc8-dec5-47ac-a914-b90b66c5f2e5">

<img width="1512" alt="Screenshot 2024-06-06 at 11 21 56 AM" src="https://github.com/jordanbaird/Ice/assets/6496412/e8a7f635-9566-4eea-92a9-9dc529f46af3">

**Comment by jordanbaird** [comment]
Closing in favor of #103
