### ISSUE TITLE
[Bug]: Screen Flicker

### ISSUE THREAD

**Issue by ItsPapaChaos** [jordanbaird/Ice#105]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

I was watching a show on Paramount+ and I noticed that about every 5 seconds, there was a very quick black screen flicker within the video player. It only seems to happen when not in fullscreen mode and does not happen when Ice is disabled.

### Steps to Reproduce

Watch a show on Paramount+ and see if the screen has a quick flicker every 5 seconds or so.

### Ice Version

0.9.0

### macOS Version

14.5

**Comment by jordanbaird** [comment]
Hmm, I thought I had fixed this issue. It has to do with capturing the screen while DRM content is visible. Screen capture should only ever happen if you have the menu bar appearance settings enabled. And even then, only the desktop background is captured, so it shouldn't be affecting DRM content. I'll do some research and see what I can find out.

**Comment by di11ard** [comment]
I am also experiencing screen flickering while watching Hulu.

**Comment by jordanbaird** [comment]
@di11ard Good to know. Same thing, every 5 seconds?

**Comment by di11ard** [comment]
@jordanbaird Sometimes it is ~5 seconds, and sometimes it will “skip” an interval and flicker after ~10 seconds.

I am experiencing a white flicker watching Hulu.

Using a stopwatch, I logged each flicker over the course of 60 seconds. Each entry is the time at which I hit the lap button to “log” a flicker. There will be variation as I am manually logging the events and not timestamping the exact time the flicker occurs.

Flicker
1. 5.1
2. 10.0
3. 20.0
4. 25.3
5. 30.1
6. 35.2
7. 40.0
8. 50.1
9. 55.2
10. 60.1

So, over the course of 60 seconds, I experienced 10 flickers. The timing between flickers does appear to be rather consistent.

Other observations:
- Running ICE without menu bar appearance customization settings allows me to watch content without flicker, but only if I start ICE without customizations.
- While Hulu is open (and customizations are on), ICE becomes very slow to respond.
- Disabling customizations, but not killing/restarting ICE, has zero impact on flicker, as the flashes will continue.
- Flickers will occur even when content is paused (this observation is probably not that surprising, but I figured I’d share).

**Comment by AdaMiez** [comment]
same here with Safari-Firefox watching German TV streams

**Comment by mikesprague** [comment]
I'm also experiencing this with multiple streaming providers. I do have menu bar customizations enabled and seeing flicker approx every 5 seconds (as others have noted). Exiting Ice eliminates the flicker.

**Comment by RonJ7** [comment]
I'm experiencing the exact same flickering issue with Apple TV. There is a flicker, then a black screen every few seconds. I am currently running MacOS 14.5, on an M3 MacBook Air.

**Comment by edgarvoit** [comment]
Same issue here - flickering with tv.app (Apple TV) content. It's a very inconsistent flicker, sometimes with larger gaps, sometimes blacking out for several seconds.

Running 14.5 on an M1 Macbook Pro.

**Comment by devmil** [comment]
I can confirm this happening on my machine as well. Tried different browsers, same result.
M1 Macbook Pro, Sonoma 14.5

**Comment by vodium-vastro** [comment]
Same here. Sonoma 14.5, Ice 0.9.0.

Netflix in Safari.

Flickering is random in gap. Quitting Ice resolves the issue.

Many thanks.

**Comment by giakinh0823** [comment]
I have the same problem, and sometimes the whole screen flashes. I took it to warranty and was told that the machine has no fault, I realized it was the ice application.

I am using macbook pro M4 pro - Sequoia 15.3.2
