### ISSUE TITLE
[Bug]: Icon shown in hidden section

### ISSUE THREAD

**Issue by Nik3in** [jordanbaird/Ice#107]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

I have tried to hide any icon that comes after the Ice icon but whatever application has an icon is showing, regardless of the options I check, the only solution is to hide it permanently.

### Steps to Reproduce

1. Press the Ice icon
2. Press it again
3. The application does not hide

### Ice Version

0.9.0

### macOS Version

Sonoma 14.5

### Screenshots

![Captura de pantalla 2024-06-06 a la(s) 13 30 46](https://github.com/jordanbaird/Ice/assets/171967534/2aced649-f1b2-41d1-8e3f-5bfbb9fbee58)
![Captura de pantalla 2024-06-06 a la(s) 13 31 19](https://github.com/jordanbaird/Ice/assets/171967534/0588d24f-bc9d-4ff2-a06e-69d793b10647)
![Captura de pantalla 2024-06-06 a la(s) 13 30 57](https://github.com/jordanbaird/Ice/assets/171967534/34088977-a8ac-4aa5-89ce-406908f70566)
![Captura de pantalla 2024-06-06 a la(s) 13 35 40](https://github.com/jordanbaird/Ice/assets/171967534/c9c68f92-4321-467b-a3eb-c721dab84a4f)
![Captura de pantalla 2024-06-06 a la(s) 13 36 01](https://github.com/jordanbaird/Ice/assets/171967534/91a35979-243f-4890-8ebe-5ea5786346dc)

**Comment by jordanbaird** [comment]
The Ice icon isn't what determines what gets hidden. There are two "divider" items that get shown when you Command+drag items around. Put the ones you want hidden to the left of the larger divider, and the ones you want always hidden to the left of the smaller divider. Note that the dividers are chevron-like arrows, so don't get them confused with your Ice icon. Also, if you want everything to the left of your Ice icon to be hidden, simply drag the larger divider immediately to the left of the Ice icon.

**Comment by Nik3in** [comment]
Perfect, I understand, in my case the smallest division was before all the other dividers causing no icon to be displayed, with your explanation I was able to solve it.
This is a suggestion, and in my opinion, these dividers should be fixed so that the areas are delimited so as not to cause confusion.

Thank you very much for such a wonderful app!
