### ISSUE TITLE
[Bug]: Moving icons cause the section dividers to appear

### ISSUE THREAD

**Issue by leoravagnani** [jordanbaird/Ice#112]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

When the section dividers are hidden in the settings, dragging any icon to change the order causes the dividers to appear. Even though this is meant to be helpful it ends up causing unwanted changes as all icons slide to the left when the dividers appear and this is further aggravated on notch Macs as icons get hidden when reaching the notch's limit. Sometimes we just wanna change the order of the icons but not the section they should be in so displaying the dividers is not useful.

My suggestion is to ditch this behavior (or make it optional) and add an "Edit" option to the bar icon menu to show the dividers - IMO this shouldn't be "buried" in the Advanced menu as it's core to the functionality of the app and my guess is people only turn it on to edit and then immediately turn it off as the dividers add visual clutter when showing.

I'm filling this under bug, but it may as well be a feature request if the current behavior is intended.

Keep the great work dude!!! MacOS should have this built-in for a long time.

### Steps to Reproduce

1 - Start cmd+dragging any icon in the bar.
2 - Even if you don't actually move it much, just starting will trigger it.
3 - The sections dividers will immediately show up.
4 - If your icon is to the left of any of the dividers observe where it will be sitting once the dividers show up. It will be moved further right than it was before even if you didn't actually move it.

### Ice Version

0.9.0

### macOS Version

14.5

### Screenshots

See how the Dropbox icon moved two icons to the right even though I haven't moved it.

https://github.com/jordanbaird/Ice/assets/13058201/9dafb4e3-a3ad-4833-9233-ec6ee269cae5

**Comment by jordanbaird** [comment]
I disagree that this is a bug, and I don't think it's needed anymore now that the primary method of moving items is in Ice's settings. I personally think it's useful to know where the sections are if you're moving the items directly in the menu bar.
