### ISSUE TITLE
[Bug]: <Wrong menu bar size with external display connected>

### ISSUE THREAD

**Issue by figurax** [jordanbaird/Ice#114]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

Menu bar height is rendered badly on Macbook Air M2 main display with external QHD display connected via usb-c. When disconnected, main display menu bar overlay is rendered properly.

![Screenshot 2024-06-07 at 09 41 53](https://github.com/jordanbaird/Ice/assets/140056046/557d4ccb-fa88-4b24-9312-071dffc36ec3)

<img width="853" alt="Screenshot 2024-06-07 at 09 42 05" src="https://github.com/jordanbaird/Ice/assets/140056046/c087d980-554f-4ac3-94ce-b70427c8f0ab">

Not sure if it is the same situation as in #97 and #102 since my menu bar is smaller than the other issues. 🤷‍♂️ May be that app is trying to fit the menu bar with different pixel density (2560x1440) and emulate in on native display with 1710x1120?

### UPDATE on the issue
After updating to 0.9.0 issue reversed. Native display in now OK, but external is twice as thick.

### Ice Version

0.8.0

### macOS Version

14.2.1

**Comment by lukasbesch** [comment]
![Screenshot 2024-06-07 at 13 51 33](https://github.com/jordanbaird/Ice/assets/241689/1ab4d870-d455-4d8f-9cbf-b6a84c1c13d8)

I do have the same problem. Left screen is a Macbook Pro M3 16", right is a 1920x1200 external screen.

I have the menu bar in split mode, but they are still connected in a light shade as you can see on the left.

**Comment by tbr** [comment]
![image](https://github.com/jordanbaird/Ice/assets/690402/c5aa3fae-0234-473f-bbef-65e7900b5878)

Similar problem, though the alignment is different than what @figurax has :)

**Comment by FederaikLudikon** [comment]
Same here
<img width="1728" alt="Monitor01" src="https://github.com/jordanbaird/Ice/assets/72828638/89f917c5-9cf1-4f2d-b58d-d43458d348c1">
<img width="1920" alt="Monitor02" src="https://github.com/jordanbaird/Ice/assets/72828638/5ecc85f7-bd8d-4a6d-b2ff-b4b901fe976d">

**Comment by jordanbaird** [comment]
I believe this is in fact the same issue as #97. It comes down to Ice picking one display and using it to render the appearance. I'm going to close this in favor of the existing issue.
