### ISSUE TITLE
"always hidden objects" for ever lost

### ISSUE THREAD

**Issue by AdaMiez** [jordanbaird/Ice#117]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

Hello, 
I have a big problem. I can no longer display my always hidden objects. Neither the option button nor a shortcut show me these objects. I have already deactivated and deleted ICE with App Cleaner&Uninstaller. Nothing helps!!!
It looks like the objects that I have marked as always hidden have disappeared forever.
When I restart my MacBook Pro, the objects are briefly displayed. But after some status of the system start they suddenly disappear.
Since I need the objects, I urgently need help!!!!

### Steps to Reproduce

no steps to reproduce!?
i shut down my MacBook yesterday evening and the problem appeared today.
The only thing I did was to use the MacBook in the evening without an external monitor and start the MacBook the next morning with an Apple Studio Display connected. 
I configured ICE without an external monitor and everything worked perfectly.

### Ice Version

0.8.0 - 0.9.0

### macOS Version

14.5

**Comment by jordanbaird** [comment]
It can't be Ice's fault if you have deleted it. It doesn't do any "marking" to remove items. It simply pushes them off the screen in real time. As soon as Ice is quit, all items will be back in their original positions. Are you sure you're not running some other app that is also doing some hiding?

**Comment by AdaMiez** [comment]
Hi Jordan,
because I was so unsettled by all the hype about Bartender, I made the switch to Ice. I hadn't deleted Bartender yet, but only closed it and switched off all permissions. Apparently these measures had not led to Bartender completely ceasing to work. This probably caused the bug I was experiencing. Only after I had completely deleted Bartender from my system were the icons visible again. I apologise for my bug report, but at least your answer has prompted me to take a closer look at my system.

Best regards and have a nice day
Michael

btw. Ice works wonderfully. Great work.
It doesn't have the possibilities of Bartender, or not yet, but we'll see what you come up with and what other possibilities you'll add.

**Comment by jordanbaird** [comment]
Thank you for the update! I'm glad you got it figured out :)
