### ISSUE TITLE
[Feature Request]: Hide App Menu

### ISSUE THREAD

**Issue by schester44** [jordanbaird/Ice#122]
### Description

Is it possible to hide the app menu items?

![CleanShot 2024-06-07 at 15 57 22@2x](https://github.com/jordanbaird/Ice/assets/15207595/286bac61-1df8-4a03-abf5-2fcbe7219ed8)

It would look super clean if the app menu displayed only the apple icon. Hovering the apple icon could show the app menu.

**Comment by jordanbaird** [comment]
It's sadly not possible, unless Ice stays active all the time. Even then, as soon as you click into another app, Ice will deactivate, which would break the feature.
