### ISSUE TITLE
Hidden Menu disappears when you click to make it re-appear in Dark Mode / Sonoma 14.3.1

### ISSUE THREAD

**Issue by exlemor** [jordanbaird/Ice#13]
Hi there Jordan,

Love ICE so far.

I have setup ICE on Sonoma 14.3.1 and in Light mode no issue so far but I have my Mac setup on Auto and when it switches to Dark mode automatically, things go slightly wrong.

I have these features/settings turned off: 

Always Hidden (couldn't get it toshow that 2nd 'Always Hidden' section but it's ok I don't have a super need for it)
Show on Hover turned off

I have these features/settings turned on:

Automatically rehide

Tint: Gradient - cursor all of the way to the right 

Menu Bar Shape mode: Split  

Left side: square -- rounded
Right side: rounded -- square

Ice Icon: Door

Attached: 2 images - normal and then what happens when I click on the Door :(

<img width="1670" alt="normal-with-ice-showing-icons-with-door-icon" src="https://github.com/jordanbaird/Ice/assets/2597232/21bb66ca-efb8-4e4e-aa8d-5e889a7620f2">

<img width="1666" alt="broken-with-ice-not-showing-icons" src="https://github.com/jordanbaird/Ice/assets/2597232/be4114ba-35ef-4c24-9b63-504fe943322c">

**Comment by jordanbaird** [comment]
Interesting...I'm in the process of re-implementing the menu bar appearance features anyway, so let's see if it still happens once the change goes live.

**Comment by exlemor** [comment]
OK, sounds like a plan - thank you for a great software nonetheless - so far useful. [started using it 2 days ago]

**Comment by jordanbaird** [comment]
@exlemor The newest release is out. Can you let me know if this is still occurring?

**Comment by exlemor** [comment]
New version 0.50 seems to work great ! [ I was writing to you as you wrote that comment ;) lol ].

For a future feature, it would be great to have a compartiment/section (where you can put some apps/icons on the Menu Bar) which you could lock behind a password (or thumbprint ) before being able to access. (with a lock icon?)

**Comment by jordanbaird** [comment]
Awesome, glad to hear it!

As for the feature suggestion, that does sound interesting, but I don't think it would be very secure, as the user could just bypass it by quitting the app.

I'm going to close this issue as completed, but if you have an idea on how the password feature could work, feel free to open another issue and we can discuss it there.

**Comment by exlemor** [comment]
Unfortunately, it seems that it is re-apppearing... ;(

The issue only appears when the Mac [ Sonoma 14.3.1 ] is in dark mode at night but not always... I'm not sure if it is tied to a  situation where the machine has a lack of memory or something else.. [32Gig of RAM, 2.9 GHz 6-Core Intel Core i9] or if it is related to a video bug [this Mac has 2 video cards]...

What would you like from me to help track it down?

**Comment by exlemor** [comment]
Yes, I think it is tied to a video glitch or lack of memory condition [but i'm no expert - just a hunch from 25 years of IT ;)]

No accessibility features enabled, a secondary display, running in a VM that I know of but I do have a few programs running... available for a screen share or equivalent if you need.

**Comment by jordanbaird** [comment]
Either of those would probably make sense. If lack of memory is the problem, there might not be much we can do about it. I'm hoping that's not the case.

Does it still happen if you don't use the menu bar appearance features? Also, what language and region is your system configured for?

**Comment by exlemor** [comment]
OK so some testing shows that it ONLY happens if I have Menu Bar --> Appearance --> Menu Bar Shape set to Split. 

Whether I have Tint set to Gradient or None is irrelevant [even though that is what I had wanted].

 Menu Bar Shape set to Full = no problem, set to None to problem but setup to Split = the issue comes back!

**Comment by jordanbaird** [comment]
After doing quite a bit of thinking on this, I hope (fingers crossed) to have come up with a fix. I'll try to get a release out today or tomorrow. If you could let me know one way or the other if it worked, that would be great :) thanks!

**Comment by exlemor** [comment]
Hi Jordan, @jordanbaird 

I was very hopeful but actually 0.6.1 breaks ICE for me...

After update to 0.61,
When I click on either the shortcut key or the Door icon, the menu of many icons no longer appears instead the door becomes a open door icon and the arrow icon switches to 1 icon the microphone icon because I have a tab open of whereby.com and the microphone tells me I have a tab open with a microphone/video open...

**Comment by jordanbaird** [comment]
Could you post screenshots, of both the hidden and shown states (door open and closed)?

**Comment by exlemor** [comment]
![screenshot_2427](https://github.com/jordanbaird/Ice/assets/2597232/f86167bb-1952-4593-b600-40d2cef446d6)
![screenshot_2428](https://github.com/jordanbaird/Ice/assets/2597232/af596328-1b66-4c69-8276-1101a1706077)

Here you are :) [ For comparison, I have like 10+ icons that appeared under version 0.60]

**Comment by jordanbaird** [comment]
Can you try these two things:
1. Reset the menu bar appearance settings. Do the icons show up now? If so, reapply the "split" setting and see if they disappear again.
2. Try Option+clicking either the door or the arrow. If the icons show up here, they somehow made their way into the "Always hidden" section and you should just have to drag them back out.

**Comment by exlemor** [comment]
FYI - the Always Hidden section is turned off in case that matters and has been for the past 2-3 versions.

OK, so I went and switched Split to None and the icons do not reappear... but if I hit the door icon they all re-appear but if I reheat the door icon, they all disappear and switching it back to Split after that creates the behavior shown in the screenshots above...

What next ? ;)

**Comment by jordanbaird** [comment]
So in other words, turning off the split menu bar feature gives the correct behavior, yes?

**Comment by exlemor** [comment]
yes. that is correct. (i think) ;)

**Comment by jordanbaird** [comment]
Try this build (although, expect it to be very buggy since it's a beta)
[Ice.zip](https://github.com/jordanbaird/Ice/files/14467754/Ice.zip)

**Comment by exlemor** [comment]
Hi @jordanbaird, 

That version seems to behave as expected there is an odd 'jump' when toggling back and forth but I guess that's the ßeta effect.

Thanks ;) I can use it again with Split mode on ;) (hug)

**Comment by jordanbaird** [comment]
No problem! Glad we finally got it resolved. As for the "jump" you're seeing, that is likely due to a macOS limitation that prevents Ice from seeing the changes in the menu bar right away, causing a slight delay before it updates. If you want, you can send a screen recording and I can verify if that's what you're seeing, or if you're okay with that, we can call it good :)

**Comment by exlemor** [comment]
For 3:34am, it's just fine as I'm tired and it might be my eyes playing a trick on me ;) 

If this weekend it's a real issue, I'll post a screen recording :D 

THANK YOU!

**Comment by jordanbaird** [comment]
@exlemor before I push out an official release, would you be able to test this build and make sure it still works as expected?
[Ice.zip](https://github.com/jordanbaird/Ice/files/14472338/Ice.zip)

**Comment by exlemor** [comment]
yes sure... sorry I didn't see your message earlier... let me test it right now.

**Comment by exlemor** [comment]
Seems to be working fine - but I will test it for the next hour or so... just to be sure.

**Comment by jordanbaird** [comment]
Awesome. Thanks for your help! If things seem to be working well, I'll go ahead with the new release.

**Comment by exlemor** [comment]
I'm going to get in trouble but I think I found an issue with 0.6.2 [just installed it] -- sorry ;( 

That or I misunderstood a feature of Ice... 

With the Text Editor screenshot, there is no separation between it [due to the width of its menu] and Ice [and the list of apps that are running 'under Ice']... and 2 icons are no longer showing... 

I perhaps misunderstood but thought that Ice would shrink the app to the left's menu [list of options]... perhaps it was for Ice that it would shrink the list of apps... but a visual separation would be amazing like | in white or something so we would know when 2 programs collide.

![Finder](https://github.com/jordanbaird/Ice/assets/2597232/f6c4f19d-359d-4f1a-a735-4f93867aca2e)
![Screen Capturor](https://github.com/jordanbaird/Ice/assets/2597232/bac844b4-4471-4077-8f3f-90453b1d7a0d)
![Text Editor](https://github.com/jordanbaird/Ice/assets/2597232/58c55b19-d3c0-49c7-98c8-24bcfb35baa8)

**Comment by jordanbaird** [comment]
So Ice does have this feature, but it's quite limited due to the design of macOS, which doesn't allow for the movement of application menus. The feature gets around this by having Ice activate when items are shown, so that its menu (which is empty) is shown instead of the active app. But when you click back into the previously active app, macOS forces that app's menu to be shown again, so it's really only useful for temporarily visualizing the full list of menu bar icons. If you want to try the feature, it's in `General` > `Hide application menus when showing menu bar items`. There's also a planned feature that will add a separate bar underneath the menu bar that might solve this problem for you (see the comments in issue #1)

No worries about finding extra things you think can be improved, btw. I want to make the app the best it can possibly be. In the future though, could you open separate issues for each new thing you find? The comment section on this one is getting pretty long haha.
