### ISSUE TITLE
[Bug]: Doesn't hide menubar in Full Screen mode, like in World of Warcraft.

### ISSUE THREAD

**Issue by Fred-IV** [jordanbaird/Ice#130]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

WoW and other full screen apps and games hide the macOS menubar, but with the new rounded bars, which I like very much, they are no longer hidden, and it causes screen display problems.
It needs to correct for this, or have an app exclusion list.

### Steps to Reproduce

1. turn on rounded menu bars.
2. Open a full screen app, like WoW.
3. Look at the top of the screen.

### Ice Version

0.9.0

### macOS Version

14.4.1

### Screenshots

For some reason, it will not screen capture.
Sometime, I can get it to go away, or come back.
Try app-switching, and using multiple desktop Spaces.
This will cause it to come and go...

**Comment by connorguy** [comment]
Same issue I think for me as well. More generalized to: Hiding full screen menu when bar shape option enabled.

<img width="1512" alt="Screenshot 2024-06-09 at 12 06 45" src="https://github.com/jordanbaird/Ice/assets/22226355/142ec824-4488-45e9-82e7-203e22b77ae1">

**Comment by PixelHir** [comment]
![CleanShot 2024-06-10 at 11 40 58@2x](https://github.com/jordanbaird/Ice/assets/7670940/b64828d7-7a96-4e44-867e-228dc07a5e83)
same issue while presenting with Keynote in fullscreen mode

**Comment by jordanbaird** [comment]
Closing this, as there have been multiple related reports of similar issues. I have opened #140 to track them together.
