### ISSUE TITLE
[Bug]: Icons go missing

### ISSUE THREAD

**Issue by black-snow** [jordanbaird/Ice#133]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

I moved my docker icon to the always displayed section and it worked fine last week. Now I start ice and it's just gone. It's neither getting rendered when icons are collapsed nor when they are expanded. No idea how to get it back.

### Steps to Reproduce

Hard to say. What I did:

1. move icon to always displayed section
2. wait some amount of time w/ several reboots in between
3. watch icon go missing as ice starts

### Ice Version

0.8.0

### macOS Version

14.5

### Screenshots

Ice not running:
![grafik](https://github.com/jordanbaird/Ice/assets/579733/ce279d79-870b-4547-abc2-8c076511fcf6)

Running, collapsed:
![grafik](https://github.com/jordanbaird/Ice/assets/579733/15c7fbc4-a697-4d09-ad17-7ba1e7239ec8)

Running, expanded:
![grafik](https://github.com/jordanbaird/Ice/assets/579733/71b748f6-feb8-432f-bd96-b500c560a54f)

**Comment by jordanbaird** [comment]
This is tracked in #6. Docker's macOS app has a wierd behavior where it resets the location of its icon, which puts it into the always-hidden section. Access it by Option+clicking the Ice icon. I'm going to close this, but just know that there's a feature being worked on that allows you to choose the location of your icons, and even if Docker resets its icon, Ice will move it back to the spot you chose.

**Comment by jordanbaird** [comment]
Also, I would recommend upgrading to 0.9.0. A lot of bugs are fixed in that version.

**Comment by black-snow** [comment]
Thanks for your super fast replies @jordanbaird !
