### ISSUE TITLE
[Bug]:  Can see menu bar while in full screen

### ISSUE THREAD

**Issue by michaelhonein** [jordanbaird/Ice#137]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

When in full screen with the rounded edges feature turned on, i can still see my menu bar outline

### Steps to Reproduce
![CleanShot 2024-06-11 at 05 14 59@2x](https://github.com/jordanbaird/Ice/assets/151960032/075c3206-b0dd-49f2-b356-49af74e26d53)

### Ice Version

0.9.0

### macOS Version

14.4.1

**Comment by jordanbaird** [comment]
Closing this, as there have been multiple related reports of similar issues. I have opened #140 to track them together.
