### ISSUE TITLE
[Feature Request]: Hide icon from dock

### ISSUE THREAD

**Issue by andrewcrook** [jordanbaird/Ice#139]
### Description

An option to hide the app's icon from the dock
when I start up and login the ice icon is always in the recently-active part of the dock

### Screenshots

![Screenshot 2024-06-11 at 11 28 43](https://github.com/jordanbaird/Ice/assets/803618/4854210b-aaba-4d6a-8ef1-5641db71b172)

**Comment by jordanbaird** [comment]
This is a feature of macOS. To turn it off, uncheck `System Settings > Desktop & Dock > Show suggested and recent apps in Dock`

**Comment by andrewcrook** [comment]
> This is a feature of macOS. To turn it off, uncheck System Settings > Desktop & Dock > Show suggested and recent apps in Dock

@jordanbaird 

That disables the whole feature for all apps. This isn't what I meant.
Many menubar apps don't show an icon in the dock when opened  or have an option to hide the icon from the dock.

example
![Screenshot 2024-06-11 at 12 31 18](https://github.com/jordanbaird/Ice/assets/803618/d6bd7984-68da-451a-87ef-a4e858805e28)

**Comment by jordanbaird** [comment]
Ah, I see. Sorry for the misunderstanding. I think I have a fix for that.

**Comment by andrewcrook** [comment]
@jordanbaird   no problem,  thanks

**Comment by jordanbaird** [comment]
Let me know if the icon still shows up in the next release

**Comment by DanielYang59** [comment]
I could confirm [Ice 0.11.13 (macOS Tahoe Beta 2)](https://github.com/jordanbaird/Ice/releases/tag/0.11.13-dev.2) seems to fix this issue (while the latest 0.11.12 doesn't) on macos 26.0. Thanks a ton!
