### ISSUE TITLE
[Bug]: Menu bar appearance showing in fullscreen

### ISSUE THREAD

**Issue by jordanbaird** [jordanbaird/Ice#140]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

Users have been reporting the that menu bar appearance overlay is showing in fullscreen on certain apps and websites. This seems to primarily be an issue with apps not using the macOS native fullscreen mode. Ice needs to figure out a way to reliably detect a fullscreen window, regardless of the method that is used.

### Steps to Reproduce

1. Open a video in VLC
2. Make sure `Settings > Video > Use the native fullscreen mode` is unchecked
3. Fullscreen the player

### Ice Version

0.9.0

### macOS Version

14.5

### Screenshots

<img width="1440" alt="mb-appearance-showing" src="https://github.com/jordanbaird/Ice/assets/90936861/20b49770-b7af-48c2-9ad0-bbaa341e54ed">

**Comment by jvdbiam** [comment]
What fixed the issue for me was changing my color profile in display settings and then changing it back. I found this by accident.
Hope this can help others.

**Comment by jvdbiam** [comment]
after restarting my mac the problem was back but I change color profiles and it works again

**Comment by andrewmccullough** [comment]
I am experiencing a similar issue when presenting a Keynote presentation in fullscreen. I have attached a screenshot. Artifacts remain at the top of the screen showing an outline of the left and right menubar and my desktop background in between.

![Uploading Screenshot 2024-06-18 at 5.34.32 PM.png…](screenshot)
