### ISSUE TITLE
[Bug]: Hover and click gestures are not compatible with Lickable Menu Bar

### ISSUE THREAD

**Issue by ermonas** [jordanbaird/Ice#146]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

While using Ice and Lickable Menu Bar in tandem, click and hover gestures will stop working altogether.

### Steps to Reproduce

1. Install Ice
2. Configure click and hover gestures
3. Install Lickable Menu Bar
4. Both gestures fail to work

### Ice Version

0.9.0

### macOS Version

14.5

**Comment by jordanbaird** [comment]
Oddly enough, this seems to have been fixed on `main`. I think it was the fix that addressed #139. The fix will be in the next release.
