### ISSUE TITLE
[Bug]: Dropbox icon disappeared

### ISSUE THREAD

**Issue by stagelevel** [jordanbaird/Ice#151]
### Check existing issues

- [x] I have checked existing issues and believe that my issue is not a duplicate

### Description

Everything has been working well for the past few days with Ice, however, I've now noticed that my Dropbox icon has disappeared. Has this been the case for others?

### Steps to Reproduce

Dropbox no longer appearing in menu bar.

### Ice Version

0.9.0

### macOS Version

Sonoma 14.5

**Comment by jordanbaird** [comment]
Dropbox was likely restarted at some point and its icon moved into the always-hidden section (see #150). Option+click the Ice icon to see the always-hidden items and drag it back into whichever section you had it in before. There is a fix being worked on for this
