### ISSUE TITLE
[Bug]: Notifications constantly being redrawn

### ISSUE THREAD

**Issue by pahles** [jordanbaird/Ice#154]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

I use OmniFocus which shows me notifications as alerts (they stay on the screen) in a group. Whenever Ice is running the notifications are constantly being redrawn, either when they are collapsed or all showing. When I close Ice the notifications just sit there like they should.

### Steps to Reproduce

1. make sure you have more than one alerts from some app
2. start Ice, and watch the alerts being redrawn constantly
3. close Ice, the redrawing of the alerts stops
4. start Ice again and the alerts start being redrawn again constantly

### Ice Version

0.9.0

### macOS Version

14.5

**Comment by TheWeirdHomosapien** [comment]
I'm not sure if the problem I'm experiencing is similar to yours but when I click the notification center, the extra drop-down bar (which has a name that's agreed upon? idk) also shows up. Hopefully, the GIF will help to explain the problem more properly. Or if it's a user error then I would appreciate a suggestion for a fix. also apologies for the bad gif, 10mb limit
![Timeline 1](https://github.com/jordanbaird/Ice/assets/47301098/c391613c-32d4-4501-9cef-b09a3bb600ed)

**Comment by jordanbaird** [comment]
@TheWeirdHomosapien do you happen to have show-on-click enabled? What happens if you turn it off?

**Comment by TheWeirdHomosapien** [comment]
> @TheWeirdHomosapien do you happen to have show-on-click enabled? What happens if you turn it off?

That did the trick! thank you. It seems it was a user error yet again. Ill try to fiddle with the settings some more the next time around.

**Comment by jordanbaird** [comment]
@TheWeirdHomosapien I believe this is actually a bug in the beta. I made some changes to the way menu bar items are detected that seems to have broken it completely on some devices. Does clicking the notification center show the hidden section if you use 0.9.0?

**Comment by TheWeirdHomosapien** [comment]
@jordanbaird I downloaded 0.9.0 and it does not seem to show the hidden section when I click the notification center. This is true for both when I have show-on-click enabled or 
![Timeline 2](https://github.com/jordanbaird/Ice/assets/47301098/81af5606-5e31-4560-814b-cec17a15a719)
disabled.

**Comment by pahles** [comment]
The issue I reported only appears when there are two or more notifications from OmniFocus that have the same due date and time. The issue disappears when I close Ice.

**Comment by jordanbaird** [comment]
@pahles Interesting...could you post a screen recording of this happening?

**Comment by pahles** [comment]
https://github.com/jordanbaird/Ice/assets/3521661/e0790f68-2ff2-4c74-8ce0-d616a8e497ba

Just a short clip. When I'm recording the redrawing only happens once, as soon as I stop recording the redrawing continues constantly. There is no regularity, sometimes it takes a second, sometimes two, or five, or whatever. But it does not stop unless I quit Ice.

**Comment by KTsarlz** [comment]
The reappering notifications also happens to me. I don't use any app for my notifications.
They just reappear, multiple times even if I click clear or open thru it

**Comment by pahles** [comment]
@KTsarlz I'm not complaining about reappearing notifications.

@jordanbaird That said: there clearly is an issue with notifications and Ice.

**Comment by chatoo2412** [comment]
<img width="508" alt="image" src="https://github.com/user-attachments/assets/fa5062b8-d0c3-4fe5-b164-7bbed534d401">

"Allow notifications when mirroring or sharing the display"

Try turning this switch on.

**Comment by jordanbaird** [comment]
@chatoo2412 Interesting thought. @pahles On that note, how does it work with the latest release (0.10.2)? I switched to a different screen capture method.

**Comment by jordanbaird** [comment]
Closing as stale.
