### ISSUE TITLE
[Feature Request]: Hide / Display Items According to the Focus Mode

### ISSUE THREAD

**Issue by matthieugd** [jordanbaird/Ice#157]
### Description

Not sure if this is possible but it would be nice to leverage the current Focus mode to hide or display some apps like pomodoro timers , etc.

**Comment by jordanbaird** [comment]
I love this idea! I haven't checked yet, but I would be surprised if Apple didn't provide some way to monitor the current focus mode. This is already being tracked as part of #26, so I'm going to close this in order to keep things in one place.
