### ISSUE TITLE
[Feature Request]: Hover to show function edit

### ISSUE THREAD

**Issue by ZetaZan** [jordanbaird/Ice#159]
### Description

I'd love it if the hover in empty space didn't mean all over the menubar but just in the area where your hidden apps are.
Maybe you can update that or make it a toggle switch in the menu. 🙏🏻
Also took me a while to find out how to move and add apps to always hidden, maybe there could be a short instruction intro.
Love the tool btw

**Comment by jordanbaird** [comment]
I'm not entirely sure I follow. The area where you are supposed to be able to hover is the area between the application menus and the visible menu bar items. Is that not where the hidden items are?

And there is actually a much more intuitive method of item movement coming in the next update. But yes, I do plan on adding some instructions like you said.

**Comment by ZetaZan** [comment]
Hey, thanks for the quick response.
Right now it reacts everywhere in the bar, even on the left side of my camera notch.
Also I’ve noticed some glitching (flashes) every 3 seconds or so that pops up every now and then, especially when I watch a vid in fullscreen. (I’ll just turn it off when I do for now)
Yesterday when I was watching something in fullscreen the menubar didn’t want to dissapear, seems to be fine today (relaunched).
Cheers,
Daniel
________________________________

**Comment by jordanbaird** [comment]
The flashing and menu bar not disappearing in fullscreen are known issues and are being tracked. What version of Ice are you on?

**Comment by ZetaZan** [comment]
Ok, thought so.
Just downloaded it yesterday, 0.9.

From: Jordan Baird ***@***.***>
Date: Monday, June 17, 2024 at 13:09
To: jordanbaird/Ice ***@***.***>
Cc: ZetaZan ***@***.***>, Author ***@***.***>
Subject: Re: [jordanbaird/Ice] [Feature Request]: Hover to show function edit (Issue #159)


The flashing and menu bar not disappearing in fullscreen are known issues and are being tracked. What version of Ice are you on?

**Comment by jordanbaird** [comment]
Are you able to post a screen recording of this happening? I can't reproduce this on my computer, unless I'm still misunderstanding your problem.

**Comment by ZetaZan** [comment]
https://we.tl/t-Ho3qUZEFEd
In my opinion, if I move my mouse on the blank left side it shouldn’t react.
I kind of only want it to open when I’m hovering over the area where the invisible apps but I guess anywhere right of my cam notch (in the center) would be ok.

From: Jordan Baird ***@***.***>
Date: Friday, June 21, 2024 at 01:47
To: jordanbaird/Ice ***@***.***>
Cc: ZetaZan ***@***.***>, Author ***@***.***>
Subject: Re: [jordanbaird/Ice] [Feature Request]: Hover to show function edit (Issue #159)


Are you able to post a screen recording of this happening? I can't reproduce this on my computer, unless I'm still misunderstanding your problem.

**Comment by jordanbaird** [comment]
To do what you're saying would add a lot more complexity to an already fairly complex set of calculations to determine whether the mouse is in the correct location. The icons aren't made invisible, but are instead moved off the screen entirely. Either way, it's doing what it's designed to do, and I think what most people expect.

**Comment by ZetaZan** [comment]
Ok, no worries, thanks for taking the time to respond.
