### ISSUE TITLE
[Bug]: Simulated Input Ignored -Little Snitch GUI Scripting access required

### ISSUE THREAD

**Issue by cachrisman** [jordanbaird/Ice#162]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

I have [Little Snitch](https://obdev.at/products/littlesnitch/index.html) v6.0.1 (7102) installed and when I installed Ice, every menu bar item was in the Hidden menu. I tried to drag the Little Snitch menu bar display to the Visible menu and I got a pop up from Ice that said:

> Operation timed out

I also got a popup from Little Snitch with this warning:

> **Simulated Input Ignored**
> 
> For security reasons, Little Snitch has ignored mouse or keyboard input that was simulated by Ice. You can allow such simulated input in Settings > Security by enabling "Allow GUI Scripting access to Little Snitch".
> 
> PID: 5170
> Path: /Applications/Ice.app/Contents/MacOS/Ice

Before I enabled GUI Scripting Access to Little Snitch, inside the Ice settings, the Little Snitch menu bar item is missing (after I've tried to move it initially). It's only after I enable GUI Scripting access to Little Snitch and closed & reopened the Ice settings dialog does the Little Snitch menu bar item show up in the Ice settings, but something is still a little odd until I completely quit Ice and reopen it. This might also be similar/related in some way to #145 

So basically get it to work correctly I need have to do the following:

1. Quit the Ice application
2. check 'Allow GUI Scripting access to Little Snitch' in the Little Snitch Settings
3. Reopen Ice and open the Ice settings dialog
4. Move the Little Snitch menu bar item where I want it

Then I can turn off the 'Allow GUI Scripting access to Little Snitch' in the Little Snitch Settings if I want to minimize my security risk and the menu bar item will continue to behave according to the Ice settings. But if I want to move the Little Snitch menu bar item again in Ice settings, I need to enable GUI Scripting access before doing so.

If there's something that can be done to prevent this popup/problem with Little Snitch, that'd be awesome, but if "GUI Scripting" is essential to Ice's functioning, then I'd suggest adding a notice in the app or something to the Readme at least saying this is expected behavior and that it isn't a security risk as [Little Snitch describes it](https://help.obdev.at/littlesnitch6/pref-security) or that the additional security risk can be eliminated by disabling GUI Scripting access after moving the Little Snitch menu bar item.

Maybe reaching out to the team at Objective Development could help as well - https://obdev.at/support/contact 

### Steps to Reproduce

1. Have Little Snitch installed
2. Install Ice
3. Open Ice settings
4. try to move Little Snitch menu bar item from the Hidden bar to the Visible bar

### Ice Version

0.10.0-beta.3

### macOS Version

14.5

### Screenshots

Popup 1
<img width="250" alt="image" src="https://github.com/jordanbaird/Ice/assets/6521666/f0fd09bb-afd3-4d7b-94ad-96963a3c71b7">

Popup 2
![image](https://github.com/jordanbaird/Ice/assets/6521666/97f7b253-d753-43dd-a0dc-6355d17e0039)

**Comment by jordanbaird** [comment]
Thanks for the report! I was able to figure out a fix for this. I'll post a new beta soon with the fix.

**Comment by pawelkontek** [comment]
<img width="613" alt="Screenshot 2024-07-18 at 3 45 00 PM" src="https://github.com/user-attachments/assets/d820b6e4-0e32-4e0c-83d3-44338510c6de">
I am still constantly getting this error. It is possible that this app is causing this: https://github.com/objective-see/LuLu

I deleted it, but the error persists.

**Comment by jordanbaird** [comment]
@pawelkontek This usually happens when you have an app that is interfering with the events that Ice sends to move menu bar items. Specifically mouse events. I would look at LinearMouse and Loop as possible culprits. I don't recognize the other apps in your screenshot, so I can't comment on those. Of course, I am also looking into a general fix for this, as it remains a common issue for people.
