### ISSUE TITLE
Coming from Bartender problems

### ISSUE THREAD

**Issue by dreh65** [jordanbaird/Ice#163]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

Hi. I wonder if you had a guide for moving from BT to Ice? I tried that on my M2 MBA which has a notch. The items I have as always showing in BT show, but all the hidden items can’t be found. Maybe this is more of a feature request? In BT, there was a pref to show which items show and which stay “hidden”. Thanks for any light you might be able to shed.

### Steps to Reproduce

Simply installed Ice on the MBA with a notch. Couldn’t find my hidden items.

### Ice Version

0.9

### macOS Version

14.5

**Comment by dreh65** [comment]
Found the link to #1. Thanks.

**Comment by jordanbaird** [comment]
We do need a guide, though. Just haven't had time to write it.

**Comment by jordanbaird** [comment]
I just opened #165 as a more generalized issue, so any discussion regarding this will be found there.
