### ISSUE TITLE
[Bug]: No Menu Bar Items settings section

### ISSUE THREAD

**Issue by dvdvdmt** [jordanbaird/Ice#167]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

Hi 👋, I can't find the Menu Bar Items section in the settings. I can see it listed on the Readme page on this screenshot:
![image](https://github.com/jordanbaird/Ice/assets/8076700/9c25b72b-271e-4aaf-a3d0-1c86ab02c47e)

But I don't see it the installed version:
<img width="853" alt="image" src="https://github.com/jordanbaird/Ice/assets/8076700/9bde98b7-6fcf-47c5-aca5-3fabd2751660">

What I did:
- Remove the old app for bar management Hidden Bar.
- Install the menu bar using `brew install jordanbaird-ice`.
- Give it all the necessary permissions.
- Try to configure it.
- Reboot

### Steps to Reproduce

See the above

### Ice Version

0.9.0

### macOS Version

14.5 (23F79)

### Screenshots

<img width="866" alt="image" src="https://github.com/jordanbaird/Ice/assets/8076700/ea35f4f4-bdeb-4cdf-9a64-c2b0118675a1">

**Comment by dvdvdmt** [comment]
I've also tried to install the previous 0.8 version, which also doesn't have the Menu Bar Items section. So, I can't control the major part of it - hidden or always shown items.

**Comment by jordanbaird** [comment]
This is in the upcoming 0.10.0 release, which is still in beta. You can download the latest build [here](https://github.com/jordanbaird/Ice/issues/1#issuecomment-2176647022).

**Comment by dvdvdmt** [comment]
I see now, thanks! It is better highlight it somehow in the Readme

> ⚠️ Note that Menu Bar Items is Beta feature which you can access [here](https://github.com/jordanbaird/Ice/issues/1#issuecomment-2176647022)

**Comment by jordanbaird** [comment]
I mean, it does say "Coming soon..." right above the screenshot. The current beta updates too frequently to put a link to the latest one in the README, in my opinion. The full release will hopefully be out before too much longer anyway.
