### ISSUE TITLE
Ice does not properly remember app order

### ISSUE THREAD

**Issue by mvevitsis** [jordanbaird/Ice#172]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

Let's say I set my menu bar to have the following items (from right to left)
DeepL
Dropbox 
Ente

If I close one and reopen it again, it will not necessarily be in that order. It always seems to be off by one or two. For example:

DeepL 
Ente
Dropbox 

I like to keep my menu bar icons in alphabetical order (from right to left) so this is incredibly irritating. 

### Steps to Reproduce

1. Open some apps, organize them in ice
2. Close one app
3. Reopen it
4. Confirm position in menu bar

### Ice Version

0.9.0

### macOS Version

14.5

**Comment by jordanbaird** [comment]
Ice doesn't have the ability to arrange menu bar items. It only hides them. Not a bug with Ice, as it's macOS that's putting them in a different order. Once profiles are implemented with #26, this will no longer be a problem.
