### ISSUE TITLE
[Feature Request]: Spaces support

### ISSUE THREAD

**Issue by CharlesWiltgen** [jordanbaird/Ice#173]
### Description

macOS Spaces are a neat feature for organizing work, separating personal stuff from work stuff, etc.

Two problems with Spaces that are opportunities for ICE: (1) The UI for them is mostly hidden (the menu bar is an obvious home for this), and (2) they can’t be renamed. It would be neat if Mr. Baird could take a look at this for inspiration and sample code: https://github.com/Jaysce/Spaceman?tab=readme-ov-file

Thank you!

**Comment by SteveMattan** [comment]
While not an answer about Ice, naming spaces can be accomplished with [Hammerspoon](https://www.hammerspoon.org) and the spoon [SpaceName](https://github.com/ekalinin/SpaceName). I'm using it with Ice and it works fine.
