### ISSUE TITLE
[Bug]: Ice bar drawn under menu bar, under as in 'z-order' under, not below.

### ISSUE THREAD

**Issue by agingorange** [jordanbaird/Ice#174]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

My menu bar is set to automatically hide and show. When I click on the menu bar, the Ice bar is drawn _under_ the menu bar, so the menu bar overlaps it, partially hiding it. I can drag the ice bar so it's fully visible, but at the next invocation of Ice, the position of the ice bar is reset.

### Steps to Reproduce

1. Click on menu bar to open the Ice bar
2. The Ice bar is under the menu bar

### Ice Version

0.10.0 beta 4

### macOS Version

14.5

### Screenshots

<img width="610" alt="ice-bar-under-menu-bar" src="https://github.com/jordanbaird/Ice/assets/90155696/21e2b4c5-277e-413b-86ea-c28eba91ddc8">

**Comment by jordanbaird** [comment]
Just published beta 5. Give that a go and see if it's fixed.

**Comment by agingorange** [comment]
Excellent, the ice bar is now visible under the menu bar. 

Why is the ice bar draggable? I was hoping that its position would be remembered, but that is not the case. So, there must be another reason?

**Comment by agingorange** [comment]
Also, the only way to show the ice bar is to click on the ice icon? I could've sworn I could click on the open menu bar space to show it with beta 4?

**Comment by jordanbaird** [comment]
It's draggable mainly because someone asked me to make it that way haha. I've been experimenting with a feature that lets you pin the Ice Bar in place. It will be availablein a future update.

Clicking empty space isn't working for you? It should work. Did the setting somehow get switched off?

I'm going to close this as the main issue is resolved, but we can continue our discussion.

**Comment by agingorange** [comment]
Empty space isn't working and neither is scrolling. Both settings are enabled and both do work when the cursor is on the icon. I also tried hover which I don't use, and that doesn't work when the cursor is on empty space on the menu bar, nor when the cursor is on the icon.

Thanks for letting me know about it being draggable. :)

**Comment by jordanbaird** [comment]
Can you confirm that it still does work on beta 4? I want to make sure that it was a change I made in this beta, and not something that may have changed on your computer. It will help me track down the problem.

**Comment by agingorange** [comment]
Clicking and scrolling on empty space on the menu bar using beta 4 shows the ice bar. Just putting the cursor on the empty space (I assume that's hovering) does nothing.

**Comment by jordanbaird** [comment]
Maybe it would be a good idea to open a new issue for this. It sounds like this won't be a quick fix. Would you like to open one, or should I?

**Comment by agingorange** [comment]
Sorry, busy day.

Not sure what to tell you, but _everything started working!_ Including hover. I haven't changed anything, haven't rebooted. The only thing that happened with Ice is that I quit it, used beta 4 to answer your questions, and then used beta 5 again.

**Comment by jordanbaird** [comment]
That's really weird. I'm not sure whether this warrants its own issue or not, then. On the one hand, if it can happen once, it can happen again. On the other, maybe it was just something weird with the install the first time around 🤷

**Comment by murarisumit** [comment]
not able to see ice-bar drawn under menu bar, how to enable that setting ?

**Comment by jordanbaird** [comment]
@murarisumit Yep. Beta feature. Although I'd recommend being on beta 6, as there have been tons of improvements and bug fixes.
