### ISSUE TITLE
[Bug]: <Always-hidden section bug>

### ISSUE THREAD

**Issue by i-has-a-dat-GG** [jordanbaird/Ice#176]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

always-hidden section automatically hide my app even I pull it outside the section , then next time I open ice , it still hide some app that I don't want to be hide. 

### Steps to Reproduce

1. open my macbook
2. open ice
3. my menubar has been hide
4. click the ice icon to see some hidden app, but cannot see the "eul.app"
5. option + click to see always-hidden section and find out "eul.app" then pull it to normal section 
6. restart my macbook , it returned to its original hidden state

### Ice Version

0.9.0

### macOS Version

14.4.1

**Comment by jordanbaird** [comment]
This has been discussed at length in several other issues. Ice can't control where items appear, and doesn't currently do any moving of individual items. It's the behavior of macOS that's causing this. Once profiles are implemented in #26, this will no longer be a problem. It's being tracked there, so I'm going to close this.
