### ISSUE TITLE
[Bug]: cannot get screen recording permission in Sequoia

### ISSUE THREAD

**Issue by ndszz** [jordanbaird/Ice#177]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

Ice cannot get screen recording permission in sequoia

### Steps to Reproduce

1 open ice.app
2 click on grant permission under screen recording
3 nothing happens. does not open system preferences pane

### Ice Version

latest release

### macOS Version

macOS 15 beta 1 or 2

**Comment by jordanbaird** [comment]
There's a good chance this is just a bug in the Sequoia beta. I'll keep this open for now, but I expect this will be fixed before the official release.

**Comment by ishaanrathodd** [comment]
> 

can you give a hot fix for this? extremely annoying

**Comment by jordanbaird** [comment]
@ishaanrathodd I can fix it. But it only happens once, right? Once you manually grant permissions, it should go away.

**Comment by ishaanrathodd** [comment]
> @ishaanrathodd I can fix it. But it only happens once, right? Once you manually grant permissions, it should go away.

ah no, it pops every passing hour. Essentially atleast for me, if the app remains inactive for more than an hour, the permissions pop up again. If it was just after a restart i wouldn't care, but this happens not only on your app but so many more apps. But ill update u, the permissions were asked only onces in beta 4, if it pops up again ill let uk!

**Comment by jordanbaird** [comment]
@ishaanrathodd Are you sure you're not talking about the issue described in #170? If that's the case, this isn't a bug, but a change in macOS 15 that we're going to have to deal with. There's nothing we can do about it until Apple either adds missing functionality to the ScreenCaptureKit API, or rolls back on the change.

**Comment by ishaanrathodd** [comment]
> @ishaanrathodd Are you sure you're not talking about the issue described in #170? If that's the case, this isn't a bug, but a change in macOS 15 that we're going to have to deal with. There's nothing we can do about it until Apple either adds missing functionality to the ScreenCaptureKit API, or rolls back on the change.

damn im cooked, the app is almost unusable beacuse of the pop ups

**Comment by jordanbaird** [comment]
@ishaanrathodd If Apple doesn't make the change, I'll put out an update that prevents live menu bar item updates in the interface. That should at least minimize the number of times the alert appears, but we'll have to sacrifice functionality.

**Comment by ishaanrathodd** [comment]
> @ishaanrathodd If Apple doesn't make the change, I'll put out an update that prevents live menu bar item updates in the interface. That should at least minimize the number of times the alert appears, but we'll have to sacrifice functionality.

yeah better than being unusable

**Comment by jordanbaird** [comment]
@ndszz Is this still a problem as of the latest macOS 15 beta?

**Comment by ndszz** [comment]
Hi Jordan thanks for asking.  Fell off my radar.  I’ll take a look and let you know On Aug 16, 2024, at 2:32 PM, Jordan Baird ***@***.***> wrote:﻿
@ndszz Is this still a problem as of the latest macOS 15 beta?

**Comment by ndszz** [comment]
so I wasn't actually able to check I the issue I was having would still happen because the sequoia install I'm running was an update from a Sonoma instal that already had permissions granted. 

I will endeavour to make a new instal of sequoia at some point and I'll find out them if I'm able to grant the permissions or not

**Comment by mpstaton** [comment]
Also feeling it:
<img width="477" alt="image" src="https://github.com/user-attachments/assets/fdfb6fc0-eb28-4310-ba73-f97dd6c57df1">

**Comment by JuanVqz** [comment]
> Also feeling it: <img alt="image" width="477" src="https://private-user-images.githubusercontent.com/5722/364882416-fdfb6fc0-eb28-4310-ba73-f97dd6c57df1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MTY3OTMsIm5iZiI6MTcyNjcxNjQ5MywicGF0aCI6Ii81NzIyLzM2NDg4MjQxNi1mZGZiNmZjMC1lYjI4LTQzMTAtYmE3My1mOTdkZDZjNTdkZjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTlUMDMyODEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzAzZmM0MmQ5YzFhNjU2YTE0MGFmMGE3OGM5N2M0YzUzYTE3MDMxZGEyNmNkZTQ2N2E2MDFiMmRmNWQzN2FhNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4Okqbc4z9GDOYBi2ncBCsVjhwkiK2WT2Ksylekj29ds">

Same here!

**Comment by jordanbaird** [comment]
@JuanVqz Are you running the latest version of Ice (0.11.2)?

**Comment by JuanVqz** [comment]
> @JuanVqz Are you running the latest version of Ice (0.11.2)?

yes, I am. I installed it via Brew. Let me know if there is something else I can help with

**Comment by ndszz** [comment]
just wanted to report back, I was satisfied enough with sequoia that I ended up upgrading my Sonoma volume to sequoia rather than doing a fresh install

I never did encounter this issue again, presumably because the system already had permissions.

**Comment by jordanbaird** [comment]
I'm thinking this is an issue with Sequoia not showing the system dialog to request permissions. I think a workaround might be to have Ice manually open the settings window to the correct permissions pane, rather than relying on the system dialog to do it.

**Comment by jordanbaird** [comment]
Okay, I think I actually have something working using a different API to show the system dialog. Going to close this for now. Once the next release is out, if this still happens for anyone, let me know and I'll reopen this.

**Comment by axeII** [comment]
Hi @jordanbaird, 

I would like to report that I still have this issue. I am on macOS 15.1.1 and using the Ice version 0.11.12, and no matter what I tried - I am unable to add screen recording permission to the app. 

I am not sure if it's problem on macOS side but for example when I tried to add same permission to the zoom app I had no issue with that one.
