### ISSUE TITLE
[Bug]: Hidden items are treated as Always hidden?

### ISSUE THREAD

**Issue by getninjaN** [jordanbaird/Ice#179]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

I have to use option+click to show my hidden items. Does not matter if they're just "Hidden" or "Always hidden".

### Steps to Reproduce

Not sure how to reproduce.
I activated "Launch at login" after a reboot.

### Ice Version

0.9.0

### macOS Version

14.5

### Screenshots

https://github.com/jordanbaird/Ice/assets/1355935/62b68135-c49b-448e-966c-bf6fd6ef87cf

<img width="962" alt="image" src="https://github.com/jordanbaird/Ice/assets/1355935/68c373ec-a692-44cb-b2a9-3bfdce0ae7ef">
<img width="962" alt="image" src="https://github.com/jordanbaird/Ice/assets/1355935/99d606d1-0c79-43ef-b4c4-a6815b81c605">
<img width="962" alt="image" src="https://github.com/jordanbaird/Ice/assets/1355935/8483f0b7-6f70-4754-bb01-1cd7bb6eccb5">

**Comment by getninjaN** [comment]
<img width="827" alt="SCR-20240627-hisy" src="https://github.com/jordanbaird/Ice/assets/1355935/4dba876e-76d6-486b-9aef-140fee48bdf6">

<img width="827" alt="SCR-20240627-hiyz" src="https://github.com/jordanbaird/Ice/assets/1355935/e1c3097b-ea3b-4c39-8be6-a7c5d9b21ecc">

**Comment by simgust** [comment]
The same happens for me!

**Comment by jordanbaird** [comment]
You've moved the larger arrow (indicating the start of the hidden section) to the left of the smaller arrow (indicating the start of the always-hidden section). You're effectively telling Ice that the hidden section should be inside the always-hidden section.

I know this is unintuitive. The next update will enforce that the arrows stay in the correct order.

**Comment by getninjaN** [comment]
> You've moved the larger arrow (indicating the start of the hidden section) to the left of the smaller arrow (indicating the start of the always-hidden section). You're effectively telling Ice that the hidden section should be inside the always-hidden section.
> 
> I know this is unintuitive. The next update will enforce that the arrows stay in the correct order.

Oh! I didn't even register that they where different sizes.
Thanks! Moving the larger arrow to the correct place solved the issue.

**Comment by jordanbaird** [comment]
No problem! :)
