### ISSUE TITLE
[Bug]: Icon for Flow (pomodoro timer) is not visible

### ISSUE THREAD

**Issue by andreabusi** [jordanbaird/Ice#180]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

[Flow](https://www.flow.app/) is a pomodoro timer app that creates a countdown timer in the menu bar.

When Ice is in execution, the icon is not visibile. I tried to

### Steps to Reproduce

1. Open Flow app and set a timer
2. Icon is not displayed in menu bar
3. Close Ice app to reveal the Flow menu icon

### Ice Version

0.9.0

### macOS Version

14.5

### Screenshots

This is the menu bar when Ice is active:
![ice-active](https://github.com/jordanbaird/Ice/assets/847860/3ade03db-dde3-41e2-9613-743257e39c67)

And this is the menu bar with Ice closed
![ice-not-started](https://github.com/jordanbaird/Ice/assets/847860/9e2a2564-e3ae-4d38-8503-00626ca5a28b)

**Comment by jordanbaird** [comment]
The item likely got placed into the always-hidden section, which can be shown by Option+clicking the Ice icon. You can hold down Command and drag it out of the section. This isn't a bug with Ice, but rather a side effect of the way macOS treats new menu bar items. It places them at the far left of the menu bar, which is where the always-hidden section is. Once #6 and #26 are implemented, this will be much easier to manage.

**Comment by andreabusi** [comment]
> The item likely got placed into the always-hidden section, which can be shown by Option+clicking the Ice icon. You can hold down Command and drag it out of the section. This isn't a bug with Ice, but rather a side effect of the way macOS treats new menu bar items. It places them at the far left of the menu bar, which is where the always-hidden section is. Once #6 and #26 are implemented, this will be much easier to manage.

Thank you, I didn't notice of this feature. I can confirm that It was in the always-hidden section.

Thanks!
