### ISSUE TITLE
[Bug]: CPU spike every 1m20s

### ISSUE THREAD

**Issue by autonome** [jordanbaird/Ice#181]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

Seeing high CPU on macOS Sonoma 14.5 (23F79) / m2 macbook air.

I timed it. On my machine it's 1m20s between spikes and each spike is ~12s. 

Seems like something definitely happening on a timer. The spike length is likely variable across machines if it's workload based.

I saw the other perf bug, and it seemed more mysterious.

This issue is reproducible, happens on a timer.

### Steps to Reproduce

- run Ice
- watch Activity Monitor for many hours
- ok it won't take that long, you'll see the pattern

### Ice Version

0.9.0

### macOS Version

14.5

**Comment by jordanbaird** [comment]
Would you believe me if I said I can't reproduce it? Haha. On 0.9.0 or 0.10.2.

Watching it for a couple minutes each:

- On 0.9.0, it hovers around 0.7% CPU (menu bar appearance disabled); 1.7% CPU (menu bar appearance enabled)
- On 0.10.2, it hovers around 0.1% CPU (menu bar appearance disabled); 0.5% CPU (menu bar appearance enabled)

Running an M3 Pro, 18GB memory. I also have an M1, 8GB memory, which I haven't tested as thoroughly on, but still can't reproduce.

**Comment by autonome** [comment]
> Would you believe me if I said I can't reproduce it? Haha.

I've worked with desktop applications far too long to disbelieve anything 😉

Whether you can reproduce or not is less interesting than whether there is a timer that matches what I'm describing.

**Comment by jordanbaird** [comment]
> Whether you can reproduce or not is less interesting than whether there is a timer that matches what I'm describing.

Definitely not a timer for 1m20s. There _are_ various timers throughout the app, related to menu bar appearance, caching items, etc. Maybe some of them happen to line up every 1m20s to produce a higher CPU load. Are you still seeing the pattern on 0.10.2?

**Comment by autonome** [comment]
Just updated, will test today!

**Comment by autonome** [comment]
I'm seeing periodic spikes in low single digits now, but nothing like before and not on same schedule.
