### ISSUE TITLE
[Bug]: Ice icon remains visible in task switcher after interacting with Ice menu item

### ISSUE THREAD

**Issue by gingerbeardman** [jordanbaird/Ice#184]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

I'm the person who created the method of hiding the menu items for Dozer, so I understand that the icon needs to be visible in the task switcher for the menus to be able to be replaced with the blank ice menu.

But Ice fails to hide its task switcher icon in certain circumstances.

Seems like a simple logic problem.

### Steps to Reproduce

1. click ice bar icon (show hidden)
1. option click ice bar icon (show always hidden)
1. option click ice bar icon (undo show always hidden)
1. click ice bar icon (undo show hidden)

at this point the ice icon will remain visible in the task switcher

### Ice Version

- 0.10.0-beta.5

### macOS Version

- 14.5.0 (23F79)

### Screenshots

https://github.com/jordanbaird/Ice/assets/49612/a4a60958-c08e-4561-a9a2-56dd758736cf

**Comment by gingerbeardman** [comment]
Still a problem in 0.11.8.1

**Comment by jordanbaird** [comment]
@gingerbeardman Weird. I haven't been able to reproduce this problem at all.

**Comment by gingerbeardman** [comment]
I don't know what to say, I can reproduce it on demand :)

**Comment by jordanbaird** [comment]
@gingerbeardman Is Ice's icon visible in the dock when also visible in the task switcher? Or does it disappear from the dock, but stay in the task switcher?

**Comment by gingerbeardman** [comment]
both dock and task switcher

ps: I'm using auto hide Smart which seems a bit problematic. 

I've switched to Focused App and it seems to be behaving.

HTH

**Comment by jordanbaird** [comment]
@gingerbeardman Aha! That was the key piece of information I was missing. I can get it to happen when Smart rehide is triggered, _and_ both sections are shown, _and_ application menus are hidden. Seems like Smart rehide is bypassing the logic I have in place to deactivate the app.

**Comment by gingerbeardman** [comment]
Let's go!!!
