### ISSUE TITLE
[Bug]: fails to hide menus

### ISSUE THREAD

**Issue by gingerbeardman** [jordanbaird/Ice#185]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

sometimes showing always hidden menu bar items does not hide the menus of the current app even though they do not fit in the space available

### Steps to Reproduce

1. click ice bar menu item
2. option click ice bar menu item

### Ice Version

- 0.10.0-beta.5

### macOS Version

- 14.5.0 (23F79)

### Screenshots

https://github.com/jordanbaird/Ice/assets/49612/796dbd2a-714c-474e-aee7-1f63eea0f465

**Comment by jordanbaird** [comment]
This was fixed here: https://github.com/jordanbaird/Ice/commit/77c103c6ad9fd82357814c96942538f3a95f9c1c
