### ISSUE TITLE
[Bug]: Some icons moved back to "always hidden" upon inactivity

### ISSUE THREAD

**Issue by tigattack** [jordanbaird/Ice#189]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

The only app I've noticed this with is Discord. I don't know if others are affected.

Discord creates a menu bar icon for voice activity when you join a voice channel. I moved this to the "visible" section so I could always see it. I then noticed that after leaving voice and re-joining, the icon was moved back to the "always hidden" section.

### Steps to Reproduce

1. Join a voice call/channel on Discord
2. Move the voice activity icon to a section other than "always hidden"
3. Leave voice and quit Discord (quitting wasn't always necessary but proved most reliable to reproduce)
4. Re-open Discord and re-join a voice call/channel
5. See the voice activity icon is moved back to the "always hidden" section

### Ice Version

0.10.0-beta.5

### macOS Version

14.4.1

**Comment by jordanbaird** [comment]
See the [Frequent Issues](https://github.com/jordanbaird/Ice/blob/main/Documentation/FREQUENT_ISSUES.md)
