### ISSUE TITLE
[Bug]: Missing "Menu Bar Items" submenu

### ISSUE THREAD

**Issue by tombarys** [jordanbaird/Ice#190]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

I need help finding Menu Bar Items submenu.

### Steps to Reproduce

1. go to Settings
2. see :)

### Ice Version

0.9.0

### macOS Version

Sonoma 14.6

### Screenshots

![CleanShot 2024-07-01 at 19 36 50@2x](https://github.com/jordanbaird/Ice/assets/5729352/5c41728c-2c9a-47bb-905f-32d58ea64d3e)

**Comment by jordanbaird** [comment]
You need to be on the [0.10.0 beta](https://github.com/jordanbaird/Ice/releases/tag/0.10.0-beta.5)

**Comment by tombarys** [comment]
Thanks!

**Comment by jordanbaird** [comment]
No problem! And actually, I just released a new beta that's different from the one I linked. [0.10.0 (Beta 6)](https://github.com/jordanbaird/Ice/releases/tag/0.10.0-beta.6)
