### ISSUE TITLE
[Feature Request]: <Secondary>

### ISSUE THREAD

**Issue by alexistrn** [jordanbaird/Ice#199]
### Check existing feature requests

- [X] I have checked existing issues and believe that my feature request is not a duplicate

### Description

First of all, thank you, thank you and thank you again for this app. I'm a French user and like many others, I was baffled by the Bartender takeover and that's when I discovered Ice (this marvel one). 

I would like to propose a feature that exists at Bartender and which I personally miss quite a bit (even if I much prefer Ice): the possibility of having hidden applications + always hidden in a second menu bar, under the main menu bar. The main interest of this feature would be to allow those who use professional graphics, video, audio, etc. software, which have many menus in the menu bar, to display their applications fully in the menu bar , on a Macbook Pro with the notch. Because currently, when I use an application and there are too many menus, I can no longer display my items in the menu bar with Ice because they are automatically hidden so as not to conflict with the menus of the open application, which extends beyond the left side of the notch to sometimes encroach on the right side. 

Ideally, a system to manage what is visible, hidden or always hidden accessible from the settings and preferences of the Ice application would be a big plus (a bit like Bartender but others do the same: Ibar etc. .). 

THANKS !

### Screenshots

<img width="617" alt="BartenderBar@2x" src="https://github.com/jordanbaird/Ice/assets/112898349/0b585c6c-66bc-44ca-bb2c-4398c1fa1fa2">

![Items](https://github.com/jordanbaird/Ice/assets/112898349/5b8ab491-9ee4-43ca-ba7b-3b5d08194260)

**Comment by alexistrn** [comment]
![AddingGroup](https://github.com/jordanbaird/Ice/assets/112898349/cb5e0196-37e5-4856-bd67-450ae7b68d97)
<img width="617" alt="BartenderBar@2x" src="https://github.com/jordanbaird/Ice/assets/112898349/f3e1f28b-cbe3-4daa-8d0c-1956ba53553d">

**Comment by jordanbaird** [comment]
This is available in the [latest beta](https://github.com/jordanbaird/Ice/releases/tag/0.10.0-beta.6).

**Comment by alexistrn** [comment]
Thank you for this quick response ! I didn't know that, I'm sorry to have created a post if this was already planned!

**Comment by sizhky** [comment]
I'm unable to find this feature in the latest version...
