### ISSUE TITLE
[Feature Request]: <Margin with customization of the menu bar appearance>

### ISSUE THREAD

**Issue by alexistrn** [jordanbaird/Ice#200]
### Check existing feature requests

- [X] I have checked existing issues and believe that my feature request is not a duplicate

### Description

Hello ! I love Ice, and I find the function of customizing the appearance of the menu bar perfect: simple, effective and pleasant. 

There is a very small point that I would like to see modified for a future update (I don't know if I'm the only one?). 

When using the appearance customization functions (rounded corners, shape kind: full and split), I find that the outer margin of the bottom of the menu bar (between the background and the edge of the screen ) is too thin, especially on a Macbook Pro. This gives the impression that it is stuck to the edge of the screen, but not all the way, and with the rounding/border-radius, I find that it doesn't look as good as it could if there were more margin. Would it be possible to consider using a larger margin? Or add a feature that would allow you to change it yourself, like the three border sizes ? It looks a little less awkward with an added border but still a little in my opinion.

THANKS ! 

(Below some captures to illustrate my points)

### Screenshots

<img width="570" alt="Capture d’écran 2024-07-03 à 01 59 18" src="https://github.com/jordanbaird/Ice/assets/112898349/18a8f546-6da0-4571-9bb8-62be79a5a980">
<img width="676" alt="Capture d’écran 2024-07-03 à 01 57 26" src="https://github.com/jordanbaird/Ice/assets/112898349/d2664267-2aa1-412a-99b4-157dd3ea306d">

**Comment by jordanbaird** [comment]
As with your previous issue, this is also available in the [latest beta](https://github.com/jordanbaird/Ice/releases/tag/0.10.0-beta.6).

**Comment by alexistrn** [comment]
As with my first post, I'm still sorry to have created a useless post, but delighted that it's happening! Thank's.

**Comment by jordanbaird** [comment]
@alexistrn No worries! It happens :)
