### ISSUE TITLE
[Bug]: Ollama icon doesn't show

### ISSUE THREAD

**Issue by varna9000** [jordanbaird/Ice#202]
### Check existing and frequent issues

- [X] I have checked existing issues and believe that my issue is not a duplicate
- [X] I have read the [Frequent Issues](https://github.com/jordanbaird/Ice/blob/main/Documentation/FREQUENT_ISSUES.md) document, and my issue is not included there

### Description

When, loaded Ollama Icon doesn't show in Ice. When I quit Ice, the icon is there.

### Steps to Reproduce

Load Ice, Load Ollama.

### Ice Version

0.9.0

### macOS Version

14.5

**Comment by jordanbaird** [comment]
You didn't read the frequent issues that are linked in the template.
