### ISSUE TITLE
How do I update existing translation?

### ISSUE THREAD

**Issue by Svec-Tomas** [jordanbaird/Ice#203]
I am not able to locate the file needed for translation. Can you guide me, please, how do I update an existing translation? Maybe I just missed the guide or instructions how to contribute with the new / existing translations.

There is also some incorrect translations and also missing translation. Thanks!

**Comment by jordanbaird** [comment]
Ice doesn't do any localization right now, so any translations you are seeing must be built in to SwiftUI or AppKit, the two UI frameworks we use. Out of curiosity, what things are translated incorrectly?

As far as contributing to translations, I want to wait until the design of the interface is a little more stable before we start work on localizing. There is a discussion #160 that you can follow for updates regarding this.

**Comment by Svec-Tomas** [comment]
Sorry, I wanted to post this to other opened Safari tab with other Github project! But as you have replied already to my question. I am also ready to translate Ice to my native language, once you will be ready to accept contributions and translations! :)
