### ISSUE TITLE
[Feature Request]: Spacers and Groups

### ISSUE THREAD

**Issue by RedcoatAsher** [jordanbaird/Ice#204]
### Check existing feature requests

- [X] I have checked existing issues and believe that my feature request is not a duplicate

### Description

The ability to add spaces (size configurable) between items to better display information.
Also, groups that can be catered and expanded on click/hover to house related task/types of menubar items.

### Screenshots

<img width="636" alt="image" src="https://github.com/jordanbaird/Ice/assets/6314239/ad627745-41ac-4488-9c73-179c286cb2ca">

**Comment by jordanbaird** [comment]
Both of these are already requests. See #46 and #91
