### ISSUE TITLE
[Bug]: Slight white tint on place where menu bar is when window is tiled (not sure if bug or macOS thing)

### ISSUE THREAD

**Issue by highjeans** [jordanbaird/Ice#205]
### Check existing and frequent issues

- [X] I have checked existing issues and believe that my issue is not a duplicate
- [X] I have read the [Frequent Issues](https://github.com/jordanbaird/Ice/blob/main/Documentation/FREQUENT_ISSUES.md) document, and my issue is not included there

### Description

I'm not sure if this is a bug with Ice or not, but when using Ice and a different shape menu (aka menu bar shape selected as anything but None), I notice that on MacOS Sequoia, there is a small white-ish tint/line on the place where Apple's default menu bar ends (at least on my Macbook Pro 14" with the notch). Please see the screenshot.

### Steps to Reproduce

1. Open Ice on MacOS Sequoia
2. Go to Menu Bar Appearance and select the Menu Bar shape as anything but None
3. Tile any window
4. See the slight tint

### Ice Version

0.10.0-beta.6

### macOS Version

15.0 beta 2

### Screenshots

<img width="1510" alt="Screenshot 2024-07-04 at 13 58 12" src="https://github.com/jordanbaird/Ice/assets/77588045/e94176d2-b648-4808-a334-2a0ba8877101">

**Comment by jordanbaird** [comment]
This is a macOS thing. What you're seeing is the tiled window's shadow, which doesn't extend into the menu bar. To make this less obvious, you can turn off the margins in `System Settings > Desktop and Dock > Windows > Tiled windows have margins`. This will make the native snapping behave more like existing window managers, (i.e. Rectangle, Magnet).
