### ISSUE TITLE
[Bug]: Hidden section not showing

### ISSUE THREAD

**Issue by adrianfurlanc** [jordanbaird/Ice#206]
### Check existing and frequent issues

- [X] I have checked existing issues and believe that my issue is not a duplicate
- [X] I have read the [Frequent Issues](https://github.com/jordanbaird/Ice/blob/main/Documentation/FREQUENT_ISSUES.md) document, and my issue is not included there

### Description

Hidden Section not showing.

### Steps to Reproduce

The hidden section is not showing any icons,  I can right click and choose show the hidden section and nothing happens. If I choose show the always hidden section all the icons appear (including the hidden section). 

### Ice Version

0.9.0

### macOS Version

14.5

**Comment by adrianfurlanc** [comment]
Reinstalling fixed it

**Comment by jordanbaird** [comment]
What likely happened is that the item that indicates the start of the hidden section (larger arrow) got moved to the left of the item that indicates the start of the always-hidden section (smaller arrow). To prevent this from happening again, you could download the [latest beta](https://github.com/jordanbaird/Ice/releases/tag/0.10.0-beta.6), which enforces the order of these two items.
