### ISSUE TITLE
[Feature Request]: is there a way to stop OBS from getting moved to the always hidden section? i've moved it to hidden many times and it still puts itself in always hidden

### ISSUE THREAD

**Issue by ComfortableMilk4454** [jordanbaird/Ice#207]
### Check existing feature requests

- [X] I have checked existing issues and believe that my feature request is not a duplicate

### Description

is there a way to stop OBS from getting moved to the always hidden section? i've moved it to hidden many times and it still puts itself in always hidden

**Comment by jordanbaird** [comment]
There will be once #6 and #26 are implemented. Closing because this is already tracked there.

**Comment by ComfortableMilk4454** [comment]
Oh I see, thanks! Do you have any estimates on when those will be implemented?

**Comment by ComfortableMilk4454** [comment]
@jordanbaird ^

**Comment by jordanbaird** [comment]
@ComfortableMilk4454 I honestly don't know. It depends on how testing goes after the initial implementation, which I haven't started on. Tentative guess is at least a couple weeks to a month.

**Comment by ComfortableMilk4454** [comment]
awesome ty for letting me know :). look forward to this fix!

**Comment by ComfortableMilk4454** [comment]
@jordanbaird hey, any updates on the timeframe of this fix? tysm!

**Comment by jordanbaird** [comment]
I had to push it from 0.11.0 to 0.12.0, as there were too many things to implement. I currently don't have a timeframe, as things have come up personally that I'm dealing with, so work has slowed down over the last couple of weeks.

**Comment by ComfortableMilk4454** [comment]
no worries, thanks for telling me! i look forward to the fix :)))

**Comment by comfortablemilk4454** [comment]
@jordanbaird hey, just wondering how close we are to a release containing a fix for this? thanks so much!

**Comment by comfortablemilk4454** [comment]
@jordanbaird ^
