### ISSUE TITLE
[Feature Request]: Menu bar layout customisation

### ISSUE THREAD

**Issue by Romachamp** [jordanbaird/Ice#213]
### Check existing feature requests

- [X] I have checked existing issues and believe that my feature request is not a duplicate

### Description

Hello, I would like to see a feature for changing menu bar icons layout, like being able to put them beneath the menubar(similar to Bartender) or change their position overall.

**Comment by jordanbaird** [comment]
These are both already implemented in the [0.10.0 beta](https://github.com/jordanbaird/Ice/releases/tag/0.10.0-beta.6).
