### ISSUE TITLE
[Bug]: Right-click context menu appears when it shouldn’t; doesn’t appear when it should

### ISSUE THREAD

**Issue by natesilva** [jordanbaird/Ice#217]
### Check existing and frequent issues

- [X] I have checked existing issues and believe that my issue is not a duplicate
- [X] I have read the [Frequent Issues](https://github.com/jordanbaird/Ice/blob/main/Documentation/FREQUENT_ISSUES.md) document, and my issue is not included there

### Description

When in full screen, the right-click context menu shows over full-screen apps on my secondary monitor — when the menu bar is not visible.

On my laptop’s primary monitor (with a notch), the context menu doesn’t appear for full screen apps — when the menu bar is visible.

Configuration:

- 16-inch 2021 M1 MacBook Pro with “notch” screen
- Secondary monitor: LG 4K via Thunderbolt DisplayPort
- In System Settings → Control Center → Automatically hide and show the menu bar: “In Full Screen Only”

Apps I’m running in full-screen:

- Microsoft Remote Desktop
- VMWare Fusion running a desktop OS
- A video game

## Case 1: Context menu shows when it shouldn’t

1. Make an app go fullscreen on the secondary 4K monitor
2. Point near the top of the screen, but not _all_ the way to the top (so the menu bar does not appear)
3. Right-click

**Expected result:** The Ice context menu should not appear when the menu bar is not visible.

**Actual result:** Ice context menu appears over my game or Microsoft Remote Desktop session.

## Case 2: Context menu doesn’t show when it should

1. Make an app go fullscreen on the built-in laptop screen (with notch)
2. Point all the way at the top of the screen, so that the menu bar appears.
3. Right-click on the menu bar area

**Expected result:** The Ice context menu should appear.

**Actual result:** The Ice context menu does not appear.

### Ice Version

0.9.0

### macOS Version

14.5

### Screenshots

Case 1, running VMWare Fusion with Windows in fullscreen
![Running Microsoft Windows in fullscreen](https://github.com/jordanbaird/Ice/assets/160467/cd6deccc-020d-4636-8aad-c37c940e394e)
Case 1, running a Mac-native video game in fullscreen
![Video game in fullscreen](https://github.com/jordanbaird/Ice/assets/160467/ea345f01-4981-4330-ab81-475a16915c61)
(No screenshots for Case 2, sorry)

**Comment by jordanbaird** [comment]
First, thank you for the very thorough bug report. It's always helpful to have this many details.

Could you check the [latest beta](https://github.com/jordanbaird/Ice/releases/tag/0.10.0-beta.6) to see if the problems still happen? I believe issues with fullscreen menu bar checks should be fixed there.

**Comment by natesilva** [comment]
Hi Jordan,

I saw that 0.10.0 was just released. I tried with that version and the problem is fixed, both case 1 and case 2 work correctly now.

I’ll close this issue.

Thanks!
