### ISSUE TITLE
[Bug]: Click menu bar show/hide button on the secondary monitor will cause Ice icon appears in task bar

### ISSUE THREAD

**Issue by 50Death** [jordanbaird/Ice#219]
### Check existing and frequent issues

- [X] I have checked existing issues and believe that my issue is not a duplicate
- [X] I have read the [Frequent Issues](https://github.com/jordanbaird/Ice/blob/main/Documentation/FREQUENT_ISSUES.md) document, and my issue is not included there

### Description

I have two monitors: The Macbook built in monitor and an external display monitor(default).
Clicking hide button on default external monitor appears to be normal. But clicking the secondary macbook monitor will show this icon in task bar. Click one more time this icon will disappear.
![image](https://github.com/jordanbaird/Ice/assets/30155715/306800d9-0032-4a23-8131-923a7172dc66)
This icon appears when the menu bar icons are shown. This icon disappear when the menu icons are hidden.

A little bit of annoying.

### Steps to Reproduce

1. Have an external monitor
2. hide some random icons
3. click hide/show button on the secondary monitor

### Ice Version

0.9.0

### macOS Version

Sonoma 14.5 ARM

**Comment by jordanbaird** [comment]
You likely have the feature to hide application menus enabled. Your monitor is probably large enough to display all your menu bar items without them going behind the application menus. Your MacBook screen is probably too small, so Ice hides the menus. To do this, Ice needs to be active, which causes its icon to be shown in the dock.
