### ISSUE TITLE
[Bug]: "The "visible" section in settings "Menu Bar Items" is only available if Ice icon is activated in "General"

### ISSUE THREAD

**Issue by fnsign** [jordanbaird/Ice#224]
### CHECK EXISTING AND FREQUENT ISSUES

- [X] I have searched existing issues, and this bug has not been reported

### Description

Although a hot fix 0.10.1 was released, there still seems to be a bug in the visibility of sections in the "Menu Bar Items". The section for "visible" items disappears, if the Ice icon is de-activated in general settings. To make the section visible, the Ice icon has to be activated again.

### Steps to Reproduce

see description above

### Ice Version

0.10.1

### macOS Version

14.5

**Comment by jordanbaird** [comment]
Just to clarify, the actual items in your menu bar are still there, right? It's just the drag-and-drop interface in the "Menu Bar Items" settings pane that is gone?

**Comment by fnsign** [comment]
Yes, the items are still there.

BUT, if I reorder the items in the settings pane within a section or across sections, suddenly they may disappear as well as from the pane as from the menu bar. They don't re-appear, even if I quit and re-start Ice. So basically there are two bugs, regarding the settings pane.

**Comment by jordanbaird** [comment]
Interesting. I have an idea about that. Ice isn't supposed to be able to remove items, but this may be an exception. I'll play around with it and see if I can get items to disappear.

**Comment by jordanbaird** [comment]
Could you open a separate issue for the items disappearing, since it's not related to this bug?

**Comment by fnsign** [comment]
Yeah sure, I'll open a separate issue! Thanks for fixing this one!
