### ISSUE TITLE
[Bug]: Missing and duplicate items in Menu Bar Items settings

### ISSUE THREAD

**Issue by yaoyhu** [jordanbaird/Ice#225]
### CHECK EXISTING AND FREQUENT ISSUES

- [X] I have searched existing issues, and this bug has not been reported

### Description

The hot fix does not seem to be working.
1. Every time I tried to use the menu bar (`use ice bar` selected), the ice application would quit. 

![Screen Recording 2024-07-09 at 11 29 29 PM](https://github.com/jordanbaird/Ice/assets/86143910/37384465-0586-41f0-a378-de64a540e2d2)

2. It only works when `use ice bar` is deselected. But the `menu bar items` do not seem to be working either. Even if I set the layout I want, rearranged needed, missing items in menu bar preview, duplicated items in options window...

~~When I click the dots, every item gets hidden which conficting with what I want.~~: `<` should be in the `menu bar items`

<img width="852" alt="image" src="https://github.com/jordanbaird/Ice/assets/86143910/d24fc452-4646-43db-baf8-1cd7ec13e8c4">

![image](https://github.com/jordanbaird/Ice/assets/86143910/3005505a-1c2f-4644-87fb-9439f0a56fd1)

### Steps to Reproduce

See gif and video uploaded.

### Ice Version

0.10.1

### macOS Version

14.5

### Screenshots

Some items missing, some duplicated. Hard to reproduce.

**Comment by yaoyhu** [comment]
The 2nd part of my issue might be caused by conflicted `<` with menu bar items layout. And why the always hidden part not showing even with command key pressed. 

I'm so confused about the new version and hot fix. Is this because of my OS version?

**Comment by tigger04** [comment]
Just thought I would mention - are you running BetterTouchTool by any chance? I opened a similar defect to yours (https://github.com/jordanbaird/Ice/issues/226) but then closed it with some detail once I figured out a BTT tweak was conflicting it.

**Comment by jordanbaird** [comment]
This isn't related to the hot fix. That being said, it _is_ its own issue. Could you open the `Console` app, select "Crash Reports" in the side bar, and see if there's a crash report for Ice? That will at least give me a starting point.

**Comment by yaoyhu** [comment]
> This isn't related to the hot fix. That being said, it _is_ its own issue. Could you open the `Console` app, select "Crash Reports" in the side bar, and see if there's a crash report for Ice? That will at least give me a starting point.

[Ice-2024-07-10-081845.txt](https://github.com/user-attachments/files/16152406/Ice-2024-07-10-081845.txt)

**Comment by jordanbaird** [comment]
I'm thinking the crash is the same issue as @tigger04's. Maybe a different cause though. The crash reports look very similar. I've pushed a fix for that, so let me know if it keeps happening once the next release is out.

**Comment by jordanbaird** [comment]
> I do have BBT, but I've never used menu bar tweak. I've tried to quit the BBT, crash happened again.

I noticed you have OnlySwitch. If you go to "Customize" in the sidebar and disable "Hide Menu Bar Icons", does the crash stop? Or if you quit OnlySwitch? If either one of those is the case, I'm almost certain this is the same crash.

**Comment by yaoyhu** [comment]
> > I do have BBT, but I've never used menu bar tweak. I've tried to quit the BBT, crash happened again.
> 
> I noticed you have OnlySwitch. If you go to "Customize" in the sidebar and disable "Hide Menu Bar Icons", does the crash stop? Or if you quit OnlySwitch? If either one of those is the case, I'm almost certain this is the same crash.

The crash disappeared after disabling "Hide Menu Bar Icons". Thanks.

(But missing and duplicate items in Menu Bar Items settings still remain)

**Comment by jordanbaird** [comment]
@yaoyhu Are the items still duplicated after updating to 0.10.2?

**Comment by yaoyhu** [comment]
> @yaoyhu Are the items still duplicated after updating to 0.10.2?

Still remains, missing and duplication. I got a video recording for you.

https://github.com/user-attachments/assets/d4c065f4-346a-4f25-8a06-b8c92f42702c

**Comment by jordanbaird** [comment]
Interesting...thanks for getting back to me. Can you paste the following command into Terminal?

```
defaults export com.jordanbaird.Ice ~/Desktop/com.jordanbaird.Ice.plist
```

Then go to your desktop and upload the exported plist file here?

**Comment by yaoyhu** [comment]
`.plist` is not allowed to upload, use gzip.

[com.jordanbaird.Ice.plist.gz](https://github.com/user-attachments/files/16215696/com.jordanbaird.Ice.plist.gz)

**Comment by jordanbaird** [comment]
Thanks.

Also, just reading back through this thread, I noticed you were having trouble accessing the always-hidden section. It's the Option key, not the Command key that shows the section. Not sure if that helps with anything, but I thought I'd mention it. I'll see if I can diagnose the issue with the file you sent me.

**Comment by yaoyhu** [comment]
> It's the Option key, not the Command key that shows the section.

Thanks, I got it. 

So the main issue right now was shown in video: missing items after moving into Always-Hidden (`option + click` shows nothing) & these disappeared items still remain in Hidden section (in the menu bar, not Menu Bar Items setting).

Hard to describe in words, see video.

**Comment by yaoyhu** [comment]
The issue seems to be resolved after several new releases. A funny thing worth mentioning is that dragging the icon in * settings* while pressing the cmd key will make the dragging not work. 

I hope this feedback helps improve Ice. Thank you for your contributions to open-source.
