### ISSUE TITLE
[Bug]: Menu Bar Items are not visible immediately 

### ISSUE THREAD

**Issue by ccarpinteri** [jordanbaird/Ice#228]
### CHECK EXISTING AND FREQUENT ISSUES

- [X] I have searched existing issues, and this bug has not been reported

### Description

When opening the Settings for the first time after launching Ice, the Menu Bar Items are not visible immediately. At first the app reports "Unable to display menu bar items", though when you click in the window, they will appear, and appear each time settings is opened after that.

[See screen recording](https://jam.dev/c/e7827e83-5daf-4940-8928-d7111c4ecb4d).

### Steps to Reproduce

1. Start Ice
2. Open Settings
3. Navigate to Menu Bar Items

See "Unable to display menu bar items". Clicking in the window reveals the menu bar items
Expect to see menu bar items

### Ice Version

0.10.1

### macOS Version

14.5 (23F79)

### Screenshots

https://jam.dev/c/e7827e83-5daf-4940-8928-d7111c4ecb4d

**Comment by jordanbaird** [comment]
Thanks for the report. It should actually have been fixed in 715dcaaf9eefe694b3eafc05d718fdd782ad1bf5. I'll release a patch soon with the fix.
