### ISSUE TITLE
[Feature Request]: Option to also show Ice bar on hover of the Ice menubar icon, not just divider of the hidden area

### ISSUE THREAD

**Issue by e-kotov** [jordanbaird/Ice#237]
### Check Existing Issues

- [X] I have searched existing issues, and this issue is not a duplicate

### Description

Kindly consider adding an option to reveal the floating `Ice Bar` when hovering the menubar icon of `Ice`. Currently, hovering only works when pointing the mouse at a location where the last menubar icon is visible. Optionally showing the bar when hovering on the `Ice` menubar icon may be useful for users who prefer to have the `Ice` icon fixed towards the right of the screen, rather then keeping it as the last leftmost visible icon in the menubar.

### Screenshots

https://github.com/jordanbaird/Ice/assets/8681379/5b26408e-6cf5-4868-a0c5-79f158706728

**Comment by jordanbaird** [comment]
I'm not sure I see the use case for this. Show on hover is meant for users who would prefer not to interact with the Ice icon. If their mouse is already over the Ice icon, could they not just click to show instead?

Also, note that hovering actually works in any empty space in the menu bar, not just where the last visible item is. Knowing that may make it easier to use.

**Comment by e-kotov** [comment]
> note that hovering actually works in any empty space in the menu bar, not just where the last visible item is

Yep, noticed that today too. Quite handy!
