### ISSUE TITLE
Automatically rehide on "focused app" an multiple displays collide

### ISSUE THREAD

**Issue by riegaz** [jordanbaird/Ice#24]
This feature works but if you have two displays the menubar goes gray on the not active (focused) display.

The problem arises when selecting menu bar options on a display that is not currently active. The menu items briefly appear before disappearing, presumably due to a focus shift within macOS. Ice must address this to ensure the menu items remain visible.

**Comment by jordanbaird** [comment]
Is this still a problem in the latest release?

**Comment by riegaz** [comment]
It still does strange redrawings on the latest version when focusing other apps

https://jumpshare.com/s/omYxrU8k4evwCmM5t27W

**Comment by jordanbaird** [comment]
I'm noticing the "focused app" auto rehide is still behaving as you described. The strange redrawing is a separate issue I believe, and is a side effect of a workaround I had to do to get the Ice Bar working. I've opened #241 for that.
