### ISSUE TITLE
[Bug]: "Help" menu label not showing on left menu in Evernote with split menu on Mac Sonoma 14.5

### ISSUE THREAD

**Issue by albyh** [jordanbaird/Ice#250]
### Check Existing Issues

- [X] I have searched existing issues, and this issue is not a duplicate

### Description

When set to Menu Bar Shape = Split the "Help" menu label doesn't show in Evernote. It can be accessed by selecting the "Window" label and then right arrowing to the label. 

### Steps to Reproduce

Set Ice to "Split" menu bar shape
Open Evernote

### Ice Version

0.10.2

### macOS Version

14.5

### Screenshots

<img width="386" alt="image" src="https://github.com/user-attachments/assets/16a6f7b7-5775-42a1-84c1-1fbda035af8a">

**Comment by jordanbaird** [comment]
I believe this is a regression that has happened in the last couple of updates. I'll look into what may have caused it and see if I can get a fix out.
