### ISSUE TITLE
[Feature Request]: Replace some visible items to show selected ice bar item

### ISSUE THREAD

**Issue by KaBankz** [jordanbaird/Ice#258]
### Check Existing Issues

- [X] I have searched existing issues, and this issue is not a duplicate

### Description

For the most part when selecting an item from the ice bar it opens up fine, except for large items.

If the menubar does not have enough space to fit a large item from the ice bar, it does not activate.

I suggest that some of the currently visible items are temporarily hidden to make space for the selected hidden item to appear, kinda like what bartender does.

This sounds similar to https://github.com/jordanbaird/Ice/issues/240, but instead of swapping all hidden and visible items, we only want to swap specific ones only if there isn't enough space to display them.

### Screenshots

Example with the Stats app, It's too big to fit in the menubar, so clicking on it does nothing.

https://github.com/user-attachments/assets/a4f6aa27-d006-495b-913a-3ea221b51035

**Comment by jordanbaird** [comment]
The latest release, 0.10.3 has this.

**Comment by KaBankz** [comment]
I'm running 0.10.3

**Comment by jordanbaird** [comment]
Does your screen have a notch? If so, this is actually a bug that the fixes in 0.10.3 didn't account for. We have a new issue, #259 that is tracking this.

**Comment by KaBankz** [comment]
Yeah, I got a notch, didn't know it was a bug, but I'm glad someone reported it. I'll follow that issue for updates. Thanks.
