### ISSUE TITLE
[Bug]: On a MacBook with a notch, items on Ice Bar are unclickable if menu bar is full

### ISSUE THREAD

**Issue by okuramasafumi** [jordanbaird/Ice#259]
### Check Existing Issues

- [X] I have searched existing issues, and this issue is not a duplicate

### Description

The screenshot is in [this thread](https://github.com/jordanbaird/Ice/issues/236#issuecomment-2233880833)

As far as I understand, Ice puts items on Ice Bar to menu bar when they are clicked. This works when there are enough space on menu bar.
However, on a MacBook with a notch, that mechanism works only on the right side of a notch. That means, if the right side of a notch is full, Ice Bar items are not clickable. Unfortunately it's often the case.

### Steps to Reproduce

On a MacBook with a notch, put many items on menu bar such as WiFi status. Then configure Ice to have Ice Bar, put some items on it and click it.

### Ice Version

0.10.3

### macOS Version

Sonoma 14.5

**Comment by jordanbaird** [comment]
Thanks for opening this. I'll get to work on a fix as soon as possible.

**Comment by okuramasafumi** [comment]
I've confirmed this is fixed with the version 0.10.4, thank you!

**Comment by jordanbaird** [comment]
@gordon0907 Good to know. I'll reopen this.
