### ISSUE TITLE
[Feature Request]: full working when menu bars are hidden in OS.

### ISSUE THREAD

**Issue by applebait** [jordanbaird/Ice#262]
### Check Existing Issues

- [X] I have searched existing issues, and this issue is not a duplicate

### Description

I don't think it's necessary.
I work with the macOS' Menubar hidden. I also have a MacBook Pro with the Top Notch and I also work, when at home, with a second Display.

**Comment by jordanbaird** [comment]
I'm not sure why you don't think it's necessary, even when Ice says it can't do it (it says that for a reason). Either way, this is tracked in #201. Closing as a duplicate.
