### ISSUE TITLE
Option to make menubar taller on Macs without the notch

### ISSUE THREAD

**Issue by TheMaster5209** [jordanbaird/Ice#264]
### Check Existing Issues

- [X] I have searched existing issues, and this issue is not a duplicate

### Description

Found the app today, seems great so far. 

If possible, I'd love to see an option to make the menubar taller so that it matches how it looks on the newer notched MacBooks. I am on an M1 Air and it is annoying how short the menubar is with no padding between the text and the top/bottom edges of the menubar. 

Hopefully this is something that is feasible and is added soon. Best of luck to the developer for the future of the app

**Comment by jordanbaird** [comment]
This is sadly not possible, as far as I am aware. There may be a private API that can do this, but those are hard to discover in modern macOS.
