### ISSUE TITLE
1Password menu bar item always moves against the will to the Always-Hidden section after restarting Mac

### ISSUE THREAD

**Issue by Serdna379** [jordanbaird/Ice#266]
### Check Existing Issues

- [X] I have searched existing issues, and this issue is not a duplicate

### Description

1Password menu bar item appears in Always-Hidden section. When I move it to Hidden section or to Visible section, it stays there only until I restart Mac. After the restarting the Mac, the 1Password menu item is again moved to the Always-Hidden section, although it should stay in the section where I have moved it before, as the other menu items have.
No such problems appear with other apps.

### Steps to Reproduce

1. Move 1Password menu item from the Always-Hidden section to the Visible section.
2. restart macOS, the 1Password menu item appears again in the Always-Hidden section.

### Ice Version

0.10.3

### macOS Version

Sonoma 14.5 (23F79)

### Screenshots

1. ![Clicked on the Show Hidden section](https://github.com/user-attachments/assets/8adaea51-3ca1-4b1c-99a3-8da7063ecd39)
2. ![Clicked on the Show Always-Hidden section](https://github.com/user-attachments/assets/787d00b0-96fa-404a-b083-23bca1cc8dcd)
3. ![Moved 1Password menu item to the Hidden section](https://github.com/user-attachments/assets/47826f06-0d74-4b96-b14c-f6d8d124b642)
4. ![After restarting Mac 1Password menu bar item moves again the the Always-Hidden section](https://github.com/user-attachments/assets/69c3762d-bb7f-431b-a114-5359c9b55e21)

**Comment by jordanbaird** [comment]
This isn't a bug with Ice. It's a side effect of the way macOS treats newly added menu bar items. It places them at the far left of the menu bar, which is where the always-hidden section is. Most apps save the positions of their items, but some apps, like 1Password do not. This causes them to be treated as new items each time their app launches. Once #6 and #26 are implemented, Ice will be able to remember the location of each item and move it back to the correct position. Closing as this is tracked there.
