### ISSUE TITLE
[Bug]: Disappearing icons

### ISSUE THREAD

**Issue by mortenscheel** [jordanbaird/Ice#268]
### Check Existing Issues

- [X] I have searched existing issues, and this issue is not a duplicate

### Description

I'm experiencing a bug that's hard to explain exactly. I'll explain the general "gist", and include a couple of concrete examples.
I'd be happy to help trying to narrow it down.

### General
Sometimes app icons that *should* be visible, are missing.
These missing icons can *sometimes* be found by selecting "Show the always-hidden section" and moving them back into place.
If they aren't in the always-hidden section either, the only solution is to quit Ice.
It's not a consistent bug. Sometimes everything works as it should.
It doesn't seem to be related to apps being updated to newer versions.

### Specific apps
This bug affects two apps especially (that I've noticed):

**OrbStack**
This seems to be the most problematic app by far. It doesn't stay where I place it (in the visible section) for more than a couple of days.

**iTerm2**
When using these settings, the iTerm icon is removed from the Dock and Cmd+Tab switcher, *and* an icon is added to the menu bar, where you can access the items that would otherwise be available in the app menu.
It's a pretty niche setup, but it would be nice if it could work with Ice.
<img width="786" alt="image" src="https://github.com/user-attachments/assets/12ae7a37-6ef2-4d4f-bc2a-924b3df99e2f">

**Microsoft Outlook**
I don't care about this one, but it's one of the apps that usually appear in the always-hidden section when I go looking for either OrbStack or iTerm2

### Steps to Reproduce

Like I said, it's not easy to reproduce. Sometimes a restart fixes things, but usually it doesn't.

I don't know if it's relevant, but I used Bartender before. It's uninstalled now, but I don't know if it could have any side effects, even after uninstalling it.

### Ice Version

0.10.2

### macOS Version

Sonoma 14.5

**Comment by jordanbaird** [comment]
This isn't a bug with Ice. It's a side effect of the way macOS treats newly added menu bar items. It places them at the far left of the menu bar, which is where the always-hidden section is. Most apps save the positions of their items, but some apps don't. This causes them to be treated as new items each time their app launches (which includes a system restart). Once #6 and #26 are implemented, Ice will be able to remember the location of each item and move them back to the correct order.

As for quitting Ice causing the items to reappear, I'm skeptical on this. Ice does not and cannot remove items, so there must be something else with your system that is interfering with these items being displayed.

I'm going to close this, as it isn't a bug with Ice, and the behavior will be fixed once the linked issues are implemented.
