### ISSUE TITLE
[Bug]: XXX is unresponsive (yellow exclamation) until Ice is quit and relaunched

### ISSUE THREAD

**Issue by luckman212** [jordanbaird/Ice#269]
### Check Existing Issues

- [X] I have searched existing issues, and this issue is not a duplicate

### Description

I recently updated Syncthing on my Mac, whose icon I had previously put in the "Always Hidden" section. After relaunching it, the menubar icon appeared at the left of the menubar (not the Ice bar) and when I tried to open the Ice settings to move it, I saw a yellow ⚠️ symbol and the message:

> _Item is not movable. Syncthing is unresponsive. Until it is restarted, it cannot be moved. Movement of other items may also be affected until this is resolved._

Quitting Ice and relaunching it allowed me to move it back to the Hidden Ice Bar.

### Steps to Reproduce

? unsure

### Ice Version

0.10.3

### macOS Version

14.5

### Screenshots

![image](https://github.com/user-attachments/assets/68601c3f-c2b3-4f97-a40a-7c5b43aeb935)

**Comment by luckman212** [comment]
Forgot to mention that:

- This has happened before, with other apps (Syncthing was just an example in this case)
- Syncthing was not crashed at this time, and its icon was movable and draggable using normal macOS command-drag

**Comment by jordanbaird** [comment]
I believe we're using the same API as Activity Monitor to check for responsiveness. So it's weird that it would give a false positive. I'm thinking it has to have been unresponsive at some point, and maybe Ice just hasn't updated its state to reflect the fact that it is now responsive? I'll look into it.

**Comment by luckman212** [comment]
This may be important:

I was compiling a custom build of Syncthing from source. So the steps I took were:

1. Quit Syncthing
2. Compile new build (app's code signature changed because I sign with my own Developer ID)
3. Replaced old version of Syncthing app with new build in /Applications
4. Launch new build
5. Menubar icon appeared to the left of Ice's "chevron" (previously it was supposed to be in the Always Hidden section)
6. I opened Ice's preferences to try to put it back in Hidden, that's when I saw the exclamation and error message above.
7. Quitting and relaunching Ice cleared the issue...

Thanks @jordanbaird

**Comment by luckman212** [comment]
After restarting my Mac, this happened again, so it actually does seem to be somehow specific to Syncthing or perhaps the fact that this build is not notarized?

![screenshot_G0J58rMo](https://github.com/user-attachments/assets/c717e40b-4bba-43b1-90f0-d81eb77e9ecb)

**Comment by dblinnikov** [comment]
It's not tied to your specific app. I have exactly the same issue with BetterTouchTool app if i do "Restart BTT" option.
<img width="248" alt="image" src="https://github.com/user-attachments/assets/b141a035-6911-4f1e-a885-0d896534bff7">

**Comment by s235784** [comment]
The steps I found to reproduce the problem are:

1. Click the icon in the separate bar, and it will appear in the menu bar.
2. Quit the app.
3. Relaunch the app.

Now the icon is shown in the menu bar and will not be hidden. Currently, the only way to resolve this is to relaunch ice and drag the app back into the hidden section.

**Comment by jordanbaird** [comment]
@s235784 This isn't the same issue. This issue is specifically about the yellow unresponsive image and alert. What you're describing is due to the fact that Ice doesn't actually control the order of items. Showing items using the Ice Bar is a special case, where it remembers the item's original location and returns it after a certain amount of time, but if you quit the app while it's shown, it cancels that operation, so you need to manually move it back. Ice will eventually get profiles, which will resolve this, as every item will always be remembered.

**Comment by s235784** [comment]
Thanks, @jordanbaird. It's my fault for not describing the steps carefully. Open the ice settings instead of relaunching it, and you'll see the yellow unresponsive icon and alert.
