### ISSUE TITLE
[Bug]: 'Always-hidden section can be toggled' setting isn't honored

### ISSUE THREAD

**Issue by KenGoBlue** [jordanbaird/Ice#271]
### Check Existing Issues

- [X] I have searched existing issues, and this issue is not a duplicate

### Description

When the 'Always-hidden section can be toggled' setting is turned on, option ⌥ + click one of Ice's menu bar items, or inside an empty area of the menu bar, does not toggle the section.

### Steps to Reproduce

1. In Ice settings, go to the Menu Bar Items tab and confirm that there are items present in the Always-Hidden section.
2. In Ice settings, go to the Advanced tab and confirm that the "Enable the always-hidden section" and "Always-hidden section can be toggled" settings are enabled.
3. In the menu bar, confirm that the items in the Always-Hidden section are not visible.
4. ⌥ + click in an empty area of the menu bar.
5. Note that items in the Always-Hidden section still are not visible.

### Ice Version

0.10.3

### macOS Version

14.5 (23F79)

**Comment by jordanbaird** [comment]
I'm unable to reproduce this. Here's the behavior I get when following your steps:

https://github.com/user-attachments/assets/31df52f6-d7b2-4f90-88cf-b22b0448a84d

**Comment by KenGoBlue** [comment]
Ugh — must be a conflict on my end, I guess. I can do some digging later, but I'm afraid I'm going to have to do a restart before then (for unrelated reasons).

**Comment by jordanbaird** [comment]
Just tried it with both of those settings disabled. Still getting the same behavior. Do you use multiple monitors? If so, does it work on any single monitor, or with all external monitors disconnected if you use a MacBook?

**Comment by KenGoBlue** [comment]
Interesting — I usually do use multiple monitors, but not today. 

Since my last comment, tho', I've had to perform my work-related restart and that seems to have resolved the issue. I'm going to close this bug, and I'll open a new one (linking to this) if it comes back again anytime soon. I'll document my monitor situation, etc., in the bug if that happens.
