### ISSUE TITLE
[Bug]: Ice Bar doesn't open on MacOS 15

### ISSUE THREAD

**Issue by Xytronix** [jordanbaird/Ice#274]
### Check Existing Issues

- [X] I have searched existing issues, and this issue is not a duplicate

### Description

Apparently, Ice Bar doesn't work under some circumstances.
The menu bar layout doesn't show up as well.

This is linked together with the mouse being shown under any application in macOS 15 until you move it to the dock or menu bar. 

### Steps to Reproduce

1. Click o Ice Bar
2. Ice Bar not showing up
3. Under Ice settings see expected results in screenshot
4. Under settings see expected results

### Ice Version

0.10.3

### macOS Version

15

### Screenshots

<img width="936" alt="Bildschirmfoto 2024-07-27 um 17 07 05" src="https://github.com/user-attachments/assets/6433fb3c-066a-4ede-a753-331ac24e6d00">

**Comment by jordanbaird** [comment]
I'm not sure this is a macOS 15 issue. It works just fine for me on the latest developer beta. I think this is related to a known issue where sometimes screen capture seems to break on a specific space (desktop). This can happen even if you only use one space. What happens when you try switching spaces or restarting your computer?

**Comment by leowill01** [comment]
I'm having this issue too. tried restarting and making a different space. activity monitor says the app is running, but i cant pull up the main settings panel and floating expanded menu bar wont show, so only indication its running is in activity monitor.

env:
- M2 Macbook Air 13in
- macOS Sequoia 15.0 (24A335) (latest public beta)
- Ice v0.10.5 via homebrew

**Comment by jordanbaird** [comment]
@leowill01 This is a different issue that should be resolved in the next release.

**Comment by jordanbaird** [comment]
@Xytronix Still can't get this to reproduce on the official macOS 15 release. I'm going to close this as an edge case, unless you have more information.
