### ISSUE TITLE
[Feature Request]: Ability to add custom icons - for both light and dark mode

### ISSUE THREAD

**Issue by dhruvikn** [jordanbaird/Ice#275]
### Check Existing Issues

- [X] I have searched existing issues, and this issue is not a duplicate

### Description

If we select an icon from the predefined list of icons in the settings, they change their fill as per the light and dark mode.
However, if I add a custom icon, I can only add one image which is shown in both light and dark mode.
In the attached screenshot, I used the [arrow down](https://remixicon.com/icon/arrow-down-s-line) icon (SVG) from remix icons and it looked great, however, as soon the menu bar's background changed to dark it was hard to spot.

If we cannot invert the icon automatically when the mode changes, I think it would be great if we could allow the user to upload two icons - one for light and one for dark mode.

Have attached a screenshot for reference. Thank you!

### Screenshots

![CleanShot 2024-07-28 at 16 57 05@2x](https://github.com/user-attachments/assets/2446d2ab-df9a-4161-a6de-115ce335f5f5)

**Comment by jordanbaird** [comment]
Thanks for the detailed feature request! You can invert the icon automatically by selecting the "Use template image" setting that appears when you use a custom icon. Will that work for your use case?

**Comment by dhruvikn** [comment]
Woah lol, I'm embarrassed about how I missed that. Yes, that's exactly what I wanted. Thanks for the swift response! Love the toggle's description!

However, maybe we could rename the toggle's label from "Use template image" to something better. It's not very user-friendly. Some ideas - 
1. Toggle icon color automatically
2. Use monochrome icon
3. Apply system theme to icon
4. Match icon to system appearance

**Comment by jordanbaird** [comment]
Totally agree about renaming the label. I'm going through the entire UI right now and rewording a bunch of things, so I can make the change if you want, or if you want to be listed as a contributor, I'll accept a pull request. I like numbers 2 and 3 from your suggestions the most.

**Comment by dhruvikn** [comment]
I'll make the change and raise a PR with number 3. Thanks. Will share here once done.

**Comment by dhruvikn** [comment]
Have a raised a PR here - https://github.com/jordanbaird/Ice/pull/277

Please let me know if you need anything else!

**Comment by jordanbaird** [comment]
Not entirely sure how this works with merging a PR into a branch that isn't `main`, but I believe you should be listed as a contributor once the `0.11.0` branch is merged.

**Comment by dhruvikn** [comment]
Thank you @jordanbaird 🚀
