### ISSUE TITLE
App doesn't show all the icons when another app is in focus.

### ISSUE THREAD

**Issue by maxoliinyk** [jordanbaird/Ice#28]
When editing settings in Ice.app it's gonna be in focus, that means that menubar actions are exclusive to it. In this case, every icon shows as expected.

<img width="1440" alt="image" src="https://github.com/jordanbaird/Ice/assets/68681586/8f8c88e6-4ade-4cf6-afdb-d1463ed23c37">

Though, when you use another application, its menubar overlaps icons in Ice.app and some icons are hidden, and there's no way to access them. 

<img width="1440" alt="image" src="https://github.com/jordanbaird/Ice/assets/68681586/c7b5b9fa-8f16-490e-b612-2c479b20cb68">

In my opinion, it's a bug, and should be fixed. For example, Hidden cleans all menubar when you open it.

**Comment by jordanbaird** [comment]
There's a setting to enable this: "Hide application menus when showing menu bar items". It's at the bottom of the "General" settings pane in 0.6.3.

Also, the next release, 0.7.0, is going to greatly improve this feature by only hiding the application menus when they overlap with the menu bar items.

**Comment by maxoliinyk** [comment]
I enabled that setting in previous update, and it worked well. Now I've updated to 0.7.0, and it stopped working.

**Comment by jordanbaird** [comment]
With the changes in 0.7.0, it doesn't hide the application menus every time -- only when the application menu is long enough to prevent menu bar icons from showing. Have you tried it with an app with a long menu to see if it still doesn't work?

**Comment by maxoliinyk** [comment]
I've already deleted my reply because it started working again. When the issue appeared, the menu bar was long enough to hide some of my icons.

I found out that this issue doesn't work as intended when we have "Currently Sharing" icon

<img width="1430" alt="3884" src="https://github.com/jordanbaird/Ice/assets/68681586/8fa05399-6a29-40d9-9664-52e2bcae23cd">

And works great without it. Should I fill a separate bug report?

<img width="1440" alt="36425" src="https://github.com/jordanbaird/Ice/assets/68681586/ff9ac419-4f0a-440c-abec-0f5aa7779aa2">

**Comment by jordanbaird** [comment]
Interesting. Yes, if you could open a separate issue for this, that would be great.
