### ISSUE TITLE
[Feature Request]: Configure height of menubar

### ISSUE THREAD

**Issue by mintyleaf** [jordanbaird/Ice#284]
### Check Existing Issues

- [X] I have searched existing issues, and this issue is not a duplicate

### Description

Hey!
Can menubar height (or vertical margin) configuration be implemented?
The thing is when using laptop screen with notch i get a really nice and thick menubar with beautiful above and under text spacing
But on clamshell mode with 4k monitor (without any notch, apparently) the menubar is too small for my taste and oh my god that driving me crazy
I don't want to use any custom menubars, since i really like that stock macos bar
And since there are some customizations related to it's shape, like, rounded corners and split out - it will be really nice to "unstick" it from the top when pilled, e.t.c.

**Comment by jordanbaird** [comment]
This is something I wish were possible, but unfortunately it isn't. The only thing Ice can do is overlay a shape and tint on top of the existing menu bar, but it can't move or resize it. It can be "unstuck" from the top on notched screens because of the extra size. But that's about it.
