### ISSUE TITLE
[Feature Request]: Update Notes

### ISSUE THREAD

**Issue by DerekLangley** [jordanbaird/Ice#285]
### Check Existing Issues

- [X] I have searched existing issues, and this issue is not a duplicate

### Description

Would it be possible to include update notes in the new version update prompt? I am always curious to see what has changed before updating, and a text box with a summary of changes and/or a link to the Github release page would be very helpful.

Thanks!

**Comment by philCryoport** [comment]
Apparently somebody had the same idea as me with the 0.10.4 release dialog.

**Comment by kg4zow** [comment]
I normally don't do the "me too" thing, but ... I came here to open what sounds like the same exact issue.

I wish the "upgrade is available" dialog had a link/button/etc. which shows me the new version's release notes, before I decide whether I want to upgrade *now* instead of waiting until later.

**Comment by jordanbaird** [comment]
I agree, this would definitely be a good thing to start including. I'll try to make the change before the next release. Not entirely sure what it will entail, though, as we use the third-party framework [Sparkle](https://github.com/sparkle-project/Sparkle) for updates.

**Comment by jordanbaird** [comment]
The latest update (0.10.5) has release notes in the app, but something went wrong with the formatting. I don't think I can change it after the release goes live, so the next one will hopefully be better.
