### ISSUE TITLE
[Feature Request]: Remove 1px padding around menu bar when using any menu bar shape

### ISSUE THREAD

**Issue by billyjacoby** [jordanbaird/Ice#288]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

When using either the full or split menu bar shape there's a tiny vertical space between the menu bar and the top of the screen. This happens on both built in screens and external displays, but it is much more noticeable on higher resolution external displays.

### Steps to Reproduce

Set the menu bar shape to either split or full in Menu Bar Appearance and notice the gap above the menu bar.

### Ice Version

0.10.4

### macOS Version

15.1

### Screenshots

<img width="418" alt="Screenshot 2024-08-02 at 7 05 33 AM" src="https://github.com/user-attachments/assets/e69a2e8a-d3a4-4e50-b2fc-29aa6e0d5869">

**Comment by jordanbaird** [comment]
This is actually an intentional design choice to match up with Bartender's styling feature (so that people switching can get the same look). But I do agree it looks a little odd. I'll leave this open for a while to get other peoples' input. In a month or so, if no one has said anything, I'll go ahead and make the change.

**Comment by maparaschivei** [comment]
I actually find the top padding/margin pleasing to the eye.

Any way to simply make it a toggle in the settings instead of removing it entirely?

**Comment by jordanbaird** [comment]
@maparaschivei When you say padding, are you talking about the single pixel or the setting to inset the shape when using a screen with a notch? Because that setting will stay.

**Comment by maparaschivei** [comment]
@jordanbaird The single pixel padding.

On my 4K monitor it allows the wallpaper to peek through the top which gives the menu bar an effect as though it is floating (it's not anchored to anything). Particularly with the split menu bar and rounded corners.

In my opinion, it looks very nice with certain wallpapers. Thanks.

<img width="559" alt="Screenshot 2024-08-10 at 10 16 25" src="https://github.com/user-attachments/assets/b7ad3a4f-f8a7-42f0-b430-76d2ee890ff8">

**Comment by jordanbaird** [comment]
I went ahead and made the change. By default, there is no longer a 1px padding around menu bar shapes. You can get an option to revert back to the old look by checking "Show advanced appearance settings" in the Advanced settings pane.

**Comment by jordanbaird** [comment]
After installing the latest update on my personal MacBook, I'm realizing that on screens without the notch, it looks very weird to _not_ have the 1px padding. The top of the menu bar shape is cut off. I'm going to release a hot fix soon with a compromise that only removes the padding on screens with the notch.
