### ISSUE TITLE
[Bug]: Ice ignores Doll menu item position preferences

### ISSUE THREAD

**Issue by targumanu** [jordanbaird/Ice#292]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Ice fails to remember the preferred positions of the menu bar items created on the fly by [Doll](https://github.com/xiaogdgenuine/Doll).

### Steps to Reproduce

1. Set up [Doll](https://github.com/xiaogdgenuine/Doll) to monitor an app (e.g., Messages) for notification badges.
2. Wait until the Messages app shows a new notification badge.
3. Doll will create a new Messages icon in the menu bar.
4. Go to the Ice settings and move the Messages icon from the Hidden section to the Visible section.
5. Open the chat with the new message(s) in the Messages app so that the menu bar item created by Doll disappears.
6. Wait again until the Messages app shows a new notification badge and Doll creates a new menu bar item for it.
7. Ice will consider the newly created Messages icon a completely new menu bar item and will automatically move it to the Hidden section again.

### Ice Version

0.10.4

### macOS Version

14.4.1

**Comment by jordanbaird** [comment]
This isn't a bug with Ice, but rather a missing feature. Ice doesn't currently manage the individual locations of items. It only hides or shows them. Once #26 is implemented, this will be resolved. Closing, as this is tracked there.
