### ISSUE TITLE
[Feature Request]: be able to press buttons from "menu bar items" window in the settings

### ISSUE THREAD

**Issue by yonatankremer** [jordanbaird/Ice#293]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

no idea if possible, but would be neat

**Comment by jordanbaird** [comment]
The only way to do this would be to show the real item in the menu bar and forward the click to it (basically the same as what the Ice Bar does). While it would be easy to implement, I don't think it would be very straightforward as a feature, so there are no plans for this at the moment.
