### ISSUE TITLE
[Feature Request]: App Recommendations for Menu Bar Enjoyers (©)

### ISSUE THREAD

**Issue by nskazki** [jordanbaird/Ice#295]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

However unorthodox, this may be the best place for the menu bar enjoyers (©) to come together and share app recommendations. I'll begin:

1. https://github.com/p0deje/Maccy - A clipboard history manager. Faster than coming back to a tab and copying again.
2. https://github.com/amebalabs/TRex - An OCR tool. Quicker than asking to share what you see on a shared screen.
3. https://github.com/sindresorhus/System-Color-Picker - A color picker. There are many, but this one is mine.
4. https://github.com/swiftbar/SwiftBar - A script runner. This + AppleScript = Endless Possibilities.

**Comment by nskazki** [comment]
Also, if anybody could recommend an app pinning half-transparent image references over all other windows, it would be greatly appreciated. The [pixelparallel-by-htmlburg](https://chromewebstore.google.com/detail/pixelparallel-by-htmlburg/iffnoibnepbcloaaagchjonfplimpkob) Chrome extension is great, but a native app would be even better.

**Comment by jordanbaird** [comment]
An issue tracker isn't the place for this. I went ahead and created a new repository, [awesome-menubar](https://github.com/jordanbaird/awesome-menubar) for this purpose. You can submit a pull request to include your recommendations there.
