### ISSUE TITLE
[Bug?]: On Sequoia the app triggers a security popup every day, at least once.

### ISSUE THREAD

**Issue by ryanbooker** [jordanbaird/Ice#296]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

The new security model in ~Windows Vista~ macOS Sequoia triggers an "OMG your screen is being watched" pop up every day. 

I'm not sure if this is something you can improve the experience of with capability settings or signing or something, but FYI, as it's really very annoying. 

### Steps to Reproduce

Install the app and wait.

### Ice Version

0.10.4

### macOS Version

15.x

### Screenshots

<img width="260" alt="Screenshot 2024-08-05 at 08 47 07" src="https://github.com/user-attachments/assets/05d20837-becf-48db-9c50-483a2a16065b">

**Comment by jordanbaird** [comment]
Duplicate of #170
