### ISSUE TITLE
[Bug]: Timery Menu Bar Item Keeps Resetting

### ISSUE THREAD

**Issue by mergesort** [jordanbaird/Ice#297]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Thanks a lot for the app @jordanbaird, I absolutely love it!

This only seems to happen to one app, but every time I reboot the app [Timery](https://apps.apple.com/us/app/timery-for-toggl/id1425368544) moves from the Visible to Always-Hidden section. No matter how many times I've moved it to Visible, the app continues to move back.

The only difference between Timery and other apps on my computer is that Timery is a Mac Catalyst app. I don't know if that could cause trouble, but otherwise I'm out of ideas. 😅

### Steps to Reproduce

1. Launch my computer
2. Move Timery from Always-Hidden to Visible
3. Reboot
4. See that Timery is once again Always-Hidden

### Ice Version

0.10.3

### macOS Version

14.5

### Screenshots

![Ice Menu Bar](https://github.com/user-attachments/assets/b476e827-9df3-4611-922d-19583b4ccc31)

**Comment by jordanbaird** [comment]
This isn't a bug with Ice. It's a side effect of the way macOS treats newly added menu bar items. It places them at the far left of the menu bar, which is where the always-hidden section is. Most apps save the positions of their items, but some apps don't. This causes them to be treated as new items each time their app launches. Once #26 is implemented, Ice will be able to remember the location of each item and move them back to the correct order. Closing as this is tracked there.
