### ISSUE TITLE
[Feature Request] Use modifier key + click on empty area to show "always hidden" section 

### ISSUE THREAD

**Issue by maxoliinyk** [jordanbaird/Ice#30]
We currently have a feature that allows to use modifier key (option in my case) + click on Ice icon to show "always hidden" section. Also, we can click or just hover the empty area to show this section. 

In my opinion, it would be great to have a feature that allows to show "always hidden" section with modifier key + click on empty area.

**Comment by maxoliinyk** [comment]
That was fast. Thanks!

**Comment by jordanbaird** [comment]
No problem!
