### ISSUE TITLE
[Feature Request]: Adjust spacing between menu bar items

### ISSUE THREAD

**Issue by philocalyst** [jordanbaird/Ice#304]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Adjust the spacing between items in the menu bar, as is done both on the command line and through apps such as: https://sindresorhus.com/menu-bar-spacing

**Comment by stonerl** [comment]
This is already part of the [0.11.0](https://github.com/jordanbaird/Ice/tree/0.11.0) branch.

![CleanShot 2024-08-07 at 22 18 13@2x](https://github.com/user-attachments/assets/32cb19cd-6c22-42b1-9354-a32467dd982d)

**Comment by philocalyst** [comment]
Oh! Sorry for asking a redundant question then. I just searched the open issues, where should I look next time so I don't make a similar mistake?

**Comment by jordanbaird** [comment]
@philocalyst You can remove the `is:open` filter from the search field to search both open and closed issues.
