### ISSUE TITLE
[Bug]: 1Password keeps getting moved to always hidden after restarting it

### ISSUE THREAD

**Issue by krisbreuker** [jordanbaird/Ice#307]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

I don't know if this is a bug specifically with 1Password, but for me it's the only application where this happens. I have put the 1Password menu icon into the hidden section. If I quit and restart 1Password, it shows up in the always-hidden section and I have to move it back to the hidden section.

### Steps to Reproduce

1. Make sure 1Password is shown in the menu bar
2. Move the icon to the 'Visible' or 'Hidden' section
3. Quit 1Password from the menu bar icon (fully quit, not just close)
4. Reopen 1Password
5. The icon is now placed in the 'Always-Visible' section

### Ice Version

0.10.4

### macOS Version

14.6.1

**Comment by jordanbaird** [comment]
There have already been lots of duplicate reports of this. See #298 for why this isn't a bug. Please check the closed issues when making a report.

**Comment by krisbreuker** [comment]
My bad, sorry for the duplicate and not checking the closed issues...

**Comment by jordanbaird** [comment]
No worries.
