### ISSUE TITLE
Multi-monitor support

### ISSUE THREAD

**Issue by fastnlight0** [jordanbaird/Ice#31]
Currently, if I style my menu bar (eg. split, round edges), the bar appears like that on my main display. However, on my secondary display, my menu bar appears normal. Can multi-monitor support be added?

Screenshots:

Bar on main display:
![Screenshot 2024-03-18 at 9 10 13 PM](https://github.com/jordanbaird/Ice/assets/77035115/9fc8dc74-afb1-4677-81a1-c8220da91e38)

Bar on secondary display:
<img width="1440" alt="Screenshot 2024-03-18 at 9 10 38 PM" src="https://github.com/jordanbaird/Ice/assets/77035115/6de97b35-8d52-4119-aba4-3ce5171d69e3">

**Comment by jordanbaird** [comment]
This is strange. It's supposed to appear on all displays. Give me some time to assess the issue, and I'll see what I can do.

**Comment by jordanbaird** [comment]
Just curious, does it work after updating to 0.8.0? I made several general changes to the way things behave, so there's a chance one of those fixed the problem.

**Comment by fastnlight0** [comment]
I'm not currently at home, but I'll let you know when I do.

**Comment by fastnlight0** [comment]
It works!
