### ISSUE TITLE
[Bug]: Invisible large items in menu bar cause it to overflow and become scrollable

### ISSUE THREAD

**Issue by DrBones** [jordanbaird/Ice#313]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

There are invisble (but really large) menu bar items that cause the menu bar to overflow and become scrollabe.

### Steps to Reproduce

I unfortunatelay have no way to reproduce this. This just suddenly happend and now I can't get rid of it. I removed Ice and reinstalled but the settings persisted. I am now looking for the config files

### Ice Version

0.10.4

### macOS Version

14.5 (23F79)

### Screenshots

See video of Ice "Menu Bar Items" Settings view

https://github.com/user-attachments/assets/6e944615-05b7-48f3-9068-b0ed789249cf

**Comment by DrBones** [comment]
Removing Ice and deleting `Library/Preferences/com.jordanbaird.Ice.plist` does reset the App but does not clear the large invisble icons. Maybe they stem from the two monitors I have attached?

**Comment by jordanbaird** [comment]
Do you have an action configured in BetterTouchTool to hide menu bar items? Or do you use some other app that might be hiding them? Some I can think of offhand are:

* Bartender
* Hidden Bar
* Dozer
* iBar
* Barbee
* OnlySwitch

The way these apps (Ice included) hide menu bar items is to make a really long item that pushes other items off screen. Ice's current policy is to just display whatever items are in the menu bar (aside from its own really long items, of course). We _could_ check the length of each item and try to determine which ones to display based on that.

You _should_ get a tooltip that shows the name of the app when you hover over an item in Ice's interface. That might help you narrow down which app is causing this.

**Comment by DrBones** [comment]
Yes! I have BetterTouchTool installed and also an Apple Script attached to a Double Click on the Menubar that was supposed to hide the menu bar items. I was apparently too impatient to let the cursor rest for a second, the popover clearly shows BetterTouchTool. Unfortunately, after I logged out and back in I now have three BetterTouchTool icons 😅.

I am going to look through BTT to see if there is something else enabled in that regard but I currently cant find anything. However, it currently works for me, since knowing that is an icon lets me move it to the far left and now it looks like it should

An Aisde: I would never have guessed that there is a large invisible icon if not for some reason my "Show Scroll Bars" Setting would revert to "Always" occasionally.

![Screenshot 2024-08-13 at 14 03 19@2x](https://github.com/user-attachments/assets/7d568b74-6ce4-44d4-a018-2e25c7fc0321)

I think this can be closed, since this is more of an BTT/compatibility issue. Thank you for your help and the awesome open source Bartender alternative!
