### ISSUE TITLE
[Bug]: Menu item is always in 'Always Hidden' after restart

### ISSUE THREAD

**Issue by KenGoBlue** [jordanbaird/Ice#314]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

After every restart I have to visit the Menu Bar Items tab in Ice Preferences to move 1Password's menu bar item out of Ice's "Always Hidden" section and into "Visible" — after the next restart, Ice will always move it back to "Always Hidden."

### Steps to Reproduce

1. Move 1Password menu bar item to the "Visible" section in the Menu Bar Items tab in Ice Preferences to make it always visible
2. Restart and log in (doesn't matter whether immediately or hours/days later)
3. 1Password menu bar item is missing from the menu bar
4. Visit the Menu Bar Items tab in Ice Preferences
5. See 1Password listed in the "Always Hidden" section again.

### Ice Version

0.10.3

### macOS Version

14.6.1 (23G93)

**Comment by jordanbaird** [comment]
This isn't a bug with Ice, but rather a side effect of a behavior of macOS. See #298 for more details, as well as the plan to address it.

**Comment by KenGoBlue** [comment]
Sounds good! (Sorry, not sure how my bug search missed those.)
