### ISSUE TITLE
[Bug]: When program restart, The program icon will break away from Ice.

### ISSUE THREAD

**Issue by cevin** [jordanbaird/Ice#315]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

When a program restart (full quit and start it again), The icon will have problem in ice settings panel.

like: JetBrain Tools

### Steps to Reproduce

1. Start `JetBrain Tools`
2. Full Quit `JetBrain Tools`
3. Start `JetBrain Tools` again

### Ice Version

0.10.4

### macOS Version

14.6.1

### Screenshots

![image](https://github.com/user-attachments/assets/3e8c00ed-325e-4bfa-a0df-18a9230af443)

**Comment by jordanbaird** [comment]
This is fixed on `main` and will be in the next release.
