### ISSUE TITLE
[Bug]: "Always Visible" application moves to "Always Hidden" unexpectedly.

### ISSUE THREAD

**Issue by oak86** [jordanbaird/Ice#320]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

I have an application called NepTunes. It shows the track I'm listening to in the menu bar. When a song ends and no other song comes next, the application is moved from "Visible" to "Always-Hidden."

### Steps to Reproduce

1. Start NepTunes and Ice
2. Move NepTunes to "Visible"
3. Play a single song in Apple Music or Spotify.

### Ice Version

0.10.4

### macOS Version

14.5 (23F79)

**Comment by jordanbaird** [comment]
This isn't a bug with Ice, but rather a side effect of a behavior of macOS. See #298 for more details, as well as the plan to address it.
