### ISSUE TITLE
[Bug]: Many Alfred Icons

### ISSUE THREAD

**Issue by SteveMattan** [jordanbaird/Ice#322]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

One of my icons was not showing in Ice so I went to look at the "Menu Bar Items" in settings. And I discovered that there were multiple top hat icons for Alfred, as can be seen in the attached screen shot. Actually, there were more than shown in the screen shot, and there was the actual active working Alfred icon. I have no idea what the steps were to cause this to occur.

I invoked the Hidden bar and clicked on one of the 'bad' Alfred icons, and Ice promptly crashed. macOS presented the crash report and I clicked ok to reopen and things returned to normal.

### Steps to Reproduce

Alas, I do not know.

### Ice Version

0.10.4

### macOS Version

14.6.1

### Screenshots

![Screenshot 2024-08-16 at 3 02 29 PM](https://github.com/user-attachments/assets/5648c625-9608-4459-970a-0df9dce1543c)

**Comment by jordanbaird** [comment]
I think this was likely fixed in the latest release (0.10.5). I'll close this for now, but let me know if the issue still persists, and I'll reopen it.

**Comment by SteveMattan** [comment]
Will do. Thank you.
