### ISSUE TITLE
[Feature Request]: Multi-language support

### ISSUE THREAD

**Issue by luotn** [jordanbaird/Ice#324]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

First of all thank you very much for developing this alwsome software!
As a multi-language speaker. I am able to use Ice without any problem. I want to let more people know and use Ice without any roadblocks. Therefore, I believe adding multi-language support is the right thing to do.
I would love to contribute by translating en-us to zh-cn.

**Comment by jordanbaird** [comment]
Thanks for being willing to contribute! At this point, the interface changes so much from one release to the next that it would be very difficult to keep up with all the different translations, so I plan on localizing once the interface is more finalized. We have a discussion (#160) set up for that. If you'd like to comment there, you'll receive updates when we're ready to start. Someone has already volunteered for Chinese, but maybe you could work together on different areas of the app. I'm going to close this issue in favor of the discussion. Thanks again!
