### ISSUE TITLE
[Bug]: Operation timed out for "Sound"

### ISSUE THREAD

**Issue by Holger-erf** [jordanbaird/Ice#328]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

When I want to move menu bar icons from “Hidden Menu Bar Items” or “Alwais - Hidden Menu Bar Items” to “Visible Menu Bar Items” in the “Menu Bar Items” menu in the settings, I get the error message: 
Operation timed out for “Sound”
Please try again. If the error persists, please file a bug report at https://github.com/jordanbaird/Ice/issues.
After that, the icon I wanted to move has disappeared, and when I try to move menu bar icons from “Hidden Menu Bar Items” or “Alwais - Hidden Menu Bar Items” to “Visible Menu Bar Items” in the “Menu Bar Items” menu in the settings, I get the error message: 
Operation timed out for “Sound”
Please try again. If the error persists, please file a bug report at https://github.com/jordanbaird/Ice/issues.
After that, the icon I wanted to move has disappeared.

After two restarts of Ice, the bug no longer occurs After two restarts of Ice, the bug no longer occurs.

### Steps to Reproduce

x

### Ice Version

0.10.5

### macOS Version

MacOS 14.6.1

### Screenshots

x

**Comment by leikoilja** [comment]
I m getting it after the last updates for all icons that i m trying to arrange using `Menu Bar Items` on a mac m3 pro (with a notch)

**Comment by jordanbaird** [comment]
This is likely caused by some other app you have running on your system that interferes with the events that Ice sends to menu bar items. Do you use any third party window managers, or apps that handle mouse events?

**Comment by leikoilja** [comment]
yes for both. i use magnet for window management and Karabiner-Elements for keyboard shortcuts. Tho none of them should be handing mouse events from that i know.
interestingly, system reboot has solved the timeout issue for me
