### ISSUE TITLE
[Feature Request]: When using ice bar with location"Mouse pointer", show menu items' contex window in that location

### ISSUE THREAD

**Issue by venpopov** [jordanbaird/Ice#339]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

I love that the ice bar can appear wherever my mouse is, which is really helpful for an ultrawide monitor. However, when I click on a menu item on the ice bar, the drop down window from that item appears all the way to the right of the screen. The jump is very jarring. If technically feasible, it would be really nice to draw right under the item that is clicked.

### Screenshots

https://github.com/user-attachments/assets/508f9aaf-45c3-419e-817d-f926f3114593

**Comment by jordanbaird** [comment]
I kind of don't think this is possible, but I'll have to look into it more to be sure. For now, I'll keep this open, but just know that this is unlikely to happen.
