### ISSUE TITLE
menu bar appearance changes back to standard design after using full screen app

### ISSUE THREAD

**Issue by Jager422** [jordanbaird/Ice#34]
After using an app in full screen, the menu bar appearance reverts to the standard design. This happens regardless of what design is being used and is not affected by the hidden menu bar functionality in macOS (however, the menu bar being hidden does cause, when split menu bar is used, for the split design to still be visible. Occasionally, after a couple minutes outside of a full screen app, the functionality returns to normal, but this is inconsistent. The functionality always goes back to normal after restarting Ice.

**Comment by jordanbaird** [comment]
Does this happen regardless of the fullscreen app being used?

**Comment by Jager422** [comment]
It seems so, yes. I’ve tried Safari, Chrome, Lightroom, Finder, Kindle, and all Office apps and they all have the same issue.

**Comment by jordanbaird** [comment]
I've tried with several apps at this point, and I can't reproduce this issue. What version of Ice are you running?

**Comment by jordanbaird** [comment]
I reimplemented the fullscreen check that Ice uses, so I'm hoping this will fix your issue. Let me know if the problem is still there once the next release is out.
