### ISSUE TITLE
[Feature Request]: Handle Ctrl-LeftClick on Ice icon as a RightClick

### ISSUE THREAD

**Issue by homatyano** [jordanbaird/Ice#343]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Normally on a Mac "Ctrl + Left Click" is equal to "Right Click". But not so for Ice Bar, it interprets "Ctrl + Left Click" as a regular "Left Click".

Because of that, while using the touch pad, it's impossible to invoke the the Ice Bar's context menu by clicking on its icon in the menu bar.

### Steps to Reproduce

1. Perform a Left Click on the Ice Bar's icon in the menu bar while holding down the Control button on the keyboard.

Expected result: the Ice Bar's context menu is shown
Actual result: the popup with the hidden elements is shown.

### Ice Version

0.10.5

### macOS Version

14.6.1

**Comment by jordanbaird** [comment]
From what I've seen, menu bar items of different apps handle Control clicks in different ways. Some treat them as standard clicks, while others treat them as right clicks. Ice currently does the first option, but I'm open to changing that. In the meantime, note that you _can_ right click on a trackpad by clicking with two fingers.
