### ISSUE TITLE
[Bug]: Closing / Deleting App doesn't remove from Menu Bar Items Section in Ice

### ISSUE THREAD

**Issue by allmightychaos** [jordanbaird/Ice#345]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

When closing or especially deleting an app afterwards, it still shows in Ice → Menu Bar Items and you can't remove it. Restarting helps though. 

### Steps to Reproduce

1. Close / Delete opened App
2. Open Ice
3. Go to Menu Bar Items

### Ice Version

0.10.5

### macOS Version

14.6.1

**Comment by jordanbaird** [comment]
Do you use the Ice Bar feature? If so, does the issue only occur if you first click the item in the Ice Bar to temporarily show it? Or does it happen whenever you quit an app regardless of whether it's temporarily shown?

**Comment by jordanbaird** [comment]
Just realized this has the same root problem as #332. Closing as a duplicate.
