### ISSUE TITLE
[Bug]: Menubar items get dimmed on screens where the mouse pointer isn't

### ISSUE THREAD

**Issue by j-peeters** [jordanbaird/Ice#348]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

_I read the other issue where offscreen items get dimmed when moved but I guess this is different issue._

First, thanks for developing Ice, it's an awesome tool for someone with too many menu items ;-)

This hapens in a multimonitor (3) environment (macbook pro with two screens connected)
When a screen is not active (by having an active window on another screen) the menubar items get dimmed on the other screen. I don't know if this is expected behaviour but it has two disadvanteges for me:
- It currently is inconsistent: some icons stay undimmed (see screenshot and video)
- And it creates unrest in the interface. The icons are not very obtrusive when undimmed (black or white) so dimming them doesn't give much benefit (to me)

People that only have one screen might not see this behaviour.
I'm also not sure if macOS 15 RC causes this.

### Steps to Reproduce

Attach another screen.
Move your mouse to another screen
Click somewhere in the screen
Icons get dimmed on the not active screen

### Ice Version

0.10.5

### macOS Version

15 Release Candidate

### Screenshots

![20240913 CleanShot](https://github.com/user-attachments/assets/0f369afd-a6a5-4cdb-adc8-2cc1d40e0891)

https://github.com/user-attachments/assets/e099f123-d704-4d04-907a-c78c5293f594

**Comment by jordanbaird** [comment]
This is actually a behavior of macOS. It happens even when Ice isn't running. For better or worse, it's the behavior Apple seems to be going for. As for some items not dimming, I believe these apps are manually setting the color of their items, rather than using the Apple-recommended monochrome style.

**Comment by j-peeters** [comment]
Thanks for the clarification @jordanbaird I'll contact the respective developers of their non-changing icons.
