### ISSUE TITLE
Menu background in full screen video on Firefox

### ISSUE THREAD

**Issue by toine08** [jordanbaird/Ice#35]
### Description: 
When watching a video in full-screen mode on YouTube, the background of the menu bar remains visible, overlaying the top portion of the full-screen video. This is a visual glitch that occurs with the application that manages the menu bar on macOS.

Expected Behavior: When entering full-screen mode on YouTube or any other application, the menu bar should be hidden completely, allowing the full-screen content to occupy the entire display without any overlays.

Actual Behavior: While the menu bar items (such as the Apple logo, app menus, and system icons) disappear as expected, the background color or texture of the menu bar persists, covering the top portion of the full-screen video.

Steps to Reproduce:

1. Open YouTube in a web browser.
2. Play a video and click the full-screen button or use the appropriate keyboard shortcut to enter full-screen mode.
3. Observe that the menu bar items disappear, but the background of the menu bar remains visible, overlaying the top part of the full-screen video.

Environment:

- Operating System: macOS (specify version)
- Web Browser: (specify browser and version)

<img width="1512" alt="menu_topbar " src="https://github.com/jordanbaird/Ice/assets/50374594/bdf0b556-ab3c-4c42-89c7-3e74627e5978">

## Additional Notes:

- This issue seems to be specific to full-screen mode on YouTube, but it may also occur with other applications or video players on macOS.
- The severity of the issue depends on the contrast between the menu bar background and the video content, as well as the user's preference for a distraction-free full-screen experience.

**Comment by jordanbaird** [comment]
It seems to be specific to the way Firefox handled fullscreen prior to the 124.0 update. Their release notes for that version say:

> Firefox on Mac now uses the macOS fullscreen API for all types of fullscreen windows. This should better match the expected macOS user experience for fullscreen spaces, menubar and the Dock.

So it seems that prior versions used Firefox's own method for fullscreen windows, which didn't match the way Ice checks for fullscreen. I've tried other browsers (Chromium-based and Safari), as well as different video players, and they all seem to work fine. Make sure you're updated to the latest Firefox and restart your computer. I'm going to close this issue for now, but if the problem persists, feel free to re-open it.
