### ISSUE TITLE
[Bug]: Not working with macOS Sequoia

### ISSUE THREAD

**Issue by remusris** [jordanbaird/Ice#353]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

app does not run at all

### Steps to Reproduce

App does not run on the latest version of macOS

### Ice Version

not sure

### macOS Version

15.0

**Comment by jordanbaird** [comment]
When opening an issue, you need to provide more information. There's literally nothing I can do with how little you've given me. It works just fine on my two machines that both run Sequoia. If you haven't already, try updating to the latest version of Ice and restarting your computer.

**Comment by remusris** [comment]
I had bartender installed before but I tried uninstalling it then restarting my computer and nothing popped up in my menubar.  Not able to get a version number from the app because the app is not opening which is why I'm so startled.  I installed it both via homebrew and the zip file and failed both times.

**Comment by jordanbaird** [comment]
Right click on the app icon and click "Get Info". The version number should be in the window that appears.

**Comment by jordanbaird** [comment]
Did you have Ice on Sonoma? Did it work for you there? If not, try granting screen capture and accessibility permissions manually.

**Comment by remusris** [comment]
I did not have Ice on Sonoma, I installed it today on Sequoia.  Version 0.11.1 is what its showing me.  I just checked and I have all the permissions enabled.  Very strange. Wonder if some app is conflicting with it.

**Comment by jordanbaird** [comment]
Could be. Could also just be the typical buggy behavior of a day one macOS release. I just implemented a workaround that will hopefully resolve this in the short term. I'll work on getting a new release out with the change, so keep an eye out for it.
