### ISSUE TITLE
Feature Request:  Menu bar design style to fade in to / out of the display notch at the top of the screen.

### ISSUE THREAD

**Issue by pixelrogue1** [jordanbaird/Ice#36]
Feature Request:  Menu bar design style to fade in to / out of the display notch at the top of the screen. One option, for example, would be a gradient that goes full black at the center of the menu bar.
   
   This would then make the menu bar hide the notch with grace and intention.

**Comment by jordanbaird** [comment]
This is unfortunately not possible, as macOS doesn't actually allow you to change the color of the menu bar without changing the desktop background. And even then, it just blurs whatever is behind it. The most Ice can do is tint the menu bar slightly by adding an overlay on top.
