### ISSUE TITLE
[Feature Request]: Add Spacers in Menu Bar

### ISSUE THREAD

**Issue by MrMegira** [jordanbaird/Ice#366]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Option to Add Spacers to the Menu Bar for Better Layout Customization

### Screenshots

I’ve attached an example for illustration 

![CleanShot 2024-09-21 at 02 01 11@2x](https://github.com/user-attachments/assets/f52372d2-4702-4edf-9070-af7eada816f1)

**Comment by jordanbaird** [comment]
Duplicate of #91

**Comment by jordanbaird** [comment]
If you want the lines in the spacers, please comment on the existing issue. Do not open a new one.
