### ISSUE TITLE
[Feature Request]: Removing Gradient Stops

### ISSUE THREAD

**Issue by lumen-novum** [jordanbaird/Ice#369]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Is it possible to remove gradient stops in the menu bar? How would I do so?

**Comment by lumen-novum** [comment]
Is the only way to remove them to "reset" the menu bar?

**Comment by jordanbaird** [comment]
Hit the delete key while the stop is selected. Although, I could add an X button that appears over the corner when hovering. Would that be better?

**Comment by lumen-novum** [comment]
I tried every other key except the delete key lol. It doesn't need to be a high priority thing, but a small X button would be very helpful.

Thank you for your help.
