### ISSUE TITLE
Feature request: Stylization for internet status

### ISSUE THREAD

**Issue by pixelrogue1** [jordanbaird/Ice#37]
It would be very helpful to have a style element that gave the status of the internet connection.

--
Yes, there are several dedicated menu bar apps/icons that do this already, got it. That said, it is a waste of a menu bar slot just to see status of internet when a menu bar style could do the same. Example, small 1 pixel color when connected, another when not connected...or a gradient that changes based on state. So many options.

**Comment by jordanbaird** [comment]
This is too specific of a feature for me to be interested in implementing. If I accepted every feature like this, it would clutter up the interface and make the app impossible to use. However, in the future, I plan on implementing custom triggers for certain system events, one of which could be to monitor the internet connection. You could then assign an action to the trigger that would change the menu bar style to your preferences. But that's a ways down the road.

**Comment by pixelrogue1** [comment]
Appreciate the response. Had to disable most as the bar (with MacOS 14.4) has been somewhat buggy (if auto hide menu bar is on, or with screen dimmers etc.)Think you are on to something. Common goal of minimalism, so the idea of internet status would be to have it worked into the design itself (ie 1 pixel line green when on, red when disconnected, etc). Elegant design instead of added clutter. On Mar 30, 2024, at 9:21 AM, Jordan Baird ***@***.***> wrote:﻿
This is too specific of a feature for me to be interested in implementing. If I accepted every feature like this, it would clutter up the interface and make the app impossible to use. However, in the future, I plan on implementing custom triggers for certain system events, one of which could be to monitor the internet connection. You could then assign an action to the trigger that would change the menu bar style to your preferences. But that's a ways down the road.
