### ISSUE TITLE
[Feature Request]: Adjustable Menu Bar Height

### ISSUE THREAD

**Issue by betafruit** [jordanbaird/Ice#373]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

One of the thing I hate most using a mac with a notch now is that the menu bar is weirdly tall- and there is a 5ish pixel gap between the bottom of the menu bar and the bottom of the notch. It would be nice if I could make the menu bar shorter so that it lines up with the notch and is closer to its old height. It would also be nice if doing this naturally adjusts the area a window can take up so that a max height window does not have that same gap once the menu bar is shorter.

(I found [this reddit post](https://www.reddit.com/r/apple/comments/qh6qsh/on_the_new_mbp_the_menu_bar_is_actually_taller/) complaining about what I'm talking about and took the image from there)

### Screenshots

![photo](https://github.com/user-attachments/assets/7b1ba66a-f548-485f-be47-8a62c07205ee)

**Comment by jordanbaird** [comment]
This isn't possible, unfortnuately.

**Comment by jordanbaird** [comment]
Marking as a duplicate of #264 for future reference.
