### ISSUE TITLE
[Feature Request]: Only a (left) click on the dot will open the hidden section

### ISSUE THREAD

**Issue by Anoerak** [jordanbaird/Ice#376]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Using other tools such as NotchNook, having the whole menu bar clickable for Ice creates a conflict.
Every time I click on NotchNook, the Ice hidden section shows up.

Is it possible to have an option to only have the dot area as a (left) clickable to display the hidden section, like for the right click?

Thank you :)

### Screenshots

<img width="1173" alt="Screenshot 2024-09-24 at 13 56 21" src="https://github.com/user-attachments/assets/43e62cf4-2ec4-4cca-bd7d-d5ba4d5b5e6f">
<img width="1181" alt="Screenshot 2024-09-24 at 13 56 39" src="https://github.com/user-attachments/assets/813bfaa4-0659-4941-ae0c-18c6ce8ab750">

**Comment by jordanbaird** [comment]
Turn off the "Show on click" setting.
