### ISSUE TITLE
[Bug]: Hidden menu bar is exceedingly wide

### ISSUE THREAD

**Issue by jdwhite** [jordanbaird/Ice#379]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

The hidden menu bar used to be only as wide as needed to fit the hidden items. Now it takes up the whole width of my screen and then some. Note the scroll bars in the screenshots.

I've tried closing the app (and verified it wasn't running), deleting everything in `~/Library/*/com.jordanbaird.Ice*`, and restarting Ice. Didn't make any difference.

I did recently update to Sequoia, but it was working correctly post Sequoia. I was fiddling with Ice's settings last week with 0.11.4 when I started getting the wide hidden bar and haven't ben able to "reset" since.

### Steps to Reproduce

1. Ice Settings -> General -> Use Ice bar => ON
2. Set Location: Mouse Pointer (but no different with Dynamic or Ice Icon)
3. Trigger showing of the Ice Bar, however currently configured.

### Ice Version

0.11.5

### macOS Version

15.0

### Screenshots

![CleanShot_2024-09-26_10 15 02_Ice@2x](https://github.com/user-attachments/assets/116047f2-ca1e-43c1-bda6-4d742ae9510a)

![CleanShot_2024-09-26_10 14 23_CleanShot@2x](https://github.com/user-attachments/assets/28e1f63d-d442-4ddb-9670-750c455b792d)

Note the size of the scroll bars relative to the screen size. These were taken on an M1 MPB at 1512x982.

**Comment by Robert-Black** [comment]
Ditto

**Comment by jordanbaird** [comment]
You probably have some other app that manages menu bar items. The way these apps hide items is by introducing an extremely long menu bar item of their own that pushes other items off the screen, and this is what you'd be seeing. Some that come to mind are Bartender, iBar, Barbee, BetterTouchTool, and OnlySwitch. I've thought about making a change to check the width of items and not show them in Ice's interface if they're past a certain size.

**Comment by Robert-Black** [comment]
It was BTT for me.  For now I’ve just turned it off because I use it minimally. Interestingly I wasn’t having this issue earlier, so something (Sequoia?) changed.  Your suggested fix of checking the width of menu items to avoid the display glitch sounds promising, but for now just knowing the specific culprit is enough for me. Cheers!

**Comment by jdwhite** [comment]
Was BTT for me as well. I'm thinking BTT isn't working well with Sequoia. I don't see a BTT icon whether I have "show menu bar icon" enabled or not, if I have that enabled it then I don't get the wide menu bar -- but I also don't get a BTT menu bar icon.
