### ISSUE TITLE
[Feature Request]: Hotkey for toggling Ice Bar

### ISSUE THREAD

**Issue by redfastpony** [jordanbaird/Ice#381]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

I am using my Macbook primarily with an external monitor. But when I use it standalone, the camera notch prevent me to see important stats in my menu bar. Therefore I installed Ice. What really comes in handy is the icebar, which gets rid of the hidden menubar icons issue when only working on the macbooks internal screen. For toggling the icebar without entering the settings a hotkey would be much appreciated.

**Comment by jordanbaird** [comment]
As in toggling the feature on and off?

**Comment by musiklee** [comment]
Though I like the ice bar always, I can see the appeal for those that want to switch between the 2 views (especially for those that switch between using external monitor and using just laptop)

**Comment by musiklee** [comment]
Ice keeps getting better and better,   even though i did not ask for this one,  thank you!!

**Comment by redfastpony** [comment]
That was quick, thank you very much! 💪
