### ISSUE TITLE
[Bug]: Sequoia stuck during install

### ISSUE THREAD

**Issue by bnjmnrsh** [jordanbaird/Ice#384]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

The Accessibility and Screen Recording "Grant Permissions" buttons don't trigger the opening of system settings, and Im not sure what the equivalent options are to enable them manually. 

### Steps to Reproduce

Drag & Drop the Ice.app to the applications folder
First launch the permissions panel pops up but the "grant permissions" buttons are unresponsive
The descriptions of each option that needs to be enabled do not obviously correlate to  the screens available in system settings.

### Ice Version

0.11.5

### macOS Version

15.0

**Comment by jordanbaird** [comment]
Strange. I thought I had fixed this. In the meantime, the Settings panes you need to go to are `Privacy & Security > Accessibility`, and `Privacy & Security > Screen & System Audio Recording`. Click the `+` button at the bottom and manually add Ice.

**Comment by jordanbaird** [comment]
I believe I have fixed this (although the bug doesn't happen for me, so I can't be sure). Let me know if the problem persists once 0.11.7 is out.
