### ISSUE TITLE
[Bug]: <Showing Always Hidden Section Also Shows Hidden Section>

### ISSUE THREAD

**Issue by musiklee** [jordanbaird/Ice#385]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

When NOT using Ice Bar, Showing Always Hidden shows Hidden as well,   so it shows everything!!
Not so when Ice Bar is activated, (you can choose to see either of the 2,  not both @ same time unfortunately)
Not sure if this just happened with this new 0.11.6

### Steps to Reproduce

description describes problem

### Ice Version

0.11.6

### macOS Version

14.4.1

**Comment by jordanbaird** [comment]
Not a bug. This is the intended behavior. Because of the way Ice hides menu bar items, the always-hidden section can't be shown in the menu bar without also showing the hidden section.

**Comment by musiklee** [comment]
Hmmm.  So (without Ice active) we cannot have the "Visible" plus "Always Hidden" Only? Bummer, but OK

**Comment by jordanbaird** [comment]
It can be done if Ice arranges each section, but that's already covered by #310, I believe. Regardless, this is the current intended behavior.
