### ISSUE TITLE
[Bug]:ApplePay not working.

### ISSUE THREAD

**Issue by boettchs** [jordanbaird/Ice#386]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Hi, I initially paid $5 to test this as I was a current Bartender user.
I liked it enough that I removed BT and now wanted to pay some more.
I am on a Mac, and I tried ApplePay, but the process can't complete - the box where it normally shows the fingerprint never shows up and I can't complete the process...

### Steps to Reproduce

Goto "Support" and it shows $15 as I chose that.
Click blue button.
Enter email and click Pay
Tried all three cards and none of them will work...
See screenshot.

### Ice Version

0.11.6

### macOS Version

15.1

### Screenshots

![Screenshot 2024-10-01 at 12 44 10 PM](https://github.com/user-attachments/assets/76264753-75b8-4b6d-a1da-701ee23d1dd1)

**Comment by boettchs** [comment]
OK, I finally rebooted the Mac and was just now able to complete ApplePay.
Not sure why. - I had rebooted yesterday.
Anyways, might look to see if there's anything there.
Apologies that I didn't try that before rebooting...
Scott

**Comment by jordanbaird** [comment]
@boettchs No worries. Thank you for the donation! I saw that it did indeed go through. I'm not sure there's anything for me to do here, as the ApplePay interface would be handled by either Buy Me a Coffee or Stripe. I'm guessing it was a temporary outage/bug on their end, or something similar. I'm going to go ahead and close this. Thanks again for the support!
