### ISSUE TITLE
[Bug]: "Event operation timed out" error every time I try to move something in menu bar layout editor

### ISSUE THREAD

**Issue by to-turion** [jordanbaird/Ice#389]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

I've been getting the following error every time I try to move items in the editor. The issue persists after updating to the latest version.
![CS_Ice_Menu Bar Layout_2024-10-02_22 59 08@2x](https://github.com/user-attachments/assets/bb5003d3-3125-43cc-9c1f-4ed7dc5d4e27)

### Steps to Reproduce

1. Open Settings
2. Go to Menu Bar Layout
3. Click any icon and try to move it
4. See error popup that says:
 

> Event operation timed out for [name of app]
> Please try again. If the error persists, please file a bug report.

### Ice Version

0.11.7

### macOS Version

15.0

**Comment by jordanbaird** [comment]
Please try the following:

1. Quit Ice
2. Run the following command in Terminal: `tccutil reset All com.jordanbaird.Ice`
3. Launch Ice (it will ask you to grant screen recording and accessibility permissions again)
4. Make sure you properly grant both permissions – do not leave either one unchecked
5. Quit and relaunch Ice

Let me know whether or not it works.

**Comment by jordanbaird** [comment]
Any update on this?

**Comment by jordanbaird** [comment]
Closing due to no response.

**Comment by emperinter** [comment]
Same problem, still not working after authorisation as above.

**Comment by emperinter** [comment]
Currently, the system status bar can be arranged by Command+Drag, and the following problems have occurred:

- Unable to dragging, error message appeared [in software].
- Application icons are arranged chaotically [in software/system status bar].
- The operation bar suddenly turns black, the icons become bigger, etc. [Software/System Status Bar].

It feels a bit like there is a conflict between the system status bar and the layout operation in the software, or the software writing method is similar to the singleton mode, and the operation of the software will affect the status bar, and vice versa.

![图片](https://github.com/user-attachments/assets/8303ae24-1de8-4b71-845c-d4cc24bc8080)
<img width="457" alt="图片" src="https://github.com/user-attachments/assets/6f788868-7f9d-45a7-8bbe-f92bd2451673">
![图片](https://github.com/user-attachments/assets/30c10704-1c3e-4573-99dc-d8258f1fd583)

**Comment by pacaroha** [comment]
This bug also affects me, though only on one of my systems with Ice on it, and I can't fully understand why.

I have also noticed that when Ice fails to move one of these items, the Apple icon in the top-left corner also acts as though it has been clicked, briefly.
