### ISSUE TITLE
About "Menu bar items are rehidden after a fixed time of 30 seconds."

### ISSUE THREAD

**Issue by smart-z** [jordanbaird/Ice#39]
Is it possible to set the maximum value to 5 minutes, 300 seconds? Currently, the maximum value is 30 seconds, and the consequence is that when I click on the menu bar, it closes. Then I have to open the menu bar again.

It's a bit like when some people set their phones to enter power-saving mode after 5 seconds to save battery. So often, you can see these people's eyes just leave the screen, and the phone locks, and then they start unlocking it again. I wonder how many times these people have to unlock their phones in a day?

Please consider! THANK YOU !!! ❤️❤️❤️

**Comment by jordanbaird** [comment]
Is 30 seconds really not enough? If you have it set to 5 minutes, why even hide the menu bar? I'm willing to consider it, but I just don't see a use case for it.

**Comment by smart-z** [comment]
> Is 30 seconds really not enough? If you have it set to 5 minutes, why even hide the menu bar? I'm willing to consider it, but I just don't see a use case for it.

I prefer it clean, so I want to hide icons on the menubar.
For me, 3 minutes is enough.
Sometimes I use an app to hide icons for about 1-2 minutes, so when I open this app, after about 10-15 seconds, it disappears. Then I have to repeat the process. Of course, moving the app to the visible area solves my problem. So, that's my problem, too
THANK YOU

**Comment by jordanbaird** [comment]
Perhaps the smart rehide option would be a good fit for you as well?
