### ISSUE TITLE
Ice posts below drop down menu and stays, until clicked in an open area of the menu bar, Apple Mail + other apps

### ISSUE THREAD

**Issue by macmanjimmy** [jordanbaird/Ice#391]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Ice posts below drop down menu and stays, until clicked in an open area of the menu bar, Apple Mail + other apps

Screenshot shows Brave, but popped up during Apple Mail

### Steps to Reproduce

1. Goto mail 2 click on new email 3. Ice Menu shows directly below drop down

### Ice Version

0.11.8.1

### macOS Version

15.0

### Screenshots

![Screenshot 2024-10-05 at 10 05 44 AM](https://github.com/user-attachments/assets/334db21a-00db-4f84-b117-a7686db81866)

**Comment by jordanbaird** [comment]
I don't understand your issue at all. Nothing happens when I follow your steps, which aren't very specific. What exactly are you doing to get this to happen?
