### ISSUE TITLE
[Feature Request]: Multiple Style Options For Dynamic Light/Dark Mode Wallpaper

### ISSUE THREAD

**Issue by thartrich** [jordanbaird/Ice#393]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Create 2 or more style options for [Menu Bar Appearance] Tint/Shadow/Boarder based on macOS light/dark mode system auto appearance, allowing the menubar to reflect the preference for both a light/dark theme wallpaper.

Example: Set a solid color for a **light** desktop wallpaper when in light mode and a separate solid color for **dark** desktop wallpaper color when in dark mode.

**Comment by thartrich** [comment]
![Mockup](https://github.com/user-attachments/assets/e18d83b3-bea4-4b89-8385-f39562183f45)

**Comment by thartrich** [comment]
![Light:Dark Mode Mockup](https://github.com/user-attachments/assets/3068199c-0ca0-4827-8a73-cf491a71b4e0)

**Comment by jordanbaird** [comment]
I like this idea!
