### ISSUE TITLE
[Feature Request]: Support showing ephemeral menu bar items

### ISSUE THREAD

**Issue by n3bulous** [jordanbaird/Ice#395]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Apps like Dato can display an optional menu bar item for the next calendar item.

Currently, Ice puts these items in the always hidden section. They can be moved to the visible section, but the following calendar item will be hidden (I believe -- I know it does not persist after restarting).

This image shows an example of the menu bar item in the hidden section:
![CleanShot 2024-09-24 at 10 25 15](https://github.com/user-attachments/assets/9640413b-5cd6-4996-bafc-e554de675565)

An image after dragging it. I would expect Ice to remember the position to be remembered for all items like this:
![CleanShot 2024-09-18 at 09 12 11](https://github.com/user-attachments/assets/62907dd1-c245-4a49-a013-0ab3eb6ab16d)

**Comment by jordanbaird** [comment]
It's not Ice that's doing this. See #298 for why this is happening and what will be done about it.

**Comment by n3bulous** [comment]
I bring it up mainly as bartender doesn't have this problem.

Also, apologies for not finding that issue via my searches.

**Comment by jordanbaird** [comment]
I understand that. I'm definitely working on a solution for it. Keep in mind that while Bartender has had over a decade to be perfected, Ice has been around for less than a year, so there's absolutely some catching up to do.

And no worries, GitHub can make it kind of difficult to find things haha.

**Comment by n3bulous** [comment]
Awesome.  Thanks for Ice, Jordan!
