### ISSUE TITLE
Menu bar appearance overlay is displayed when Firefox is fullscreen

### ISSUE THREAD

**Issue by peterge1998** [jordanbaird/Ice#40]
When Firefox is in Fullscreen mode (for example when watching Netflix), my Menu bar does show up when Ice is running:
<img width="1470" alt="image" src="https://github.com/jordanbaird/Ice/assets/47355238/235ffb9f-61e4-4fa3-9a30-b32711711dbb">

When Ice is disabled, it looks fine:
<img width="1466" alt="image" src="https://github.com/jordanbaird/Ice/assets/47355238/c548af60-7c5f-4996-a99f-caf819822cac">

This is what Ice looks like on my mac normally:
<img width="1470" alt="image" src="https://github.com/jordanbaird/Ice/assets/47355238/a129f78d-d29f-4845-a27c-8c13107b5487">

This is quite annoying when watching movies :/

(The netflix parts get greyed out in my screenshots due to drm on macos)

**Comment by jordanbaird** [comment]
Duplicate of #35

**Comment by peterge1998** [comment]
It does still not work for me after updating from 123.1 to 124.1...
<img width="340" alt="image" src="https://github.com/jordanbaird/Ice/assets/47355238/0e4af5e2-bfd0-4bd4-b94c-6747a24cbb57">
<img width="1467" alt="image" src="https://github.com/jordanbaird/Ice/assets/47355238/d0a990eb-527f-4d84-a819-bf8af59f0089">

**Comment by jordanbaird** [comment]
What version of Ice are you running?

**Comment by jordanbaird** [comment]
I reimplemented the fullscreen check that Ice uses, so I'm hoping this will fix your issue. Let me know if the problem is still there once the next release is out.

**Comment by peterge1998** [comment]
> What version of Ice are you running?

<img width="372" alt="image" src="https://github.com/jordanbaird/Ice/assets/47355238/03ecd524-65d2-4423-8487-da230069f201">

**Comment by peterge1998** [comment]
> I reimplemented the fullscreen check that Ice uses, so I'm hoping this will fix your issue. Let me know if the problem is still there once the next release is out.

Any ETA when this will happen? I started watching the releases to keep track. Thank you <3

**Comment by jordanbaird** [comment]
> Any ETA when this will happen? I started watching the releases to keep track. Thank you <3

Not sure. There are a few more fixes I need to make and things I need to clean up. Hopefully soon.

**Comment by peterge1998** [comment]
<img width="1470" alt="image" src="https://github.com/jordanbaird/Ice/assets/47355238/22f0e0a8-1cb9-4e27-8e19-03aa5bd7fe5f">
Ice is still beeing display while firefox is in fullscreen mode with 0.8.0 :(

**Comment by jordanbaird** [comment]
Ah, dang. I'll reopen this issue and see what else I can work out.

**Comment by Jager422** [comment]
I've noticed this same issue happening with at least Safari, OneNote, and when apps are shown in split fullscreen with the latest release.

**Comment by peterge1998** [comment]
This is fixed, the color of ice is not showing anymore. I will close this :)
<img width="1470" alt="image" src="https://github.com/jordanbaird/Ice/assets/47355238/514decbc-a4f6-4801-9f2b-7d2f0d59bc92">
