### ISSUE TITLE
[Bug]: Menu Spacing is not consistent

### ISSUE THREAD

**Issue by kristiankruse** [jordanbaird/Ice#402]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

When changing `default` spacing to e.g. -10, then icons are not having consistent spacing.
Same goes for -12 and other values.
![screenshot 2024-10-12 at 17 18 25@2x](https://github.com/user-attachments/assets/ba0df117-91e3-43b4-8791-e8009ad13817)

### Steps to Reproduce

Change menu spacing (in beta)

### Ice Version

0.11.9

### macOS Version

15.1

**Comment by jordanbaird** [comment]
Does it stay like this after logging out and logging back in?

**Comment by kristiankruse** [comment]
It stayed for a bit but I restarted now and the spacing is even. Weird, it didn't do that the first time. Thanks for checking
