### ISSUE TITLE
[Bug]: macOS Sequoia requires a restart of Ice to render the menubar border

### ISSUE THREAD

**Issue by tigeryfan** [jordanbaird/Ice#409]
### Check Existing Issues

- [x] I have checked existing issues, and this issue is not a duplicate

### Description

After upgrading to macOS Sequoia, the border function doesn't work properly. Only after quitting and reopening the app does it show up. It appears this bug only occurs when the app is launched via login items.

### Steps to Reproduce

1. Make sure Ice is set to launch on login
2. Restart
3. Notice that the Ice menubar is not rendering a border
4. Quit and reopen the Ice app
5. Notice that the Ice menubar now correctly renders a border

### Ice Version

0.11.10

### macOS Version

15.0.0

**Comment by jordanbaird** [comment]
I can't seem to reproduce this, but I'll look at the code to see what might be causing it.

**Comment by jon-hotaisle** [comment]
Oh, I just found this issue after filing #446. Quitting and restarting Ice "fixed" it.

**Comment by lookfirst** [comment]
@tigeryfan I think the critical thing here is that it happens on a brand new machine. Have you tried a brand new clean install?

**Comment by tigeryfan** [comment]
> @tigeryfan I think the critical thing here is that it happens on a brand new machine. Have you tried a brand new clean install?

I'll try to spin up a VM later and test this theory out

**Comment by lookfirst** [comment]
@tigeryfan let me know how it goes, in this case, i used migration assistant to move to a new machine and encountered this issue.

**Comment by tigeryfan** [comment]
After over a dozen VM instances, I can conclude that this issue only occurs on a brand new installation/after a macOS upgrade. Thanks for the tip.

**Comment by lookfirst** [comment]
@tigeryfan re-open the issue?

**Comment by tigeryfan** [comment]
How should we fix this issue? An option is to restart Ice if the app is in its first run state, but that would be UX-unfriendly. Can anyone suggest better alternatives?

**Comment by lookfirst** [comment]
It is one restart... I'd just do it. If you really want to be complete, you could show a dialog notifying the user.
