### ISSUE TITLE
High CPU, memory, and energy usage

### ISSUE THREAD

**Issue by soukingang** [jordanbaird/Ice#41]
A cool and very useful tool，but its energy usage is relatively high, such as CPU、memory
may optimize it? thanks

<img width="388" alt="SCR-20240401-ltot" src="https://github.com/jordanbaird/Ice/assets/2391550/11537de9-fde3-4a6d-864d-78d90b049f74">
<img width="315" alt="SCR-20240401-ltrm" src="https://github.com/jordanbaird/Ice/assets/2391550/8a405124-8696-401d-ad9c-539f77d58628">
<img width="278" alt="SCR-20240401-lvwd" src="https://github.com/jordanbaird/Ice/assets/2391550/68e53142-e1d3-4920-a074-aea12c9f5278">

**Comment by jordanbaird** [comment]
What settings do you have enabled to cause such high numbers?

**Comment by soukingang** [comment]
The settings ：

<img width="900" alt="image" src="https://github.com/jordanbaird/Ice/assets/2391550/0a8909d0-3c22-475b-8244-1de9d5c300fd">

<img width="881" alt="image" src="https://github.com/jordanbaird/Ice/assets/2391550/36c31eef-a9cc-4b1f-a929-52c3e12717cc">

<img width="881" alt="image" src="https://github.com/jordanbaird/Ice/assets/2391550/6e04e6b3-5d47-4814-a984-e389c2a4e9f3">

And my app on the menu bar：
<img width="528" alt="image" src="https://github.com/jordanbaird/Ice/assets/2391550/dca0b696-fdcd-4768-af09-b40dc62fe5cc">

**Comment by soukingang** [comment]
@jordanbaird 
**Last night，i turn on the "show on hover" option, like this:**
<img width="899" alt="SCR-20240402-kbau" src="https://github.com/jordanbaird/Ice/assets/2391550/da724fd7-03c3-40aa-b9f9-1fc67026623d">

**Now，when i hover the menu bar, my hidden icon appear ,but its memory usage is too high（usage：538.7MB）**
<img width="343" alt="image" src="https://github.com/jordanbaird/Ice/assets/2391550/8c916074-e1d5-4f29-afe5-ff2c923b8f4d">

<img width="721" alt="image" src="https://github.com/jordanbaird/Ice/assets/2391550/adbeafa5-44d9-4dd6-b5e4-a8fb90f7eacd">

<img width="589" alt="image" src="https://github.com/jordanbaird/Ice/assets/2391550/69381ff0-fc68-400b-82af-1d7aa761e366">
。。。

**Please optimize it ，thank you very much**

my Mac:
OS version is Sonoma 14.4.1
Apple M3 Max
Memory:36 GB

And what anything else i can provide？

**Comment by jordanbaird** [comment]
Wow, that's bad. I have never had it go above 90 MB on my machine. Does it still have high memory usage immediately after restarting Ice? I'm thinking there is a memory leak somewhere.

**Comment by soukingang** [comment]
> Wow, that's bad. I have never had it go above 90 MB on my machine. Does it still have high memory usage immediately after restarting Ice? I'm thinking there is a memory leak somewhere.

Not immediately , its memory usage is high，sometimes. And when i hover menubar，it is high very often（watch the videohttps://www.dropbox.com/t/UyAK918EDn1TeVnL）

i try restarting ice ，and restart my computer， it still has high memory usage sometimes （and very often in certain situation）


What can i provide some other info about it，and how..? thanks.

**Comment by jordanbaird** [comment]
I can't reproduce this. Like I said, it mostly stays below 90 MB on my machine. In my testing, I was able to get it to jump to around 100 MB, but that was a rare case. In fact, more often than not, memory usage is around 50 MB. There must be something specific to your configuration that's causing this. What's strange is that memory usage should actually go _down_ when menu bar items are being shown, not up.

Can you clarify whether it only happens when you use the "show on hover" feature? Or does it happen more generally when showing menu bar items?

**Comment by exlemor** [comment]
Hi Jordan,

Not sure if this helps but I use ICE on the last generation Intel Macbook Pro [right before M1] it's an Intel Core i9, 2.9Ghz, with 32gig DDR 4 RAM, dual graphics card (even though the Radeon doesn't turn on for ICE use), and it typically takes:

120-130mg of RAM, 9 threads, around ~465 ports,
3.0%-5.5% CPU / 40.84 GPU Time [on for 20hrs straight]

After a restart the CPU restarts at ~ 1.9%-2.1%, around 44mg of RAM.

So it appears that over time it grows slightly - maybe a memory leak issue? 

If that helps :)

**Comment by jordanbaird** [comment]
@exlemor thanks for the insight. Some memory growth is normal throughout the use of any program due to lazy loading of resources, but this does seem like a little too much. I'll look into the possibility of a memory leak.

**Comment by jordanbaird** [comment]
@soukingang after updating to 0.8.0, do any of these things get better? I did several optimizations for the release that I'm hoping will at least show some improvement.

**Comment by soukingang** [comment]
@jordanbaird Tonight, i will try using ...  Thanks a lot : )

**Comment by soukingang** [comment]
<img width="480" alt="image" src="https://github.com/jordanbaird/Ice/assets/2391550/ff6bcc0f-dc08-4013-9c8b-34b61f7cfaf9">
@jordanbaird 
a bad news...
its memory usage has a little big,
i try removing and reinstall it, but it remains
<img width="580" alt="image" src="https://github.com/jordanbaird/Ice/assets/2391550/1f8bbd85-678b-4c08-b813-96134c39dff0">


i had tried closing the menu bar apps, one by one . At last all my apps on the menubar (except built-in system) were closed, but its memory usage had still a little big , sometimes (be patient for a while) on my mac
<img width="636" alt="image" src="https://github.com/jordanbaird/Ice/assets/2391550/4cc07516-f4b8-4de5-9259-f933c59b97e2">

I know it is strange ,but it appears ... although not often


Hope it will be fixed some day, but it's not urgent and It's possible that it can only be reappear on my mac ：（

if you need some info（about this）what i can provide，you can reply me any time 。
--- that's my pleasure ：）

**Comment by jordanbaird** [comment]
Is this still a problem as of the latest release (0.10.2)?

**Comment by soukingang** [comment]
> Is this still a problem as of the latest release (0.10.2)?
@jordanbaird 
it doesn't happen any more,thanks

**Comment by dxvgef** [comment]
I have the same phenomenon，ice often uses more energy than google chrome and jetbrains goland

<img width="804" alt="Image" src="https://github.com/user-attachments/assets/dfc6a394-0d30-401b-a09c-f39973260492" />

This is my settings

<img width="890" alt="Image" src="https://github.com/user-attachments/assets/d67b3e84-f584-46f4-9e21-2fe2181abd1f" />
