### ISSUE TITLE
[Feature Request]: remove screen recording

### ISSUE THREAD

**Issue by deardaveed** [jordanbaird/Ice#415]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Hi --- thank you for your hard work. Why is it apps like Bartender and Ice must require screen recording, but an app like Hidden Bar doesn't?

Can we remove screen recording? I understand this is open source, but I imagine it wouldn't be too difficult for nefarious actors to slip in some kind of code that sends screenshots back to an address?

**Comment by Write** [comment]
Duplicate of https://github.com/jordanbaird/Ice/issues/75

**Comment by jordanbaird** [comment]
As @Write said, this is a duplicate. There is a pull request open that I believe will address these changes, but I haven't had time to look at it yet.

**Comment by jordanbaird** [comment]
As for the reasons why Ice requires screen recording permissions, see #362
