### ISSUE TITLE
[Bug]: Ice repeatedly moves MegaSync to Always-Hidden Section

### ISSUE THREAD

**Issue by troyyyyyyyyyyyyy** [jordanbaird/Ice#417]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

I move it back to Visible or Hidden. After some time it is always back in Always-Hidden. Sometimes I will need to completely quit Ice to see the MegaSync menubar item again.

### Steps to Reproduce

Open MegaSync, wait.

### Ice Version

0.11.9

### macOS Version

15.0.1

**Comment by jordanbaird** [comment]
Duplicate of #344
