### ISSUE TITLE
[Bug]: A chevron is shown in list of hidden apps

### ISSUE THREAD

**Issue by matschou** [jordanbaird/Ice#418]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

When I show my hidden apps a chevron is also shown. The chevron doesn't seem to serve any purpose. When I click the chevron the list of apps is hiddens, just like when I click on the actual ice icon. 

### Steps to Reproduce

1. Show hidden apps in menu bar
2. See chevron icon with no purpose

### Ice Version

0.11.11

### macOS Version

15.0.1

### Screenshots
<img width="272" alt="Menu bar with hidden apps and Ice icon" src="https://github.com/user-attachments/assets/1953b5d8-1df1-479c-bce0-579648504c30">
<img width="566" alt="Hidden apps shown with Ice icon and chevron " src="https://github.com/user-attachments/assets/099d94c3-b8e5-485c-8ebe-9c805f56244e">

**Comment by jordanbaird** [comment]
Not a bug. The chevron is just to show where your hidden items start. You can turn it off by disabling the "Show section dividers" in Advanced settings.

**Comment by matschou** [comment]
Ah, my bad. Didn't see that setting.
