### ISSUE TITLE
How to control which section (hidden, always hidden) apps are assigned to?

### ISSUE THREAD

**Issue by nodeOfCode** [jordanbaird/Ice#42]
All my apps get assigned to the hidden section. I'd like certain apps (e.g. calendar, system monitor) to be in always visible.

The closest setting I could find is layout, which only says 'coming soon'. Appreciate the hard work!

**Comment by jordanbaird** [comment]
Hold down the Command key and drag each menu bar item into the section you want it to be in. The sections are separated by arrows, which will appear when you start to drag. The visible section is to the right of the large arrow, the hidden section is between the large and small arrows, and the always-hidden section is to the left of the small arrow. There is also a visual example of this at the top of the README.

**Comment by nodeOfCode** [comment]
TY! Saw the example but were no instructions. Thought it might be a coming soon feature.
