### ISSUE TITLE
[Bug]: Menu Bar items automatically show/hide when click on Application Menu Items

### ISSUE THREAD

**Issue by Kayxue** [jordanbaird/Ice#421]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Just like the title, icons in menu bar automatically show/hide
Note: But this phenomena doesn't happen if you click on Application Menu items of Finder App
https://github.com/user-attachments/assets/7e001443-177b-4af6-92a3-403c1e516128

### Steps to Reproduce

1. Open an Application (but except Finder)
2. Click on items on Application Menu bar

### Ice Version

0.11.12

### macOS Version

15.2 Beta (24C5057p)

### Screenshots

The video has already been attached

**Comment by bwt615** [comment]
I think I have the same issue. You click a menu bar icon and then it decides to show permanently?

**Comment by iamsoum** [comment]
I can't replicate this issue with any app

**Comment by Kayxue** [comment]
Seems that this is the issue about Mac OS, no this problem for now, I'll close this issue.
