### ISSUE TITLE
[Bug]: <Ice App auto Open When Pressing the Ice Icon>

### ISSUE THREAD

**Issue by CoderDJJD** [jordanbaird/Ice#422]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

I am writing to report an issue I am experiencing with the Icebar app. When I click the Ice icon button to hide items in the menu bar, the app unexpectedly appears on the dock after two or three clicks. This error does not affect the apps functionality.  

### Steps to Reproduce

1. Begin by clicking on the Ice icon located in the menu bar.
2. Click the icon two to three times to proceed.
3. Once completed, the Ice app will appear in the dock.
4. To remove the Ice app from the dock, simply press the Ice icon again, and it will automatically disappear.

### Ice Version

11.12

### macOS Version

15.2 beta

**Comment by jordanbaird** [comment]
Not a bug. This is needed to hide the application menus, and is an intended feature. If you don't want this, disable the "Hide application menus when showing menu bar items" settings in the Advanced settings pane.
