### ISSUE TITLE
[Bug]: There is no "Always-Hidden" section

### ISSUE THREAD

**Issue by lapinvert** [jordanbaird/Ice#423]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

I am using the latest version 0.11.12 on MacOs 14 and there is no Always-Hidden section within "Menu Bar Layout". Only "Visible Section" and "Hidden Section".
What am I missing?

### Steps to Reproduce

1. Open Ice settings
2. Navigate to "Menu Bar Layout"

### Ice Version

0.11.12

### macOS Version

14.4

**Comment by jordanbaird** [comment]
Not a bug. You need to enable it in the Advanced settings.
