### ISSUE TITLE
[Feature Request]: Make the manu bar completely black regardless of wallpaper

### ISSUE THREAD

**Issue by Qvinto1** [jordanbaird/Ice#426]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Thanks for such a great piece of software. I have a request for a small feature change. 
Would it be possible to change the tint of the top bar to be completely black? this hides the notch. Currently you can only make the colour darker than your wallpaper but not completely black. The only way to hide the notch is to use a wallpaper that is black at the top. It would be great if we could make the top menu bar black regardless of wallpaper. Thank you!

**Comment by jordanbaird** [comment]
This isn't possible. As you said, the only way to truly change the color of the menu bar is to change the wallpaper. The reason Ice can only tint the menu bar is because it adds its own translucent overlay on top of it.
