### ISSUE TITLE
[Bug]: Always-hidden are... always hidden

### ISSUE THREAD

**Issue by riadhrebei** [jordanbaird/Ice#429]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Can't open the always-hidden section by clicking ⌥ + ice at the same time, I always have to search menu bar items to find the always hidden ones when I need them, they don't reappear when rearranging using ⌘ click either

### Steps to Reproduce

1. Click ⌥ + Ice
2. Nothing appears

### Ice Version

0.11.12

### macOS Version

15.1

**Comment by podfeet** [comment]
@riadhrebei I'm also running 15.1 with Ice version 0.11.12 and I can't replicate the failure. I have too many menu bar items to see all the way to the left for the hidden items. Option-clicking shows me all my hidden ones first so I can't verify if it works.

I have to use the Ice Bar. With it enabled, option-clicking in the empty space shows me my always hidden items. 

Do you have the Ice Bar enabled?

**Comment by riadhrebei** [comment]
Here are the settings for the menu bar items
![CleanShot 2024-11-10 at 18 17 13@2x](https://github.com/user-attachments/assets/8ac28f7f-2629-471b-a827-f3aa05026708)
And here's the failure to show the always hidden apps while holding ⌥ and selecting the option from the dropdown menu
![CleanShot 2024-11-10 at 18 17 44](https://github.com/user-attachments/assets/c641023b-00a5-452f-920e-500f5d50c92a)

**Comment by jordanbaird** [comment]
@riadhrebei You're not supposed to hold ⌥ when showing the always hidden section from the menu. Only when clicking the Ice icon. Just click it like normal in the menu.
