### ISSUE TITLE
Menu bar styling crashes app

### ISSUE THREAD

**Issue by Emerald525** [jordanbaird/Ice#43]
Hi, just wanted to say that after downloading and messing around with the color option as well as the menu bar styling feture on 0.8.0, the app continues to crash whenever booting into the menu bar options menu of ice. I would love a fix because this is an amazing app that I would love to see grow

**Comment by jordanbaird** [comment]
Could you go into your Console app, select "Crash Reports" in the sidebar and paste the latest report for Ice in a comment?

**Comment by Emerald525** [comment]
Hi @jordanbaird, I would but it isn't showing up with crash report info in the console at the moment. Do you think a restart would fix that issue and it would start showing up with the crash report info?

**Comment by jordanbaird** [comment]
Strange. It doesn't seem like it's an actual crash then. Could you send a screen capture video that shows what happens?

**Comment by Emerald525** [comment]
[Ice-2024-04-07-102730.txt](https://github.com/jordanbaird/Ice/files/14897706/Ice-2024-04-07-102730.txt)

Here is the crash file, I somehow must have hit ignore or smth when one of the crashes happened. I hope this helps!

**Comment by jordanbaird** [comment]
Where did you get that crash file from? It doesn't give me much information that I can work with.

**Comment by jordanbaird** [comment]
I have a suspicion as to where the crash may be coming from. Let me rework some things and see if that fixes it.

**Comment by jordanbaird** [comment]
@Emerald525 is this still a problem with the latest release?

**Comment by jordanbaird** [comment]
Closing as stale.
