### ISSUE TITLE
[Bug]: Conflicts with boring.notch

### ISSUE THREAD

**Issue by CyanideSunryz** [jordanbaird/Ice#430]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

boring.notch (https://github.com/TheBoredTeam/boring.notch/) periodically causes Ice to crash [I'm reporting the bug to them as well]

### Steps to Reproduce

1. Run both Ice and boring.notch (2.2) on a Mac
2. After an irregular amount of time (sometimes minutes, sometimes hours) Ice's processes will stop and Ice will exit
3. boring.notch does not appear to be affected but the issue only seems to occur when it is running

### Ice Version

0.11.12

### macOS Version

15.1

**Comment by jordanbaird** [comment]
I very much doubt boring.notch is causing this. If anything, Ice is crashing on its own and it's just gone unnoticed. That should be its own issue, though.

**Comment by richardkunkli** [comment]
Hey @jordanbaird 
Boring.Notch dev here, I also don't think it's some sort of interfere of the two apps. Thanks for clarifying it. 🚀
