### ISSUE TITLE
[Bug]: Mega.nz constantly going to "Always Hidden Section"

### ISSUE THREAD

**Issue by jayhawx** [jordanbaird/Ice#431]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

No matter how many times I set it, Mega.nz desktop app goes into the Always-Hidden Section. Running Sequoia 15.1. 

### Steps to Reproduce

Launch Mega.nz, doesn't show, then go into Ice settings > Menu Bar Layout and its in the Always Hidden Section

### Ice Version

0.11.12

### macOS Version

15.1

**Comment by jordanbaird** [comment]
Duplicate of #344
