### ISSUE TITLE
[Feature Request]: Always hide Application Menus except app name

### ISSUE THREAD

**Issue by ovanbiervliet** [jordanbaird/Ice#436]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

I'm looking for a setting similar to "Hide application menus when showing menu bar items," but in reverse. By default, this would hide all app menus _except for the app name_. This change would create more space for the menu bar items, which I find practical. The application menus would only appear when hovering over or moving towards the app name.

### Screenshots

![Ø-231114-S7BBpCyD@2x](https://github.com/user-attachments/assets/fefeda2a-ab81-46bd-a031-d570eb915b1e)
![Ø-231114-pDxUGXZr@2x](https://github.com/user-attachments/assets/fd8d15c4-ec0a-4a11-b7cf-516bd3d8d140)

**Comment by jordanbaird** [comment]
This isn't possible, unfortunately.
