### ISSUE TITLE
[Bug]: Ice settings window opens on startup

### ISSUE THREAD

**Issue by Xytronix** [jordanbaird/Ice#44]
### Description

The settings menu launches on startup, better to avoid it by launching in menubar only.

**Comment by jordanbaird** [comment]
Do you mean the settings window? If so, this is a bug. Nothing should open on startup.

**Comment by Xytronix** [comment]
Yeah settings window. I can look into reproducing it.

**Comment by jordanbaird** [comment]
Does this still happen as of the latest release (0.10.2)?

**Comment by Xytronix** [comment]
Doesn't anymore.
