### ISSUE TITLE
Ice is not displaying Stats module

### ISSUE THREAD

**Issue by iamsoum** [jordanbaird/Ice#443]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

I'm talking about [Stats app](https://github.com/exelban/stats) used to show multiple or combined modules, in this case I'm using combined modules. You can see in the screen recording that placing the module to the very left causes the issue. And if I place it right after the next icon to the left then the module is shown but that icon that was to the right of it now is not visible. However, this issue isn't there when it's in the dropdown menu. I do want it in the main menu though.

### Steps to Reproduce

1. Get ice to have same setup appearance preview as mine
2. Setup Stats combined or individual modules
3. Shove it to always show and to the very left
4. Restart Mac (just in case)
5. Whenever ice is capturing the screen at the moment or if you place one more icon on the always show section then the combined module will disappear and it'll also disappear if it's placed to the very left (space issue?)

### Ice Version

0.11.2

### macOS Version

15.1

### Screenshots

https://github.com/user-attachments/assets/d4a3d595-7e26-477c-84ca-d4a680d61772

__

**Comment by jordanbaird** [comment]
In the screen recording you attached, it isn't being shown because there isn't enough space due to the notch. This is a macOS limitation and has nothing to do with Ice.
