### ISSUE TITLE
[Feature Request]: Random play wallpaper support enhance

### ISSUE THREAD

**Issue by zomosky** [jordanbaird/Ice#455]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Ice is a very nice app!! thanks!! but i find a small quesiton can enhanced, when i use random play wallpaper, the wallpaper will chanced every minutes,  i find the Ice can catch the wallpaper change (by recording the screen maybe), but the change was a bit Stiff and rough, can we enhanced this feature by smooth or other function? nice job!!!

**Comment by jordanbaird** [comment]
Unfortunately, macOS no longer provides reliable notifications when the wallpaper changes. The only solution currently is to refresh the captured wallpaper image every so often. The current interval strikes a balance between appearance and performance (updating too often will result in high CPU usage). Unless Apple decides to reimplement their wallpaper notifications, there unfortnuately isn't anything we can do about this.
