### ISSUE TITLE
[Feature Request]: Dim the menubar to work with hazeover harmoniously

### ISSUE THREAD

**Issue by Rereyuop** [jordanbaird/Ice#461]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Hazeover is a good software that dim other windows when you focus on the current app. When ICE take control of the menu bar, Hazeover could not dim the same area.

<img width="1613" alt="图片" src="https://github.com/user-attachments/assets/f4f332a5-acbe-4044-abb9-6a0f4f8601a8" />

**Comment by jordanbaird** [comment]
Ice creates the menu bar appearance by adding an overlay directly above the menu bar. It already adds it at the lowest layer it can. I would talk to the developer(s) of Hazeover and ask them to move their dimming overlay to a higher layer.
