### ISSUE TITLE
[Bug]: Ice Bar only functional when settings app is launched

### ISSUE THREAD

**Issue by SeoliteQ** [jordanbaird/Ice#471]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Ice bar does not work for me unless I have the settings app open in the background. I can click any of the icons, but nothing happens until it is open.

### Steps to Reproduce

1. Put any icon on ice bar.
2. Close settings app.
3. Click any icon on ice bar.
4. Nothing happens.

### Ice Version

0.11.12

### macOS Version

15.2

**Comment by jordanbaird** [comment]
Can you post a screen recording of exactly what's happening to help me better diagnose the issue?

**Comment by SeoliteQ** [comment]
Apologies, I seem to have been able to fix it by reinstalling ice and re-setting the app's permissions. In my previous instance, I put some apps on the ice hidden menu bar, but upon clicking any of these icons, nothing happened. Only if the macos settings app was open in the background, did selecting any of the icons in ice's hidden menu bar work.

**Comment by SeoliteQ** [comment]
Apologies, I seem to have been able to fix it by reinstalling ice and re-setting the app's permissions. In my previous instance, I put some apps on the ice hidden menu bar, but upon clicking any of these icons, nothing happened. Only if the macos settings app was open in the background, did selecting any of the icons in ice's hidden menu bar work.
