### ISSUE TITLE
[Feature Request]: Support of other macOS versions except Sonoma

### ISSUE THREAD

**Issue by ZuBB** [jordanbaird/Ice#49]
### Description

Hi there! Thanks a lot for this software and the fact that you actually keep it updated.

Is there any technical reason why only Sonoma is supported? If not, is there any chance that you will add support (later) for other versions as well?

**Comment by jordanbaird** [comment]
There are a number of APIs that Ice uses that are only available on Sonoma. While technically possible to make it work on lower macOS versions, it would require significant rewrites all around. I decided that rather than devote my time to that, I'd rather make an app that supports more features.

**Comment by ZuBB** [comment]
It perfectly makes sense, @jordanbaird. As a side note, I recommend adding a note on the minimal supported OS version to the docs/readme to avoid similar questions.

Thanks for the answer
