### ISSUE TITLE
[Bug]: Menu Bar Appearance

### ISSUE THREAD

**Issue by Xytronix** [jordanbaird/Ice#50]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

I was able to set the appearance of the menu bar black.

Now it doesn't change the background of the menu bar at all.
It only adds a slight effect on it.

### Steps to Reproduce

1. Change color to black and solid

### Ice Version

0.8.0

### macOS Version

14.4.1

**Comment by jordanbaird** [comment]
I'm afraid you're misunderstanding what the tint feature does. Like you observed, it applies a slight tint over the top of the menu bar. It doesn't change the actual color, and never has. In fact, Ice _can't_ do that without changing the desktop background to have a colored stripe at the top. For now I've decided against adding that feature, as it would disable any dynamic wallpapers the user might have.

**Comment by Xytronix** [comment]
> I'm afraid you're misunderstanding what the tint feature does. Like you observed, it applies a slight tint over the top of the menu bar. It doesn't change the actual color, and never has. In fact, Ice _can't_ do that without changing the desktop background to have a colored stripe at the top. For now I've decided against adding that feature, as it would disable any dynamic wallpapers the user might have.

@jordanbaird is this maybe something you would look into? For now, I use TopNotch for coloring the menubar. Unfortunately, I have to run it every time after standby or reboot.

**Comment by jordanbaird** [comment]
Yeah, I can do it. I've had enough people ask about it at this point that I think I'll add it. It's being tracked in #82 now.
