### ISSUE TITLE
[Bug]: Not showing multiple identical icons

### ISSUE THREAD

**Issue by lume96** [jordanbaird/Ice#61]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

Hi there,
I do use Onedrive and I do have 2 accounts set up (one pro and one personal). This results in 2 identical OneDrive icons showing in the menu bar, one for each account.
Ice however only shows one of the 2 icons.
While I don't feel the way Microsoft handles the topic (showing multiple icons) is the best approach, it is how it is and I would expect ICE to also show the 2 icons to be able to access the settings of each Onedrive account.
Thanks

### Steps to Reproduce

1. Install OneDrive
2. Set up at least 2 accounts to have 2 menu bar icons

### Ice Version

0.8.0

### macOS Version

14.5

**Comment by jordanbaird** [comment]
It shouldn't matter if there are multiple identical icons because Ice only arranges by section. In fact, it doesn't have the ability to manage icons individually. Have you checked the "always-hidden" section to see if it was inserted there by default?

**Comment by lume96** [comment]
Hi,
just came here to say that I cannot reproduce the issue with v 0.9.
Don't know if this is related to v0.9 or to my system.
Anyway, solved as far as I am concerned.
