### ISSUE TITLE
[Bug]: fullscreen in VLC does not cover menubar properly

### ISSUE THREAD

**Issue by mdemaine** [jordanbaird/Ice#63]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

I've attached a screenshot showing the issue. The menubar is not properly getting covered by the fullscreen function in VLC. I've checked on YouTube in Firefox, and that fullscreen works correctly.

M2 Pro Mac Mini
Sonoma
VLC 3.0.20

### Steps to Reproduce

view VLC file in fullscreen

### Ice Version

0.8.0

### macOS Version

Sonoma 14.5

### Screenshots

<img width="2560" alt="Screenshot 2024-05-22 at 6 04 25 PM" src="https://github.com/jordanbaird/Ice/assets/26127219/a38e690f-2d77-48f1-af16-a9f994b7ccbc">

**Comment by mdemaine** [comment]
I realized that if I mouse over the menubar area, the issue resolves itself. I hope this extra info is helpful.

**Comment by jordanbaird** [comment]
Could you try the following steps to see if this fixes it:

1. Open VLC's settings
2. Click "Show All"
3. Navigate to Interface > Main interfaces > macosx
4. Check "Use the native fullscreen mode"
5. Restart VLC

That being said, if this does fix it, it's just a bandage over the problem. It looks like VLC uses its own fullscreen method that Ice will have to check for specifically.

**Comment by mdemaine** [comment]
Indeed, that setting resolves the issue. Thanks for the info. 

I'm very appreciate of this software. It is a marvelous alternative to Bartender.

**Comment by jordanbaird** [comment]
Closing this, as there have been multiple related reports of similar issues. I have opened #140 to track them together.
