### ISSUE TITLE
[Bug]: Show ice icon not working

### ISSUE THREAD

**Issue by Raxiel1987** [jordanbaird/Ice#64]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

i don't know what happened:
today i tried to unistall and reinstall ice, and now the show icon don't work, there's an empty space that i can click and work, but the icon don't show up

### Steps to Reproduce

sho icon tottle

### Ice Version

0.80

### macOS Version

latest

**Comment by jordanbaird** [comment]
If you're comfortable with the Terminal, copy and paste the following command:

`defaults export com.jordanbaird.Ice - > ~/Desktop/com.jordanbaird.Ice.plist`

Then go to your desktop, find the file called "com.jordanbaird.Ice.plist", and upload it here. I'll take a look at it to see if something has been corrupted.

**Comment by jordanbaird** [comment]
It looks like the Ice icon somehow got moved into the hidden section of the menu bar. If you can get it to appear when you click the empty space, hold Command and start dragging it. Two arrows should appear that indicate the hidden and always-hidden sections. Drag the Ice icon somewhere to the right of the larger arrow. An example of the arrows is at the top of the README on the front page of this repository.

**Comment by jordanbaird** [comment]
You're welcome! :)
