### ISSUE TITLE
[Feature Request] Show active windows on the Menubar

### ISSUE THREAD

**Issue by Laicure** [jordanbaird/Ice#65]
### Description

Description:
I was using [MenuBar Dock](https://github.com/EthanSK/Menu-Bar-Dock) before and it seems abandoned now. Just chiming in if you can include that feature?

I mostly want to switch currently opened windows using the Menubar (just like Windows' taskbar).

Thanks!

**Comment by jordanbaird** [comment]
After thinking about this for a while, I've decided I want to keep Ice's feature set focused on menu bar management for now. If things change in the future, I'll definitely consider this then, but for now this isn't planned.
