### ISSUE TITLE
[Feature Request]: custom spacing between icons

### ISSUE THREAD

**Issue by aexvir** [jordanbaird/Ice#67]
### Description

I've been using bartender for a long while but now that the app has been sold I'm checking alternatives and I've seen ice mentioned multiple times. Glad to see an open source app that provides this functionality! 

The main thing I see lacking at the moment is the inability to set custom spacing between icons, as I really dislike the default spacing, it feels way too wide. I see this feature mentioned on the roadmap but didn't find any issue for it so I decided to create it.

**Comment by tv21** [comment]
I  just came here to ask the same thing, and for the same reason!  In Bartender the option is called "Menu bar item spacing" and I set it to "Small spacing - previous MacOS spacing"; it would be great if this could be implemented in Ice.

**Comment by jordanbaird** [comment]
Yep, this is doable! It's on the roadmap, I just haven't gotten to it yet. I can get it working within the next update or two.
