### ISSUE TITLE
[Feature Request]: Clicking on an empty space replaces all current menu bar items with the hidden ones

### ISSUE THREAD

**Issue by stagelevel** [jordanbaird/Ice#68]
### Description

I have currently moved away from Bartender, however, it has a great feature where if you click on an empty space in the menu bar, your current menu bar icons disappear and are replaced with your hidden menu bar icons. Clicking the empty space reverse this.

Would this small feature be possible to implement please?

At the moment, clicking on an empty space in the menu bar adds all your hidden menu bar icons to the left of the currently shown icons.

Thank you very much.

**Comment by jordanbaird** [comment]
It's definitely possible to implement, but it's actually pretty complicated. Ice isn't currently able to move individual icons, and instead has to hide them by section. It needs additional functionality to be able to rearrange the sections, which I have _mostly_ figured out, but there are still some bugs that make it not ready for release.

**Comment by stagelevel** [comment]
Thank you very much for your quick reply, I didn't realize it was more complicated feature but I appreciate all the work you doing towards the app!

**Comment by 667-1** [comment]
I also like the ability to alternate between hidden and displayed areas. Hope the author can support it.

**Comment by rEes9P** [comment]
+1 for the ability to hide the primary menu bar apps when the secondary one is selected!

**Comment by jordanbaird** [comment]
There have been multiple similar feature requests, so I've opened #240 to track them together.
