### ISSUE TITLE
[Feature Request]: Always Show option

### ISSUE THREAD

**Issue by tsuliwaensis** [jordanbaird/Ice#69]
### Description

I couldn't find this in the current version. A nice feature would be the ability to always show certain icons (the "Always Show")

**Comment by jordanbaird** [comment]
This is there, you just have to Command + drag items to the right of the larger arrow (the arrow will show up once you start to drag if you don't have the "Show section dividers" setting enabled)

**Comment by pjlsergeant** [comment]
I'm a reasonably smart and technical user, and had to go digging around in the closed issues to work out how to do this. App looks great, but it's absolutely not clear how to move items to the always shown menu! Strongly recommend even a one-line explanation in the README or on the main site here

**Comment by jordanbaird** [comment]
@pjlsergeant I agree. I've been meaning to put together a little onboarding screen, but an explanation in the README would probably be good too.

**Comment by neontuna** [comment]
Agree on the readme, and also apologize we're all dogpiling as everyone abandons Bartender but I was pretty confused as well on how to do this.
