### ISSUE TITLE
[Bug]: Limit on the number of icons that can be shown

### ISSUE THREAD

**Issue by SoWizard** [jordanbaird/Ice#70]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

New user moving over from BarTender. Not sure if this is a bug regarding the "Always-hidden" section or a notch-related bug.

There seems to be a limit on the number of icons that Ice can show in the Hidden section. Any more than that and the items aren't shown at all, except for when I quit Ice. See below where 1Password disappears unless I quit Ice.

<img width="1710" alt="SCR-20240605-mdzr" src="https://github.com/jordanbaird/Ice/assets/18180575/9868312a-438c-4093-a31d-49f0d716ff80">

<img width="1710" alt="SCR-20240605-mdxz" src="https://github.com/jordanbaird/Ice/assets/18180575/49784329-13c8-4bf7-95b5-58c492045046">

It does not show up in the "Always-Hidden" section (maybe I don't know what this is exactly, as no matter what I do nothing happens when I Show/Hide the Always-Hidden section.

### Steps to Reproduce

Display a large amount of icons on a MacBook with a notch.

### Ice Version

0.8.0

### macOS Version

14.5

**Comment by jordanbaird** [comment]
This is related to the notch. I'm planning on implementing a secondary bar that appears below the menu bar (similar to the Bartender Bar) that should resolve the problem. I'm going to close this issue, since issue #1 already addresses it.
