### ISSUE TITLE
[Feature Request]: Make the Screen Recording permission optional

### ISSUE THREAD

**Issue by miodragnikac** [jordanbaird/Ice#75]
### Description

Many people don't feel comfortable enabling this option so please make it optional and if it is needed for Menu bar styling then disable that option until permission is enabled. Most of us want to hide the icons and nothing else.

Currently, you cannot even open the app if you do not allow Screen recording permission.

**Comment by Write** [comment]
I'm pretty it's absolutely necessary. It's not just for Menu bar styling. (i'm not the dev)

**Comment by holdit** [comment]
If the permission isn't needed just to hide icons, then I agree that it should be optional. Apps shouldn't have more permissions than required.

Also, maybe README.md should have a section with the list of permissions and an explanation why they're needed? That would also help when someone has questions about this.

**Comment by CrypticComputation** [comment]
As @Write said, I'm quite certain the app would cease to function properly without the screen recording permission. However, with the influx of new users due to Bartenders acquisition I do agree that once the new version is released, the ReadMe could have an FAQ added

**Comment by miodragnikac** [comment]
Maybe it is needed just for the "show on mouse hover" function and if that's the case also disable that option in the settings until enabled. That permission should be optional.

**Comment by CrypticComputation** [comment]
Absolutely. I understand your concern. That is a gargantuan amount of trust to give an app. Just to be sure though, as I'm sure you're aware. As of MacOS 14, there are better indicators to let you know when your location, microphone and screen recording are in use for a peace of mind

**Comment by JonathanVarild** [comment]
I've been messing around with the code a bit and this certainly seems possible. Even without the Screen Recording permission, I am still able to hide the menu bar items, etc. The menu bar appearance can however not be customized and returns a permission error as expected.

**Comment by vr8hub** [comment]
Just came here to comment on this as well. If we don't care about the Menu Appearance (I don't), then we shouldn't have to give this permission before Ice will even operate.

**Comment by jordanbaird** [comment]
I can work on this. @JonathanVarild is right. Screen recording is not required to hide menu bar icons. It _is_ required to move them individually from within the app interface, but Ice doesn't have that feature yet.

**Comment by vr8hub** [comment]
Awesome! When Ice gets the feature to move them within the app interface, please make that optional as well. Thank you for your work!

**Comment by jordanbaird** [comment]
@leoravagnani Accessibility permission is required in order for Ice to be able to get the location of the menu bar items and application menus. It's required for features like show on hover/click/scroll, auto rehide, and hiding the application menus, which are all what I would consider critical features.

**Comment by leoravagnani** [comment]
@jordanbaird makes sense! maybe Hidden Bar is using older APIs then, I remember the dev of the fork I'm using mentioning something like that. Still as people said above it would be nice to have the reasoning for the permissions on the README or a FAQ, the Bartender debacle has people rightfully paranoid haha

**Comment by jordanbaird** [comment]
Update on this: It's still on my list, but making this change will require reworks all around the app, so it keeps getting pushed back. I'll definitely get it done, there have just been other things that have taken higher priority.

**Comment by miodragnikac** [comment]
Thanks, looking forward to it

**Comment by pranavgoel29** [comment]
@JonathanVarild Are there any updates on when this will be available.
Thanks, awesome work with the app.
