### ISSUE TITLE
[Feature Request]: Select items on each sections

### ISSUE THREAD

**Issue by foux** [jordanbaird/Ice#76]
### Description

OK, I must be really dumb by I can't find how to select on which category (always hidden, hidden, always show) an item must belong.

Is it not possible or am I missing something?

Thanks!

**Comment by jostyee** [comment]
see https://github.com/jordanbaird/Ice/issues/69#issuecomment-2148782297

**Comment by foux** [comment]
Thanks @jostyee. Perhaps this should be added to the readme as mentioned in https://github.com/jordanbaird/Ice/issues/69#issuecomment-2149228759

**Comment by jordanbaird** [comment]
It's in the README now. There will also be a feature added at some point that lets you move items within the app's interface.
