### ISSUE TITLE
[Bug]: mouse getting captured and moved

### ISSUE THREAD

**Issue by dennispg** [jordanbaird/Ice#77]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

Randomly, my mouse moves to the top right corner of the primary screen. I'm not sure what is causing it, but it definitely stops happening when I quit ice. I believe it is related somehow to the screen recording permission.

### Steps to Reproduce

Happens randomly as long as Ice is running, stops when I quit the app. I also use another app called Sidebar to replace my dock, and it exhibited the same behavior when I turned it's live previews feature on.

### Ice Version

0.8.0

### macOS Version

14.4.1

**Comment by jordanbaird** [comment]
Ice isn't doing anything with the mouse, so I don't think it's that. What other apps do you have open?

**Comment by dennispg** [comment]
I restarted Sidebar and now it seems to be doing ok.. I believe something about the screen recording triggering it. We can probably close this.

**Comment by jordanbaird** [comment]
Okay. I agree it's probably a bug in Sidebar. I'll close this for now. If you find that it might not be related to Sidebar, feel free to reopen it and I'll investigate.
