### ISSUE TITLE
[Feature Request]: Explain how to move the icons in the README.md

### ISSUE THREAD

**Issue by spfmoby** [jordanbaird/Ice#78]
### Description

Hi

It's quite simple: nowhere is explained how to put icons in a category or another (hidden/visible).
You try to move them using the mouse, it doesn't work
You look through every menu in the app settings, nothing

After a while someone suggests you cmd+click and drag... and... it works!

With the "end" of Bartender, you will probably have a wave of new users, so I think it should be explained, even in one simple line or two after the install section. Something like the following could be useful:

### How to use
simply press cmd + click on the icon you want to put in the hidden section and drag it on the left of the "<" arrows that appears.
Click on the dot icon to hide or reveal the hidden apps.

**Comment by infused-kim** [comment]
+1 I was also very confused for this and only figured it out after finding this issue.

**Comment by jonstump** [comment]
Funny this was opened only a couple hours before I installed this app. Thanks @spfmoby for opening this issue. I suspect the rest of the horde coming from Bartender will appreciate this as much as I did.

**Comment by jordanbaird** [comment]
Yep, we can do this. There's a pull request open that adds an explanation along with a video to the README. I'm also going to add an onboarding panel that appears the first time you launch the app, after granting permissions, that explains some of the key features.
