### ISSUE TITLE
Spiking CPU usage

### ISSUE THREAD

**Issue by riegaz** [jordanbaird/Ice#8]
Hi there,

I see Ice consuming rather a lot CPU when just running (6%) and up to 20% when hovering my menubar. This is rather a lot for what it is. I guess there is potential to reduce CPU consumption.

**Comment by jordanbaird** [comment]
Yes, I agree. In this early stage of development, I've mainly been focusing on getting the app working, rather than optimizing it. As things get closer to a 1.0 release, lots of optimizations will definitely happen.

**Comment by ximmox** [comment]
Hi, 

I second this, I too noticed that Ice takes a lot more CPU cycles than Hidden Bar.
BUT it does a lot better then Hidden Bar already (hover to show icons, not losing focus of the active windows while showing icons etc).

I like it just for the icon hiding, I don't want to modify my menubar's background etc.
For this I would also prefer to not give permission to screen record, but this is not optional when initially setting up Ice.
Maybe you could make that optional and remind the user in the Menu Bar Appearance section, that this has to be enabled if one wants to use it?

Thanks & regards

**Comment by jordanbaird** [comment]
@ximmox Could you open a separate issue for this?

**Comment by riegaz** [comment]
@jordanbaird wow, the CPU consumption dropped considerably. It idles at about 0.2 for me which is awesome. During interacting with Ice it also looks good. However, I don't mind too much how the CPU consumption looks like as this is happening quite rarely. Well done!

**Comment by jordanbaird** [comment]
Nice! I'll go ahead and close this issue then.
