### ISSUE TITLE
[Bug]: Hide the Hidden Section does nothing....

### ISSUE THREAD

**Issue by omarshahine** [jordanbaird/Ice#80]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

Not sure what I am doing wrong, but Hide / Show the Hidden Section doesn't do anything for me. It always shows icons in the Hidden Section. When I click and then select Show/Hide the menu items don't even flip / toggle over to Show/Hide.

### Steps to Reproduce

1. Right Click the dot
2. Click Show or Hide Hidden section

### Ice Version

0.8.0

### macOS Version

14.4

### Screenshots

https://share.cleanshot.com/lPkYwnDX

**Comment by jordanbaird** [comment]
I'm not sure I understand. It's doing what it's supposed to do. What are you expecting?

**Comment by omarshahine** [comment]
Maybe I don't understand the difference between "Hidden Section" and "Always Hidden Section".

Items in the "Hidden Section" are never hidden for me.

**Comment by jordanbaird** [comment]
The hidden section is to the left of the larger arrow and is what gets toggled when you click the Ice icon. The always hidden section is to the left of the smaller arrow and is only visible when you specifically show it (either by Option+clicking the Ice icon, using the right-click menu, or a hotkey). You may be getting things confused and are expecting items to the left of the Ice icon to be hidden, but you can actually put the Ice icon wherever you want without it affecting the sections. From what I saw in the video, the behavior is correct. I'm going to close this for now, but if you feel there is still a problem, feel free to reopen it :)

**Comment by omarshahine** [comment]
I guess what I am saying is that is not what I am seeing. When I clock the Ice icon, the items that are "Always Hidden" show and hide, but nothing happens with the items in between.

Here is another video. Maybe I'm over thinking this?

https://share.cleanshot.com/x8fx5wYR

**Comment by jordanbaird** [comment]
What you're calling the "hidden" section is actually the "visible" section, and what you're calling the "always hidden" section is actually the "hidden" section. It isn't the Ice icon that starts the hidden section, but rather that first arrow (it shows up in your second screen recording). The "always hidden" section can only be shown if you explicitly use one of the methods outlined above. Just clicking the Ice icon with no modifier keys shows the "hidden" section. Icons to the right of the arrow are always visible. Here's a screen recording that demonstrates the two different sections:

https://github.com/jordanbaird/Ice/assets/90936861/320f4382-477b-40e2-8e29-e43efaad8d78

**Comment by omarshahine** [comment]
Ooooh. Wow thank you.
