### ISSUE TITLE
[Bug]: Items automatically get re-hidden even with disabling the feature

### ISSUE THREAD

**Issue by okuramasafumi** [jordanbaird/Ice#81]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

First of all, thank you for the great app!
I believe I've disabled "Automatically rehide" feature in setting, but the items get hidden after switching the front app.

### Steps to Reproduce

Configure Ice as the screenshot

### Ice Version

0.8.0

### macOS Version

14.5

### Screenshots

![CleanShot 2024-06-06 at 01 01 12@2x](https://github.com/jordanbaird/Ice/assets/1012014/7234e523-b327-40e9-84bc-c25cfdff63e4)

**Comment by okuramasafumi** [comment]
I think this issue is irrelevant now.

**Comment by kennguyen107** [comment]
@okuramasafumi Why is this issue irrelevant now? I think what happened to you is because you need to go to "advanced" section then "temporarily shown item" delay, but now I don't know what the "automatically rehide" feature even does.
