### ISSUE TITLE
[Feature Request]: Is it possible to move the position when expanded?

### ISSUE THREAD

**Issue by KTsarlz** [jordanbaird/Ice#84]
### Description

Came from Bartender after seeing the recent update issues..

Great work! Loving this so far! 
But can we add the feature that the expanded menu be under the menu bar?

**Comment by SteveMattan** [comment]
This is already on the roadmap as " Display hidden items in a separate bar (e.g. for MacBooks with the notch)".

**Comment by jordanbaird** [comment]
Thanks for the feature request! As @SteveMattan said, it's already on the roadmap. I'm going to close this issue to keep things organized and in one place.
