### ISSUE TITLE
[Bug]: Show on hover setting does not work

### ISSUE THREAD

**Issue by alexkli** [jordanbaird/Ice#88]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

I enabled "Show on hover" but it does not seem to do anything. When I hover over the menu bar nothing happens. I tried anywhere -  left of the Ice icon, the Ice icon itself, to the right of the Ice icon. Also kept the mouse still and hovering for a few seconds - nothing.

### Steps to Reproduce

1. enable "show on hover"
2. hover over menu bar and Ice icon in menu bar

Expected: show hidden items

Actual: nothing happens on hover

### Ice Version

0.8.0

### macOS Version

14.3

### Screenshots

Shows the settings and the menubar as it looks when my mouse is hovering over the Ice icon (chevron).

<img width="934" alt="ice-hover-screenshot" src="https://github.com/jordanbaird/Ice/assets/229022/c1e5b628-18b9-4389-9f3c-b74b388660bc">

**Comment by jordanbaird** [comment]
Is there a chance you're using a second display? There's a bug in 0.8.0 that breaks cursor detection within the menu bar on any display that isn't the "main" one. It's been fixed, I just need to get a new release out.

**Comment by alexkli** [comment]
Yes, indeed I am currently using my Macbook pro with 2 external displays. The entire menu bar shows on both displays (I forgot how I got there but it's ok for me) and hovering does not work on either display.

Thanks! 👍

**Comment by jordanbaird** [comment]
No problem! I'm going to close this for now, but if, for whatever reason, the new release comes out and the problem still persists, feel free to reopen it or open a new issue
