### ISSUE TITLE
Hovering menubar keeps showing icons

### ISSUE THREAD

**Issue by riegaz** [jordanbaird/Ice#9]
When hovering the menubar while leaving the display to the other display, the menu items don't disappear anymore. This functionality doesn't seem working well.

Also, when one is using two displays, one menubar is deactivated (grayed out) in this case Ice shouldn't show icons when hovering. At least for me, this would make sense.

**Comment by jordanbaird** [comment]
I just noticed this, as well. When I first designed the app, I wasn't taking multiple displays into account. I recently switched to a multi-monitor setup, and will be focusing on getting things working correctly.

As for your second point, the grayed out icons on other displays simply mirror the icons on the main display, so it isn't possible for them to remain hidden while the main icons are shown. There may be some hacky workarounds, but I'm not sure it's worth it.

**Comment by riegaz** [comment]
You are right of course that the icons are the same between both menubars. However, the hovering should only work on the active menubar I would say. If I want the menubar and Ice to be active again, I would then have to click the grayed-out menubar first.

**Comment by jordanbaird** [comment]
Ah, I see what you're saying. Yes, that should be doable, and I agree that should be the correct behavior.
