### ISSUE TITLE
New app icon 

### ISSUE THREAD

**Issue by miodragnikac** [jordanbaird/Ice#90]
### Description

I asked Dall-E to create the new icon for the app and this is what he came up with. 

The fourth one is my favorite. 
Would love to see the app using this modern one. 

### Screenshots

![IMG_2744](https://github.com/jordanbaird/Ice/assets/10221888/b9531c86-64ee-40ca-8de6-9b7f15669fed)
![IMG_2745](https://github.com/jordanbaird/Ice/assets/10221888/b03c9bea-55f3-4160-8667-810c43935469)
![IMG_2746](https://github.com/jordanbaird/Ice/assets/10221888/1ca18811-0838-43ab-9637-7d21f77383b5)
![IMG_2747](https://github.com/jordanbaird/Ice/assets/10221888/ab138ed2-7c98-4dc1-8c92-8dc4986c9f9e)

**Comment by SteveMattan** [comment]
In the settings, General tab, you can pick your own icon, for the menu bar. For the app itself you can change that in the Get Info panel, copy the image you wish to use, click the icon in the Get Info panel, and paste.

**Comment by jordanbaird** [comment]
Thank you for the suggestions. I personally like the current icon. I think it's simple and elegant. And while AI is great, it has a tendency to "look" like AI.

That said, I'm going to close this issue, as I don't see any problem with the current icon. Thank you, regardless!
