### ISSUE TITLE
[Bug]: <The Menu Bar got a huge blank without any icon in it>

### ISSUE THREAD

**Issue by biigthinker** [jordanbaird/Ice#92]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

<img width="1920" alt="iShot_2024-06-06_10 31 52" src="https://github.com/jordanbaird/Ice/assets/98293213/c57970e4-2c2c-49a1-a1d1-a26dc6bcae65">
check here for a image info. 

### Steps to Reproduce

can't fix it with reboot or reinstall 

### Ice Version

0.80

### macOS Version

14.5

**Comment by jordanbaird** [comment]
Is this still a problem as of the latest release (0.10.3)?

**Comment by jordanbaird** [comment]
Closing as stale.
