### ISSUE TITLE
[Bug]: Lack of sync between displays

### ISSUE THREAD

**Issue by zmkstn** [jordanbaird/Ice#93]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

Hidden and always-hidden sections do not toggle off (or unhide) on secondary displays once toggled from the primary display. Also, toggling keyboard shortcuts to hide and show the menu bar sometimes changes the focus from the secondary display, to the primary display (even if I want to maintain focus on the secondary display). Slightly related, the menubar of a secondary display is not a clickable or scrollable field.

The ideal state is for me to click, scroll, or utilize shortcuts to hide and unhide the menu bar on any display. I also wish for the events to be synced across displays.

### Steps to Reproduce

 1. Toggle the hidden and unhidden sections
 2. Un-toggle the sections
 3. Notice how other display does not un-toggle the items. Also notice how chevron changes direction, but menubar items are still visible.

### Ice Version

0.8.0

### macOS Version

14.5

**Comment by jordanbaird** [comment]
Most of these bugs should be fixed in the upcoming release. I think the only thing that isn't is the focus switching to the main display. Could you open a separate issue specifically for that problem, so I can close this one?
