### ISSUE TITLE
[Bug]: Not working on external monitors

### ISSUE THREAD

**Issue by vandrieu** [jordanbaird/Ice#96]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

On MacBook Pro (ARM, M1 Pro), hidden icons do not show when clicking nor hovering on the menu bar on external monitors, Ice only works on the main built-in MacBook monitor:

https://github.com/jordanbaird/Ice/assets/46876905/e613bb7e-347a-43f4-be2b-295a919ddfbe

### Steps to Reproduce

- Enable "Show on click" option
- ✅ Click on the menu bar of the built-in MacBook monitor: hidden icons are shown
- ❌ Click on the menu bar of an external monitor: hidden icons are not shown

### Ice Version

0.8.0

### macOS Version

Sonoma 14.5

### Side note

Thank you so much for this project!

**Comment by jordanbaird** [comment]
Yeah, this is a known issue that has been fixed on `main` (see #88). And you're welcome! Glad it's useful :)
