### ISSUE TITLE
[Bug]: hides everything, including itself regardless of settings

### ISSUE THREAD

**Issue by black-snow** [jordanbaird/Ice#98]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

I've just installed ice via brew. Started it, granted permissions. I then clicked the dot, Cmd+Moved my docker to the left and suddenly everything was gone. Just the quick-toggle menu and the date/time remained. The dot was gone, too. I could pop open the ice settings by starting the app again but none of the settings brings back the ice toggle or any other icons.

### Steps to Reproduce

s.a.

### Ice Version

0.8.0

### macOS Version

14.5

### Screenshots

![grafik](https://github.com/jordanbaird/Ice/assets/579733/83f1b14f-5f66-4b39-ac04-3b07043de0d3)

**Comment by jordanbaird** [comment]
Seems like the Ice icon (the dot) got moved into either the hidden or always-hidden section. If you have the "show on click" setting enabled, click an empty space in the menu bar to show the hidden section. If the Ice icon isn't there, Command+dragging any icon should show the entire menu bar. Find the Ice icon and drag it to the right of the larger arrow. If you don't have "show on click" enabled, you can right-click an empty space in the menu bar to open the app settings.

I'm realizing now that the current way Ice works is a little unintuitive. I'll be working on some changes that will hopefully prevent things like this from happening in the future.

**Comment by black-snow** [comment]
![grafik](https://github.com/jordanbaird/Ice/assets/579733/a8fa7584-dad5-407e-8dea-2ef821fe925b)

Show on click is enabled. Clicking on empty space in the bar does nothing, though. There's no way to get the icons back (except from quitting ice ...).
@jordanbaird 

Thanks for the quick reply btw.

**Comment by jordanbaird** [comment]
Are you by chance using a secondary display? There's a known bug in 0.8.0 that prevents "show on click" and similar from working on displays other than the main one.

**Comment by igoooor** [comment]
I have the exact same behavior as described in the initial messages as well as the follow up.
However it only happened to me on 1 out of my 3 macs

**Comment by igoooor** [comment]
but I think you're right, I was moving icons around, but the 2nd chevron was not visible at that moment for some reasons (usually it is), and after moving an icon, the "normal" ice icon was in the always hidden I believe.
I don't know what I did special but I was able to recover it

**Comment by Drewtopia** [comment]
When I first installed the Ice app on my MacBook Pro (MBP) without an external display, I couldn't see any arrows whilst dragging icons.

Today, I connected my MBP to an external monitor, and with the larger display, the arrows appeared, allowing me to rearrange the icons. I thought the issue was resolved.

However, after disconnecting the external monitor, the arrows disappeared again, and the icons lost their order.

**Comment by black-snow** [comment]
> Are you by chance using a secondary display? There's a known bug in 0.8.0 that prevents "show on click" and similar from working on displays other than the main one.

Yup. Worked fine on the primary display, thanks! The icons were at different positions on display 2 as well. I guess this issue is now a bit too fuzzy to keep it open. I'd suggest @Drewtopia and perhaps @igoooor open another one with the respective steps. What do you think?

Closing this for now, assuming that @jordanbaird tracks the multi-display issue somewhere else :)

Thanks y'all and @jordanbaird in particular for obvious reasons ;)
