### ISSUE TITLE
[Feature Request]: state system requirements clearly on the website and in the README

### ISSUE THREAD

**Issue by fingolfin** [jordanbaird/Ice#99]
### Description

The README has a question "Why not support earlier operating systems", and then answer for that seems to imply that this software requires macOS 14 or newer. But I actually couldn't find any explicit statement about this on the website, or earlier in the README. So I think it would be a good idea to add something like "System requirements: macOS 14 or newer" to the website and README.

**Comment by jordanbaird** [comment]
The website and Gumroad page now state the system requirements at the top. Thanks for bringing this to my attention :)
